### ISSUE TITLE
ViewModels may not update when properties swap between null and a valid reference

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1003]
I demo'd this on a screenshare but the setup is fairly complicated. Here's what I think the repro steps are:

**Goal:** have a mission card on the pause screen that shows if the player is in a mission and hides if the player is not.

**Setup:**

1. Have a ViewModel such as `PlayerViewModel`
2. Have a ViewModel such as `MissionViewModel`
3. Have a property on the `PlayerViewModel` that is an instance of `MissionViewModel` such as `PlayerCurrentMission`
4. Create a UI ViewModel such as `PauseMenuViewModel`
5. The `PauseMenuViewModel` should have a `public PlayerViewModel Player` property
6. The `PauseMenuViewModel` should have a property that tunnels to the current mission such as `public bool IsPlayerInMission => Player.PlayerCurrentMission != null;`
7. Make sure all of the properties have the right `DependsOn` attributes set
8. Bind the UI element's visible property to the boolean
9. Observe that swapping the `PlayerCurrentMission` property does not trigger a UI update

This system is working well for things like the HUD and the station menu. They receive updates when tunneled properties _change_. But I think this is the first time I've tried setting something to `null`. It appears that property change events may not fire consistently when properties are changed back and forth between references and null values.

**Comment by profexorgeek** [comment]
Note that this repros in Masteroid as of this commit:
https://github.com/profexorgeek/masteroid/commit/02a8633d3947c059bc9e9c30f100fd44a618d4fb

**Comment by vchelaru** [comment]
Turns out this was not a bug.
