### ISSUE TITLE
Glue prevents customizing entity input movement control values in derived entities

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#101]
**Steps to reproduce:**

1. Create a new entity with platformer movement.
   ![image](https://user-images.githubusercontent.com/130681/118557095-b9e56b00-b732-11eb-86c8-b03519c5215a.png)
2. Create a new entity derived from the first entity.
   ![image](https://user-images.githubusercontent.com/130681/118557230-e4cfbf00-b732-11eb-83ea-b14870f207d7.png)
3. Set input movement type on the derived entity to "Platformer"

**Expected behaviour:**

Control values can be edited specifically for the derived entity.

**Actual behaviour:**

https://user-images.githubusercontent.com/130681/118558825-2e210e00-b735-11eb-87e6-ee7162a964ab.mp4

After a flash of control values appearing as they would normally, Glue jumps to the created `PlatformerValuesStatic.csv` file in the project explorer. Returning to the Entity Input Movement tab for the entity itself shows that the control values automatically added when creating `PlatformerValuesStatic.csv` are missing. The lines in the CSV file for the control values are also missing.

Adding control values afterwards with the "Add Control Values" _appears_ to work, but after navigating to another node in the project explorer and back, the values are no longer there.

https://user-images.githubusercontent.com/130681/118558866-37aa7600-b735-11eb-8258-756639f71713.mp4

**Comment by vchelaru** [comment]
Okay so the real problem begins with step 3. If a base entity is a platformer entity, then the derived entity must also be a platformer entity. Glue should not give you any choice! It does, and this is a bug. In fact, I didn't realize it at first, but inheritance for movement values was only implemented in the top down movement values. I had planned on doing it on platformer, but just hadn't gotten to it yet. Fortunately the top down work paved the way to make platformer MUCH easier to do.

Now if you create a derived entity, the derived entity is forced to have the Platformer movement type if the base entity does.

![image](https://user-images.githubusercontent.com/729631/118590058-ea42fe80-b75e-11eb-9aea-3710381c17e6.png)

Furthermore, the derived automatically gets all base platformer values:

![image](https://user-images.githubusercontent.com/729631/118590082-fc24a180-b75e-11eb-82de-9ca456ce5f8b.png)

These values can be inherited (default) or can be overwritten.

The derived can also add its own custom values, so it can have a mix of inherited, overwritten, and new values.

![2021_May_17_225327](https://user-images.githubusercontent.com/729631/118590166-27a78c00-b75f-11eb-84d6-e29a2dc759e2.gif)
