### ISSUE TITLE
F2 rename doesn't work on content files after double-click

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1014]
Steps to reproduce:

1. Double-click on a content file like a PNG, you'll see that the PNG Preview window shows up.
![imaxe](https://user-images.githubusercontent.com/24922404/229275615-ce563ee8-ed9d-44b9-8c9f-9d71c320daa0.png)

2. Press the F2 key and see that the content file node doesn't start the rename.
3. I suspected this might be because the preview window has the focus but I click on the same file node again to give it focus, press F2 and again the rename doesn't start.
4. Press any other content node, press F2 and the rename works.

There seems to be some inconsistencies about how the tree reacts to key presses.

**Comment by vchelaru** [comment]
Fixed

19f8a8e1c2bc838a8d721a27f203258e4a119aed
