### ISSUE TITLE
Add "Open Project" button to Glue's Quick Actions pane

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#102]
When starting Glue with no project open, show a button for "Open Project" underneath the "Create New Project" button. This should act the same as File->Open Project.

**Comment by vchelaru** [comment]
@profexorgeek would you be able to make an icon for this?

**Comment by profexorgeek** [comment]
Added to the FlatRedBallMedia repo. See this commit for file adds:
https://github.com/flatredball/FlatRedBallMedia/commit/36ec71605f049148033217a165ef24ba25b09d82

**Comment by vchelaru** [comment]
Fixed.

4cb3b4e8486e6cf887cd58824d20bf64b89400be
