### ISSUE TITLE
Resizing objects in the editor shouldn't appear glitchy

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1025]
There are two problems here that may be separate or related.

First of all, there is a problem with origin. In many cases in the editor, you will want components that scale from an end origin. For example, any sort of line between two points (such as a girder in a building) is easy to create if you position one side, then rotate and drag it from the PointA origin to the PointB connection point. But `IScalable` seems to only support a center origin. This means you either deal with all sizing being double the object's size, or you have to position line-like things at the center point and try to scale and rotate it to connect Point A and B simultaneously. Diagram:
![image](https://user-images.githubusercontent.com/711100/231833231-c6d85dbe-1954-4220-b8ff-bba93de2fca1.png)

You can work around origin issues by just allowing the box to scale from center origin but just scale your objects as if the origin was left. This just uses half the total width (or `ScaleX`) as your object width. It's annoying that all scaling boxes are double the desired size but it is a workaround. However, this also has usability issues because it moves the origin of the object and the scale box glitches out:

![resize-fail2](https://user-images.githubusercontent.com/711100/231833659-63d23472-1d9d-4988-83b2-e000d1bebb37.gif)

You can repro this by pulling this commit:
https://github.com/profexorgeek/masteroid/commit/967124551a640b9bc85c256ae80492f0f923ce6c

Repro:

1. Pull the commit above
2. Go to Entities > Stations > StationModules > StationModuleCore1
3. Select `HabStack1` object and attempt to size it

**Comment by vchelaru** [comment]
Glichyness has been solved

e9d5bcacd8f4837a284924df7019b288a82ba886

Sizing from the center is something that we need to discuss for a new interface for editing. I'm going to close this out for now.
