### ISSUE TITLE
Editor camera shouldn't constantly reposition itself

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1026]
Observe this editing experience. The goal here is to quickly drag, scale, and rotate components to create a unique layout. But every time a new object is clicked, the camera changes. This makes trying to quickly assemble components feel like total chaos to the user. Additionally, some components react slowly to property changes (see RotationZ changes) because the editor is spammed with value changes:

![editor-camera-chaos](https://user-images.githubusercontent.com/711100/231855205-facb41c7-a938-4b76-8695-93486db3281c.gif)

The camera should not move when a new object is selected in the editor. It _may_ still make sense for it to move when an item is selected in tree view. But the most likely scenario for level designers is working visually in the editor, not structurally in the treeview. The treeview should be considered a secondary resort when items can't be managed visually, and treeview-centric behavior should be secondary to a good visual editing experience.

**Comment by vchelaru** [comment]
Fixed repositioning.

**Comment by vchelaru** [comment]
Fixed
