### ISSUE TITLE
Objects get dragged when not clicking on them

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1029]
1. Open live edit on an entity
2. Select and object on that entity
3. Click and drag in an area not covered by the transform box
result: object moves and region select appears
expected: object is deselected and region select appears

**Comment by treesgobark** [comment]
https://user-images.githubusercontent.com/6179393/232234233-21038879-b3b8-47a8-8ed6-ca0788b11341.mp4

**Comment by vchelaru** [comment]
Great find!!!  Fixed commit 06668e06b1c7fc6084fe272e7b1f054d7f40dec5
