### ISSUE TITLE
Make line endings in generated code files consistent

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#103]
Right now, generated code files tend to end up with a mix of both LF and CRLF line endings, and this can cause Git to be very grumpy, especially if the user has a global .gitattributes file set up. Line endings in generated code files should be consistent, at least for the platform on which FlatRedBall tools are being run on.

**Comment by vchelaru** [comment]
I looked through a few sample projects and found this specifically on Game1.cs, but not any other screens or entities. Do you know of any other files which may have this problem?

**Comment by charabaruk** [comment]
I think the majority of the files that had this issue were the *.Generated.cs files (before I updated our project .gitignore to the one generated by Glue) but I'm sure that I've seen it in *.Generated.Event.cs as well, which isn't in the generated .gitignore file.

**Comment by vchelaru** [comment]
I was unable to reproduce the problem on *.Generated.cs files; however, I did reproduce it on Game1.cs when the game screen is assigned.

To solve this, I added a regex to replace \n with \r\n on any generated file, so this should catch most (if not all) cases: 5a7c40c91309993d57d1581b5707443fd8fea0f0

If there are any additional cases that you can reproduce after getting this update, please let me know and I can address it. I suspect there may be other plugins which don't follow this codepath.
