### ISSUE TITLE
Panning speed is very slow

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1030]
1. Open live edit
2. Pan view with middle mouse and drag
result: panning is very very slow compared to mouse movement
expected: panning amount is equal to mouse movement

note: panning speed appears to be irrespective of zoom level

**Comment by vchelaru** [comment]
I can't repro: 
![15_11 14 53](https://user-images.githubusercontent.com/729631/232242031-55f4dc79-7d49-41ea-a65c-8156e42e61f4.gif)
