### ISSUE TITLE
Add/Update .gitattributes

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#104]
Similar to how there's a "Add/Update .gitignore" item in the Update menu, there probably should be one for .gitattributes as well.

**Comment by vchelaru** [comment]
@coldacid I'm not familiar with a .gitattribute file. I've read through a little of this:

https://www.git-scm.com/docs/gitattributes#:~:text=A%20gitattributes%20file%20is%20a%20simple%20text%20file,followed%20by%20an%20attributes%20list%2C%20separated%20by%20whitespaces.

But I'm not sure what should be contained in the .gitattribute file or what problem it is solving.

Can you explain why we need it, and what the file should contain?

**Comment by charabaruk** [comment]
I myself think that this is a low-priority issue and something I could tackle; I just wanted to make sure it was here so I wouldn't forget about it.

As for .gitattributes itself, it helps normalize things for projects with multiple developers who are using Git. It's also essentially a requirement for use with Git LFS, since .gitattributes is where file type configurations go. For the project that I'm working on with zahlman, it lets us specify whether certain files should be treated as text or binary, what the line endings should be for text files, and diff hints for different types of files (e.g. I have a diff setup in my .gitconfig that can compare JPEGs by their metadata, by running a script that pulls the metadata into text files and then comparing those files instead of diffing the files themselves and just getting "binary files differ").

**Comment by vchelaru** [comment]
Yea, I'll leave it here for you to address since I suspect you'd be much faster at it than I. Thanks!

**Comment by vchelaru** [comment]
I'm closing this to help clear out todos. If anyone wants to work on this, feel free to reopen it.
