### ISSUE TITLE
Suggested updates for plugin tutorials

### ISSUE THREAD

**Issue by Kermittt** [vchelaru/FlatRedBall#1040]
I have a few minor fixes to suggest for the plugin tutorials after working through my first plugin...

https://flatredball.com/documentation/tutorials/glue-plugins/02-creating-a-plugin-project/
- Under **Adding Project References**, a few of the project names are not quite right.
 FlatRedBall.FlatRedBall.Standard is actually FlatRedBallStandard
 GlueFormscore is actually GlueFormsCore (inconsistant casing)
 SkiaGumMonoGame is actually SkiaGumMonogame (inconsistant casing)
- This is a lot of individual projects to reference per plugin. Instead of referencing multiple projects, it may be possible to create a project with no code which references all the required projects, then plugin developers would only have to reference that one project.

https://flatredball.com/documentation/tutorials/glue-plugins/05-glue-plugins-and-mvvm/
- The ImplicitUsings line in the project file causes an ambiguous reference on UserControl as it imports System.Windows.Forms.  Suggest adding instructions to remove that line.
- The example MainTutorialPlugin file seems to use a number of obsolete methods.  AddToTab, AddTab, RemoveTab.

**Comment by vchelaru** [comment]
PluginLibraries.csproj added

52ae41611730eae8cd9a135062ac584f7299166f

**Comment by vchelaru** [comment]
I believe these are all fixed now.
