### ISSUE TITLE
Display more information in ACHX preview

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1043]
It would be nice to have access to this information without opening the standalone app:

- Duration of the selected animation chain.
- Highlight the frames the selected animation chain references.

**Comment by vchelaru** [comment]
![27_18 13 46](https://user-images.githubusercontent.com/729631/235016480-84830ccf-2d18-4d18-b107-dfea92e96573.gif)

**Comment by mfigueirido** [comment]
Awesome. Thanks!
