### ISSUE TITLE
View source file in explorer says source file is null

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#106]
While following along with the RockBlaster tutorial, I dragged-to-add the sprite files to my player entity. Since it talked about moving files to the project, I wanted to confirm that. However, when I right-clicked￼ the file and selected **View source file in explorer** it shows an error titled "Error opening file" with a message saying "The object has a null source file."

After some more reproducing, I now see **View in explorer** that appears to be the choice I wanted. I was just too accustomed to the lower option for this in other dev tools, I guess.

**Comment by vchelaru** [comment]
This option should not have been shown for PNG files. Fixed.
0d3e514956a38a3bd1acb996eef0f7075f87ea85
