### ISSUE TITLE
Gum should correctly expose color state variables

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1068]
In the Kid Defense project, `UI_Work` branch I have created a Gum component called `KDElements/TextLabelValue`. This component has two text objects and is for displaying key value pairs. I want the Value text to be colorizable, so I have exposed the text instance's ColorCategory state. But, when trying to set the color category on an instance, the dropdown is empty.

Gum should allow me to set the color state on the instances.

This is reproduceable on the latest commit to the UI_Work branch in a Gum build that is fresh as of this issue posting!

![image](https://github.com/vchelaru/FlatRedBall/assets/711100/fd8abe7b-69ee-4632-80be-cc5e34a59218)

**Comment by vchelaru** [comment]
Fixed in Gum commit 4359167e4fc2ed35a3f057bfed3170955dfdab31
