### ISSUE TITLE
Gum should have animation chain dropdown

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1069]
When choosing a parent item in Gum, you get a dropdown of options but you can manually enter text to specify something that's not in the dropdown.

But when setting an animation chain, you must enter text. This means as a designer you must open an animation chain file to find valid chain names, and enter it correctly.

Instead, this should function like the Parent dropdown. It should load the valid chain names in the file but allow the designer to specify something different if they want to.

![image](https://github.com/vchelaru/FlatRedBall/assets/711100/0dafc011-866c-4f96-8654-06debda3ec51)

**Comment by vchelaru** [comment]
Fixed
