### ISSUE TITLE
Add support for adding custom types

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1071]
For example I would need the following:

1. Create a Sprite derived class and add custom logic to it for my game.
2. Be able to choose this derived class to add it through Glue to entities or Screen lists, so it gets properly instantiated with the derived type in generated code.

**Comment by vchelaru** [comment]
When we talked about this, I forgot that projects supported custom CSVs in their project. It's quite easy to do, and this is the base technology that Glue is built on top of. All standard types like Sprite and Circle use this, so hooking into this gives you a lot of power.

I've added some new documentation here:

https://flatredball.com/documentation/tools/glue-reference/menu/content/glue-reference-menu-content-additional-content-new-content-csv/creating-runtime-objects-as-instances/

I'm going to close this issue, but if this is not sufficient, please let me know.
