### ISSUE TITLE
Gum variable references should work as expected

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1073]
First, I'm not sure what "as expected" means but here's my problem...

I have text with a drop shadow that is created by just having two stacked text instances. I want them to both display the same text but the user should be able to specify text once and have it update both instances. I have tried:

- Exposing the `Text` property of instance A and then setting instance B's variable reference to instance A's `Text` property
- Exposing the `Text` property of instance A and then setting instance B's variable reference to the container's exposed property based on instance A

Neither of these work as expected. When I update the text property of an instance of the container, it only updates the text of the text instance that has the directly-exposed property. Some pics below to help illustrate this.

The layered text instances:
![image](https://github.com/vchelaru/FlatRedBall/assets/711100/a077ea03-7ed4-434e-a767-6e779a0cbeda)

Example variable bound to the other object:
![image](https://github.com/vchelaru/FlatRedBall/assets/711100/384556c3-f292-44c0-bfc0-834a48c7f6ec)

The result, not working as expected:
![image](https://github.com/vchelaru/FlatRedBall/assets/711100/7985cb50-0880-4165-96c7-0341c4b8d06b)

**Comment by vchelaru** [comment]
This particular use case has been solved in Gum commit 65a1a7be8e24ab0ef5aaff2adffbffe6e2f6d609

This (and many similar cases) will now work correctly in Gum; however, the variable references are not preserved at runtime. Therefore, if shadow text should update at runtime, this will require additional codegen work. 

I'm not sure how to go about this without bogging down the entire Gum runtime system with a ton of events, so I'm going to leave this out for now until I hear back about whether this is needed at runtime.

If it is needed at runtime, then perhaps we can add this noninvasively without requiring every property to have an event on it.

I'm going to close this issue and when we get specific situations we can open additional issues with those situations.
