### ISSUE TITLE
Gum DefaultChildContainer should work like other containers

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1075]
If you create a custom component with a `DefaultChildContainer`, it doesn't behave like other containers. Specifically:

- Alt + up/down doesn't properly move through containers
- Copy/Paste doesn't copy/paste children

**Comment by vchelaru** [comment]
Fixed alt arrow bug 
![15_20 29 36](https://github.com/vchelaru/FlatRedBall/assets/729631/8e06adcd-e3d8-4a76-a888-4747eb4a14ad)

**Comment by vchelaru** [comment]
Fixed. Gum commit: e627eb3d526135a8b1bbb04f3ed8265745d18aaa
