### ISSUE TITLE
Texture dropdown order seems unusual

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#108]
While working through the [Rock Blaster tutorial](https://flatredball.com/documentation/tutorials/rock-blaster/tutorials-rock-blaster-main-ship-entity/), I noticed the Texture variable dropdown for sprites orders the possible values in a way that isn't obvious.

For the tutorials sprite images named **MainShip1**, **MainShip2**, **MainShip3**, and **MainShip4**, it displays them in the order 3, 2, 1, 4. This also appears in a screenshot in that tutorial.

![Screenshot of Glue showing a Player SpriteInstance object's variables with the Texture variable listing MainShip files sorted in an unusual way.](https://user-images.githubusercontent.com/713665/118823897-99bec480-b876-11eb-88d8-beddf43478a5.png)

Feels like they should be sorted alphabetically, ideally with number considerations so that MainShip10 doesn't come between MainShip1 and MainShip2.

**Comment by vchelaru** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/729631/118917338-de397700-b8ed-11eb-9b40-76139d91c81f.png)
