### ISSUE TITLE
Gum should allow animation between states

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1089]
In the past, animation was created by adding 2+ states to an animation and choosing timings and interpolation between them. Now adding a state results in this timing flag and it's not obvious how to animate between states.

![gum-animation](https://github.com/vchelaru/FlatRedBall/assets/711100/82dc1f82-4704-4125-ada0-9d3e6f7a856c)

**Comment by profexorgeek** [comment]
Note, if you deselect and reselect the animation it seems like you can add frames as normal. So that is an easy workaround.

**Comment by vchelaru** [comment]
Fixed in commit 3ab3aa56e65cfccfcd1e897c0ada4a29198bcdfb
