### ISSUE TITLE
High CPU usage on GraphicalUIElement.AnimateSelf() despite no UI is visible

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1096]
It looks like Gum's animation code is doing deep checks on its hierarchy despite nothing is visible. This causes CPU usage which it's not doing anything productive. Some shots from the profiler:

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/1ab8f67e-b46e-4ce5-8ac7-476fb2ad766b)
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/3c5a102a-25a9-4d68-b639-5585a219bb9a)
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/6126bd8b-6801-4b97-bacf-2bd088cc6afc)

Tried doing an "early out" by returning when Visible == false, that makes it fast but the animations won't play when they should after that.

**Comment by vchelaru** [comment]
Fixed dedb75b4cba0a35901012fb3efe8a6f063da1bb0
