### ISSUE TITLE
Some GLSJ files repeat many times the same JSON data

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1098]
When inspecting my GameScreen.glsj file I noticed this:

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/72c74023-ee95-4e4d-94a3-da26a09b4838)

This doesn't seem to be causing problems but it could be an evidence of a bigger issue, so I log it.

**Comment by vchelaru** [comment]
I believe this is an old problem which has been fixed for new projects, but your project still has these properties.

If you remove all Properties with name DestroyOnUnload, I believe they will not come back and you will not have further problems.
