### ISSUE TITLE
I have two Gum IDB in my game

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1100]
This is a shot from the renderer showing batches ready to be rendered:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/b98afee8-b80d-44cb-adc4-7d35f6657833)

One is created from Global Content:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/92ada7ad-8225-4047-80ce-a0bc6200feeb)

And the other from GameScreen:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/5ac2f88d-b965-43ca-9ed3-fe84b8a606a1)

I think only the screen Gum IDB should be present. What should I do to remove the other? Is it a bug?

**Comment by vchelaru** [comment]
I believe this is a holdover of how IDBs worked. I have removed the unnecessary creation of another GumIDB which was in your Screen.Generated.cs

d922cc26684db8aa649986313d0aee74c36ee070
