### ISSUE TITLE
Language index starts at zero now, it started at one before

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1101]
This is the crash when attepting to change the language to the last available:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/28824074-f16d-4db8-9547-52b37ed53cfe)

This seems to happen since a recent change to the LocalizationManager. I could just change the way I manage language indexes so they start at zero but, wouldn't this change break localization on older games?

**Comment by vchelaru** [comment]
I believe this is already fixed. Please let me know if it still happens after the latest code.

**Comment by mfigueirido** [comment]
@vchelaru fixed it on 5793abd3a61986d712c2b61eecc5c512754e8663.
