### ISSUE TITLE
Animation Editor doesn't show correct proportions for big textures

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1106]
I did generate a big texture atlas but the Animation Editor doesn't show the new texture correctly. It looks like it's being shrinked:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/848906d6-e7a3-4d32-90c7-197f1b6f3fb4)

This is the same texture displayed in the windows app:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/4cda4a8e-a5ac-403a-99b3-6d4372df3d25)

As a result of this the frames highlighted in the animation editor don't match the correct area in the png.

I will send the files by PM. The problem can be reproduced by opening any of the .achx files contained in the folder.

**Comment by vchelaru** [comment]
Your image shows that the pixels are getting blurred, possibly on a resize:

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/ddfe4128-c265-478a-b1e9-d6bd31711a67)

But I opened it on my computer and everything is showing up correctly:

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/d5d1c6bb-1f3e-4b41-ab56-ef49daa46faf)

So it seems like there's something going on that might be computer-specific in skia sharp.

**Comment by vchelaru** [comment]
I misunderstood the problem. I now see that this is on the "old" external AnimationEditor. I thought this was happening on the new embedded editor in Glue.

Would it be possible to use the new one? We could expand the functionality. 

If this is impractical I may have to install VS 2019 to test.

**Comment by mfigueirido** [comment]
We are generating our achx files with a tool so we can avoid using the "old" standalone application. We'll try to use the new preview window instead. I'm closing this. Thank you!
