### ISSUE TITLE
Add frame information to the animation preview

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1107]
Since the old XNA Animation Editor is unusable for large spritesheets and being phased out it would be really useful if the new preview window could show the list of frames a chain contains.

Picture of the old app:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/020d3410-5a15-4c18-acc1-0d388dc85fdf)

Probably all information displayed there will be needed to retain the old functionality although, for me, the one property I would really need is "FrameLength".

**Comment by vchelaru** [comment]
Added individual frame viewing for this next version.
![20_08_45_23](https://github.com/vchelaru/FlatRedBall/assets/729631/a416b266-d5ca-446d-9537-5300adb85a13)

More will come, but I'll wait until the specifics are needed as to not spend too much time on something that isn't needed yet.
