### ISSUE TITLE
Added .json files with wildcards to global content, now the project won't build

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1108]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/e4436fcc-e17c-425f-8d58-2cfcba7ee50d)

It's like .json files are being interpreted as part of a dialog tree system, but you can use .json files in a game for lots of purposes, like holding texture atlas data...

**Comment by mfigueirido** [comment]
Solved it in my case by adding "HasPublicProperty": false to the wildcard so no properties are generated. I'm removing the high priority tag.

**Comment by vchelaru** [comment]
I believe this can be solved by setting the wildcard files to have LoadedAtRuntime = false. More info here

https://flatredball.com/documentation/tools/glue-reference/files/glue-reference-files-loadedatruntime/

This property exists specifically for this case.
