### ISSUE TITLE
Gum font scaling is broken

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1110]
This is a shot of how it looked before:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/fcd7fabc-363f-4dc4-b1f2-af1319503efd)

This is how it looks now:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/094694e2-f80e-4577-ad0d-c105a2f84630)

Those texts have font scaling enabled and it's no longer working:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/f67c4c8f-a54f-43d2-9b87-1f24c1190801)

I have pinpointed the offending commit, it's this one:
[8720c8b9cad5fa6e513b26685407c6ecec4026a6](https://github.com/vchelaru/Gum/commit/8720c8b9cad5fa6e513b26685407c6ecec4026a6)

**Comment by vchelaru** [comment]
Sorry for this, silly mistake on my part. Fixed on commit 879e2413cea8374c01ac8b3c3b3564de7e9f2a14 in Gum.
