### ISSUE TITLE
Gum should recursively place children in the correct container

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1117]
**Repro:**

1. Create a list box and make sure you have the InnerPanelInstance set as the default child container
2. Put the list box into CustomComponentA and set it as the default child container
3. Create an instance of CustomComponentA and put an item inside of it

**Expected behavior:**
The default container for CustomComponentA should be the ListBox's default container, which should in turn be the InnerPanelInstance of the list box. If properly placed, the child components should neatly stack in the InnerPanelInstance

**Actual behavior:**
The item placed in CustomComponentA does not render or stack properly. It is not being placed in the proper container.

This can be quickly viewed in the Kid Defense project main branch, the EndgameDemo component:

![image](https://github.com/vchelaru/FlatRedBall/assets/711100/c0e723de-bb00-49c1-aea5-66160122f9ea)

**Comment by vchelaru** [comment]
Fixed, Gum commit b052985d36a3799b24535cc6b8b0c7b01254baf8
