### ISSUE TITLE
Glue error message about missing SourceObject 

### ISSUE THREAD

**Issue by dantogno** [vchelaru/FlatRedBall#1132]
**Repro steps:**
1. Get latest glue / gum
2. get latest fish story on NewFrb branch https://github.com/dantogno/FishStory/tree/NewFrb
3. Build & run glue
4. Open game sln in glue

**Results:**
(see screenshot)
I'm not sure what this means but you mentioned creating a card here 😅

![image](https://github.com/vchelaru/FlatRedBall/assets/3150710/9598b011-40f8-4a5d-84b3-d97cdae9a243)

**Comment by vchelaru** [comment]
This is in fact not a bug, it is reporting a missing object source accurately.
