### ISSUE TITLE
Add description, topics information into  `About` of the repository

### ISSUE THREAD

**Issue by MauNguyenVan** [vchelaru/FlatRedBall#1144]
I have seen your repository. It is exactly what I am looking for. It is a great project.
You should fill in more descriptions, keys of technology, and topic information in the repository.
This makes other people like me easily find out good resources when searching on Git Hub.
Please do that for other projects to share with more people.

Special thanks for your contribution.

- For https://github.com/vchelaru/FlatRedBall

![image](https://github.com/vchelaru/FlatRedBall/assets/48544354/18d4bdd4-4a02-4040-a383-4e78081bc522)

- For https://github.com/vchelaru/Gum

![image](https://github.com/vchelaru/FlatRedBall/assets/48544354/b5ddf2de-9bfb-470a-bcc9-a69d69c5e42d)

**Comment by vchelaru** [comment]
Thanks for the suggestion! I've updated both repositories with information.
