### ISSUE TITLE
Adding Derived Entity to Base List in Screen Crashes Edit Mode

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1158]
![image](https://github.com/vchelaru/FlatRedBall/assets/6179393/9694f20a-bfe6-4680-b167-8a367102ac18)
![image](https://github.com/vchelaru/FlatRedBall/assets/6179393/b6852274-fbdf-44ae-bef4-85ec54a7d45a)
Either launch directly into edit mode or launch from VS and switch to edit mode.
stacktrace: https://hastebin.com/share/agavegicol.css
CustomVariables is null here: `var pointsTunneled = element?.CustomVariables.FirstOrDefault(varItem => varItem.SourceObjectProperty == "Points");`

**Comment by vchelaru** [comment]
I could not reproduce. Can you please provide a project that reproduces it, and provide repro steps?

![17_18 28 47](https://github.com/vchelaru/FlatRedBall/assets/729631/a4118329-c456-49cf-9a9c-cc00e298f162)

**Comment by vchelaru** [comment]
Could not reproduce
