### ISSUE TITLE
Generated collision relationship events sometimes have extra whitespace

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#116]
While working through the [RockBlaster Collision tutorial](https://flatredball.com/documentation/tutorials/rock-blaster/tutorials-rock-blaster-collision/) I generated two list-to-list collision events. When I loaded the generated GameScreen.Event.cs file, the whitespace around the generated code was a little different than expected.

The first generated event had 8 extra leading spaces on the declaration. Both events had an extra trailing space after the declaration but before the curly braces. (The later was only noticeable because I keep whitespace visible in VS.)

![Screenshot of two generated Collision Occurred event code blocks showing the first event has extra leading whitespace and both blocks having an extra trailing space.](https://user-images.githubusercontent.com/713665/119138356-0664cb00-b9ff-11eb-9c64-de07fb8c581d.png)

**Comment by vchelaru** [comment]
fixed.
3c470b64147263ccf11c51753e6f959f067cf138
