### ISSUE TITLE
Generic reset properties are not properly emitted into generated code files

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#120]
Adding a property with a generic type (e.g. `List<T>`) as a reset property on an object within an entity leads to invalid code being produced in the entity's Generated.cs file, like so:

```csharp
static System.Collections.Generic.List`1[T] ObjectPropertyReset;
```

I wonder if generic typed properties should be supported at all as reset properties on objects except perhaps for Nullable<T>. I could see a lot of problems with collections or Lazy<T> properties being supposedly reset but potentially bringing along unexpected state with them, for example.

**Comment by vchelaru** [comment]
@coldacid I'm sorry but I could not reproduce this error. Can you provide step-by-step instructions or a sample project?

**Comment by charabaruk** [comment]
It's easily reproducible by making Points on an instance of Polygon a reset property. That's how I found it, while doing a bit of experimenting for a different issue in my project.

**Comment by vchelaru** [comment]
In the case of polygons, we may actually want to reset points on it. The core problem comes from the generation of types, specifically that IList<T> is generated as IList`1

This StackOverflow post talks about it. I need to research it to see if I can just create a common solution to get type names in a C# friendly way:

https://stackoverflow.com/questions/2448800/given-a-type-instance-how-to-get-generic-type-name-in-c

**Comment by vchelaru** [comment]
Fixed.
5d0414a02855f43025b679560a91b84b8481204e
