### ISSUE TITLE
Broken/weird WPF windows after conversion from winforms.

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1207]
All windows that have been converted need full testing. Please verify on your own machine that these are behaving properly. I will list some issues here, but do not fix only these problems because I may not have caught everything.

* Critical - event dropdowns not populated
![image](https://github.com/vchelaru/FlatRedBall/assets/729631/ba690900-26da-43fd-9685-662f279b72fb)

* ListBox seems to be used allowing user to select items in the list box. This is weird behavior. Please use the Stack layout control.
![23_07 06 15](https://github.com/vchelaru/FlatRedBall/assets/729631/f543f75a-9689-428c-9c0b-a60a510059aa)
![23_07 04 34](https://github.com/vchelaru/FlatRedBall/assets/729631/871cd25d-c038-4c02-9b7c-01111fe365d0)
* Add Event Window buttons are cut off
![image](https://github.com/vchelaru/FlatRedBall/assets/729631/75be558b-9349-49d4-8096-ea5f6caa0f9f)
* Add Event Window combo boxes are cut off
![image](https://github.com/vchelaru/FlatRedBall/assets/729631/db0774bc-807a-4e72-bfda-6905732c740a)
* Keep the layout consistent with the old view as to separate the top radio buttons from the bottom options
* Use spacing and grouping to separate primary properties (object and event vs the rest)
![image](https://github.com/vchelaru/FlatRedBall/assets/729631/fda3e78b-3f51-474e-9585-06317c644dab)
* Initial state does not match the radio button state
![23_07 19 28](https://github.com/vchelaru/FlatRedBall/assets/729631/d5ef1532-ff6b-4dc1-a758-90886f59b9d1)

**Comment by Lucasharskamp** [comment]
I've made some fixes, unclear for me if the ''event window'' now works as intended because of its many options.
