### ISSUE TITLE
Replace old looking branding from Glue

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1215]
The app would look so much better with FRB's icon instead of Glue's which is a little dated-looking. Plus the app's name in title bar could be called FlatRedBall Editor (or FRB Editor if the former is too long) to reflect its new name.

Other icons could use some work... but an artist is needed for that and they are functional, so it's fine.

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/ec1e03d6-677b-44ac-afcc-d141e5816c2d)

**Comment by vchelaru** [comment]
Icons can be found here:

https://github.com/vchelaru/FlatRedBall/tree/NetStandard/Content
