### ISSUE TITLE
MapDrawableBatch.cs has mixed line endings again

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#122]
Despite no textual content changes, after running latest Glue (from repository) a number of diffs have appeared in the file. Looks to be some line endings no longer matching.

**Comment by vchelaru** [comment]
I'm not sure what is causing this. The file is using CRLF:

https://github.com/vchelaru/FlatRedBall/blob/NetStandard/Engines/FlatRedBallAddOns/FlatRedBall.TileGraphics/FlatRedBall.TileGraphics/MapDrawableBatch.cs

I created a project and it wasn't mixed (I can't repro it). 

If you can get more specific repro steps, or if you can figure out why this might be happening, we can reopen the issue. However, I don't know what else to look for.
