### ISSUE TITLE
Newly created windows sometimes step outside the monitor

### ISSUE THREAD

**Issue by Lucasharskamp** [vchelaru/FlatRedBall#1220]
**Problem**

If one opens a window (because of, say, the ''create entities/screens'' etc wizards) the window is spawned at the location of the user's cursor (based on the left-top position of the window). The problem with that is, if the user is holding the cursor to the right or bottom of their monitor, the newly created screen will be spawned partially outside the monitor.

**Solution**

If the left, right, top or bottom coordinates of the new window are outside the monitor's boundaries. they should moved to fit inside the monitor to the nearest possible spot based on the user's cursor location. (with preferably some margin of error so it isn't placed right next to the edge of the monitor)

![image](https://github.com/vchelaru/FlatRedBall/assets/50183941/c432f75d-fea1-4027-9d10-54cf087f3701)

**Comment by vchelaru** [comment]
I believe this was caused by a bug where the new window position was not considering the desktop scale value. This has been fixed.
