### ISSUE TITLE
RefreshLayoutInternal not found

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1223]
After updating the source a compilation error appeared. This is a new method recently included in generated files but my base screen isn't generating that method.

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/e86c3271-356c-4876-a375-d412a7b134a6)

**Comment by vchelaru** [comment]
Fixed, verified by @mfigueirido 

966b27d7d16a74124bcd176a578a037149c449e6
