### ISSUE TITLE
Remove gap showing in bottom portion of the tree view

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1224]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/6e22ad6f-3a27-4b19-ad00-fe356b15818a)

**Comment by vchelaru** [comment]
Fixed

![28_05 42 18](https://github.com/vchelaru/FlatRedBall/assets/729631/266f1e59-9ce2-4df2-a5e2-348507bd0f95)
0ba5b7a94d6c9c4dcc35840e0bf57b6e96f5fd34
