### ISSUE TITLE
Projects that no longer exist cause startup error

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1228]
In this case "RenderTest1" no longer exists on the disk and this causes the startup error, I guess because FRB is looking for the project icons. These unaccesible projects do not show up on the recent list and they can't be removed from the UI either.

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/d2ada9a5-5689-47ab-8741-e38aea83b612)

**Comment by vchelaru** [comment]
Fixed 5b5a7610f179c58643635885a6ccb6b905418a0b
