### ISSUE TITLE
Glue should create inherited objects

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#123]
Glue fails to create objects that should be inherited from the base class _when you do it from the new object dialog_. Steps:

1. Have a base class with "set by derived" objects
2. Right click and create a new object
3. In the create-object dialog, choose the base entity from the dropdown
4. Complete creating the object
5. The object should have derived object from the base class but it does not

Gif:
![inheritance-demo](https://user-images.githubusercontent.com/711100/119897768-28c67f00-befe-11eb-8b17-4a1238ac44cf.gif)

**Comment by profexorgeek** [comment]
Note that changing the BaseEntity dropdown to None and back properly adds the expected objects.

**Comment by vchelaru** [comment]
Fixed.

![2021_May_27_194813](https://user-images.githubusercontent.com/729631/119915442-c7170c80-bf1f-11eb-8b49-deb4ddff42b9.gif)

bafba5197b1b464690ba9a4aa4dfbcbe6870c28e
