### ISSUE TITLE
[Gum] Sub-components exposed variables don't work

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/FlatRedBall#1234]
1. Create a component `BaseComp`
2. Add a `Text` object, expose its `Text` property as a variable `LabelText`
3. Create a component `ChildComp`, make it extend `BaseComp`
4. Create a screen and add a `ChildComp` instance
5. Modify the exposed `LabelText` variable

The variable will do nothing and the text won't change. I've also tried with the `Visible` property of some sub-components and the behavior is the same, so I'm assuming this is a generalized problem.

**Comment by vchelaru** [comment]
Thank you for the repro steps. I confirmed the bug and I'll be working on it.

**Comment by vchelaru** [comment]
Fixed in Gum commit 556ca364382812e899c11621aff18432bff8e141
