### ISSUE TITLE
[Gum] Cannot modify line spacing for Text

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/FlatRedBall#1235]
There doesn't seem to be a way to modify the line spacing (distance between line baselines) of a `Text` component. This could be specified in a different number of ways, like 1x, 1.5x, 2x (for a scale over the default) or positive/negative number to add or subtract pixels over the default, or an absolute number to specify the exact line spacing in `px` or `pt`, among probably other valid options.

**Comment by vchelaru** [comment]
Fixed with Gum commit 51ed98ecc19dee308738d735f104eb2b18b67d99

![08_06 43 25](https://github.com/vchelaru/FlatRedBall/assets/729631/d4d34175-00f0-4d4d-bd8b-c4d97657b133)
