### ISSUE TITLE
[Gum] Canvas scrolling with color picker open makes properties scroll

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/FlatRedBall#1238]
While working on https://github.com/vchelaru/Gum/pull/93 I realized this is happening. If you open the color picker, then proceed to zoom on the canvas view, the whole properties panel will scroll as well (it also happens with the new picker I added, so maybe it's unrelated to the picker control itself?). I've tried with other controls that open popups (like a combobox) and this doesn't seem to happen.

Also, if you open the color picker and scroll the properties panel on purpose this also happens, so I'm guessing some kind of lock is missing (that context and combo boxes popup already possess).

**Comment by vchelaru** [comment]
Fixed on Gum commit 89de2cc0c98216521f27be3842db730122e5edc7
