### ISSUE TITLE
[Gum] Default values have disappeared

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/FlatRedBall#1242]
Commit [6b6bad9a140291c5573f12e340840c5b32b02616 ](https://github.com/vchelaru/Gum/commit/6b6bad9a140291c5573f12e340840c5b32b02616) made default values disappear.

<img width="379" alt="Gum_tq0YLYtoNw" src="https://github.com/vchelaru/FlatRedBall/assets/28616/b84a3ab0-1dd0-43a1-b6b2-ef718f5e6577">

**Comment by vchelaru** [comment]
Oops bad fix on my part sorry about that. Fixed now:

https://github.com/vchelaru/Gum/commit/f50feb0079cfbeebe6637ed0524643a8a1023b28
