### ISSUE TITLE
[Docs] [Beefball] Mismatching icons in Beefball and other outdated screenshots

### ISSUE THREAD

**Issue by ClementineAccount** [vchelaru/FlatRedBall#1247]
(This issue should be moved once the doc repo is created)

This is a relatively minor issue but would still like to document it:

The image in [Beefball's Tutorial](https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-creating-an-entity/) is outdated compared to the image in modern FRB. Its not big deal, but I was confused not being able to find the gingerbread man.

Example 1:
![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/9c770769-3752-4244-9dde-0710e0689a93)
![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/9542ce17-c28d-4e62-8f1f-ad556e521edb)

Example 2:
![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/a94e361b-afc0-466e-af57-e92350bccdfc)
![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/acd64b73-62d0-4b9c-b9d2-4c589d5ce5ac)
[03. Creating the Screen](https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-creating-a-screen/)

Example 3:
Outdated wizard in [04. Controlling an Entity](https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-controlling-an-entity/)
![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/bd2612ec-a7ab-4309-b496-16c6cc4de123)
![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/6c365e4c-4177-417b-88ba-491ff65a4197)

**Comment by ClementineAccount** [comment]
Actually a lot of the icons are outdated now that I went through more of it: 

![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/a94e361b-afc0-466e-af57-e92350bccdfc)
![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/acd64b73-62d0-4b9c-b9d2-4c589d5ce5ac)


I think this is still low priority though as the text is the same.

**Comment by vchelaru** [comment]
Fixed on new docs site.
