### ISSUE TITLE
[Docs] Connection Security Warning

### ISSUE THREAD

**Issue by ClementineAccount** [vchelaru/FlatRedBall#1254]
I got this warning on this page: https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-adding-multiple-players/ and a few others.

![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/f205c904-67fc-4d0c-b721-0a296766bb90)

**Comment by treesgobark** [comment]
Works for me. Maybe just a fluke? Do you know any other pages it still happens on?

**Comment by vchelaru** [comment]
This will be fixed through the new docs page:

https://docs.flatredball.com/flatredball/tutorials/beefball/adding-multiple-players
