### ISSUE TITLE
[Docs] Documentation and Tutorials still refer to '-List' suffix

### ISSUE THREAD

**Issue by ClementineAccount** [vchelaru/FlatRedBall#1255]
This is usually easy to ignore except for the code example in [09. Scoring and Restarting Rounds
](https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-scoring-and-restarting-rounds/)

![image](https://github.com/vchelaru/FlatRedBall/assets/26779639/1600859c-f333-4cbc-a4f1-a798579f9034)

The user will have to take note of the difference in names to follow along with the tutorial.

**Comment by treesgobark** [comment]
I changed the names but not the gifs due to how long that would take. If that's good enough then I guess we can close this but I'll just leave it open for now

**Comment by vchelaru** [comment]
https://docs.flatredball.com/flatredball/tutorials/beefball/creating-the-screen-collision
