### ISSUE TITLE
Fix project items duplicates check on different types

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1263]
The load screen shows this error if the user adds two .dll references to the project being different types.
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/2a61227c-9a4d-4de5-817c-5048f5af1b5c)
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/df06ca8a-abcd-4966-94a9-63e1eef0b0ce)

It should only happen when they are the same type.

**Comment by vchelaru** [comment]
Fixed 71189db594ba094e2279790ef56a5b7d916590e8
