### ISSUE TITLE
[Glue] Left panel does not go away after resizing

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#127]
## Steps to Reproduce:

1. Open the "Camera Settings" tab
2. Resize the pane in which the "Camera Settings" tab appears
3. Close the "Camera Settings" tab via the X button on the tab

## Expected behaviour:

The pane which contained the "Camera Settings" tab will become collasped/closed.

## Actual behaviour:

The pane which contained the "Camera Settings" tab will remain open and cannot be resized, while the "Camera Settings" tab itself will be closed and removed from the window.

## Additional notes:

This happens with any tab that is opened in the left pane, such as the "Plugins" tab. It is not exclusive to the "Camera Settings" tab.

**Comment by vchelaru** [comment]
Fixed dfd8a61140b940d08baff82ae423f3e4fa29cd8a
