### ISSUE TITLE
Glue should build content with the correct binary

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#128]
Glue is trying to build content with a MonoGame executable named `MGCB_GLAFOO.exe` but should be using `MGCB.exe`. It's odd that it just started trying to use a different file. This started happening when I did a refresh of FRB and pulled down some 60 commits so I'm not sure the exact point it started happening.

Renaming the executable works as a workaround so it seems like the executable name just got corrupted.

![image](https://user-images.githubusercontent.com/711100/120217161-31b49a80-c1f5-11eb-96cc-e51be7d5f64e.png)

**Comment by vchelaru** [comment]
Oops this was debug code! I should not have checked that in.

Fixed 

3076033dbe31f4403b076fb822656414ed35ddc6
