### ISSUE TITLE
Gamepad.GetButton and Keyboard.GetKey should cache returned objects

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#129]
Both the `Xbox360GamePad` implementation and the `Keyboard` implementation have methods to `GetButton`/`GetKey` that might be used like this:

`IPressableInput LightAttackButton => gamepadInstance.GetButton(Xbox360GamePad.Button.A);`

If a developer does this, it will create a new `Xbox360ButtonReference` every frame, for every button, for every controller. The same applies to keyboard. This would create significant memory pressure since those objects would be immediately dereferenced after single use.

Instead, FRB should intelligently cache the objects created so developers stumble into success when creating their own input implementations.

**Comment by vchelaru** [comment]
ca0061cfebb38e8275303d3b636c79a99aa46fb4
