### ISSUE TITLE
Gum ACHX animations do not play after updating source

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1293]
It was working fine but it no longer plays:

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/74a0e984-8f02-40e7-a430-dbe7693c4e35)

I can provide a test project.

**Comment by vchelaru** [comment]
Fixed in Gum commit

db17a7b62c8e79ab9e1dff3934413bf5d35fe3d7
