### ISSUE TITLE
Update libraries crash

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1294]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/443b5ee4-0e34-4400-9f60-9cbef8255b98)

Steps to reproduce:

1. Clone this repository: https://github.com/mfigueirido/SkiaMonoGameRendering.git
2. Open the project SkiaTest with FRB Editor.
3. Press on "Update/Update Libraries".

**Comment by mfigueirido** [comment]
It looks like it's still crashing at the end:

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/b99994e6-6002-4ff3-bc62-d492f17598dd)

**Comment by vchelaru** [comment]
The 2nd fix has been verified by @mfigueirido
