### ISSUE TITLE
TileAdventure Glue Project Doesn't Build

### ISSUE THREAD

**Issue by nightblade9** [vchelaru/FlatRedBall#13]
Hi,

I just downloaded/installed FRB and all the pre-requisites using the latest installer (available today). When I create a new TileAdventure project and build it, I see these errors:

```
Entities\DialogDisplay.Generated.cs(30,17): error CS0246: The type or namespace name 'LayeredTileMap' could not be found (are you missing a using directive or an assembly reference?) [D:\temp\TileAdventurez\TileAdventurez\TileAdventurez\TileAdventurez.csproj]
Screens\GameScreen.Generated.cs(26,17): error CS0246: The type or namespace name 'TileShapeCollection' could not be found (are you missing a using directive or an assembly reference?) [D:\temp\TileAdventurez\TileAdventurez\TileAdventurez\TileAdventurez.csproj]
```

This is a stock project, without any changes. (I had to name it `TileAdventurez` because when I named it `TileAdventure`, I get an exception about copying; something like `source and destination names are the same`.

The result is the same whether I build in Glue or VS2015.

**Comment by vchelaru** [comment]
Have you tried installing the Tiled plugin?

http://www.gluevault.com/plug/94-tiled-plugin

Also, if you need immediate help for stuff like this, feel free to come over to our gitter chat:'
https://gitter.im/vchelaru/FlatRedBall

**Comment by nightblade9** [comment]
Ah, so Gitter is the main place to get help. That explains why there are no open issues here, only PRs.  I personally prefer GitHub because there's a paper trail -- eg. in cases like this, someone with the same problem can easily search and find this issue.

Thanks, downloading the plugin solved my problem.  Since FRB ships with this project template, I suggest editing [this wiki page](http://flatredball.com/download/) to mention downloading and installing the Tiled plugin.

The project crashes with a runtime exception in `TileEntityInstantiator.cs`:

```
var factory = factories.FirstOrDefault(item =>
            {
                var type = item.GetType();
                var methodInfo = type.GetMethod("CreateNew", new[] { typeof(Layer) });
                var returntypeString = methodInfo.ReturnType.Name; // crash here, methodInfo is null

                return entityType == returntypeString || entityType.EndsWith("\\" + returntypeString);
            });
```

**Comment by nightblade9** [comment]
I fixed this by replacing this:

```
var methodInfo = type.GetMethod("CreateNew", new[] { typeof(Layer) });
```

With this:

```
var methodInfo = type.GetMethod("CreateNew", new[] { typeof(Layer), typeof(Single), typeof(Single) });
```

Looks like an issue with the generated code.

**Comment by vchelaru** [comment]
I believe this has been fixed with a newer version of the Tiled plugin, so I'm closing this issue. Please let me know if any other issues come up.
