### ISSUE TITLE
Check for existing Visual Studio instance for project before launching a new one

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#132]
If possible, Glue should check to see if there is already an instance of Visual Studio running with the project solution open in it when the VS button is pressed. A new instance of Visual Studio should only be started if there are no current instances of Visual Studio, or when none of the currently running instances have the project opened.

**Comment by vchelaru** [comment]
I believe to do this, would have to use the DTE objects as explained here:

https://docs.microsoft.com/en-us/visualstudio/extensibility/launch-visual-studio-dte?view=vs-2019

I had implemented something like this LONG ago, but the amount of work it takes to implement (given that I am not familiar) relative to the benefit it gives is really high. 

I'm going to close this, but if anyone who knows more about visual studio automation is interested in tackling it, please re-open.
