### ISSUE TITLE
Mouse hover prevents slider from updating whether it's focused

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1327]
- Use the controller controls for an FRB form
- hover over a slider element (im using the built in settings component ones)
- try to focus that element, won't highlight

- focus slider with controller
- hover with mouse
- unfocus with controller
- element won't unfocus

The checkbox and all buttons seem to work properly
here's my project where the bug is happening if you need it, i made a branch for it https://github.com/treesgobark/ShiftRpg/tree/bug/hoverFocusBreak

**Comment by vchelaru** [comment]
This was caused by a bad default forms implementation. This has been fixed, along with a similar bug on CheckBox.
