### ISSUE TITLE
Certain exposed variables from Gum have display issues

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1329]
repro branch: https://github.com/treesgobark/ShiftRpg/tree/bug/gumVariablesInGlue
since the last time i have added my utilities project as a reference so you'll need that too if you're planning on running the game itself which i guess you don't really need to but here it is anyway: https://github.com/treesgobark/ANLG.Utilities.FlatRedBall
This is on the Gun entity's MagazineBar object in the editor:
In glue these values' defaults don't seem to match their defaults in gum
![image](https://github.com/vchelaru/FlatRedBall/assets/6179393/db095bdf-cc31-41e6-89c5-a999afe5ea7a)
in gum they're 255:
![image](https://github.com/vchelaru/FlatRedBall/assets/6179393/74b504d5-4854-4b03-bbef-00670df59ca1)
and the state is null and visible is checked
![image](https://github.com/vchelaru/FlatRedBall/assets/6179393/1f114501-cb5c-4a83-b07f-96fc73f5c341)

**Comment by vchelaru** [comment]
Fixed ce0d9082f8ddf7cc577e6bf8dc7f86f3df94623c
