### ISSUE TITLE
Custom Cursor Texture

### ISSUE THREAD

**Issue by djjohnsongeek** [vchelaru/FlatRedBall#1331]
MonoGame allows you to easily set a custom cursor for your game. This method is far superior to hiding the cursor and drawing a sprite in the cursor's place because you don't have to deal with the horrible lag. It also makes it quite simple to swap the cursor texture at anytime.

According to this forum post it has been a feature in MonoGame since 3.6:
[https://community.monogame.net/t/best-solution-to-draw-custom-mouse-pointer/7233/3]()

A simple usage example might look like this:
``` C#
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Graphics;
using FlatRedBall;

FlatRedBallServices.Game.IsMouseVisible = true;

Texture2D cursorTexture = FlatRedBallServices.Load<Texture2D>("path/to/cursor.png");
int originX = 0;
int originY = 0;

MouseCursor customCursor = MouseCursor.FromTexture2D(cursorTexture, originX, originY);
Mouse.SetCursor(customCursor);

```
That is it! Nothing required in Update() or Draw()

MonoGame Documentation Links
[https://monogame.net/api/Microsoft.Xna.Framework.Input.Mouse/#setcursor-mousecursor](https://monogame.net/api/Microsoft.Xna.Framework.Input.Mouse/#setcursor-mousecursor)
[https://monogame.net/api/Microsoft.Xna.Framework.Input.MouseCursor/#fromtextured-textured-int-int](
https://monogame.net/api/Microsoft.Xna.Framework.Input.MouseCursor/#fromtextured-textured-int-int)

**Comment by vchelaru** [comment]
Documentation has been updated.

https://docs.flatredball.com/flatredball/tutorials/code-tutorials/customizing-cursor-visuals/windows-desktop
