### ISSUE TITLE
Editor crashes after moving a vertex on a polygon inherited from another entity (or maybe any entity? idk)

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1344]
repro branch: https://github.com/treesgobark/ShiftRpg/tree/bug/polygonEditModeCrash
requires linking to the .FNA project in this repo: https://github.com/treesgobark/ANLG.Utilities.FlatRedBall
1. Start live edit mode on DefaultSword
2. Move any vertex on the polygon with the mouse
3. :(

**Comment by treesgobark** [comment]
a different crash happens when you click the live edit canvas while either MeleeWeapon or its PolygonInstance are selected, probably related

**Comment by treesgobark** [comment]
PolygonPointHandles.SendPolygonPointsToGlue gets the current named object save but it's null
CommandReceiver.GetSelectedNamedObjects is receiving a DTO that contains the name "PolygonInstance" but GlueState.Self.CurrentElement has no named objects at this time so an empty list gets passed into EditingManager.Select on line 1146

**Comment by vchelaru** [comment]
I am unable to repro this problem so we'll have to look at it together
![05_06 31 52](https://github.com/vchelaru/FlatRedBall/assets/729631/e9720320-b42a-4076-acb5-19bc55e8ab5e)

**Comment by vchelaru** [comment]
Note that MeleeWeapon is a base abstract class.
