### ISSUE TITLE
ODS sheet cell changes not reflected in engine until a second screen reload occurs

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1345]
repro branch: https://github.com/treesgobark/ShiftRpg/tree/bug/spreadsheetRuntimeUpdate
1. start game
2. enter gameplay screen
3. open AttackData.csv in global content with libreoffice calc
4. change value of any of the hitbox fields and save, screen reloads
5. BUG: expected changes to hitbox. no changes present
6. change any other value in the csv and save, screen reloads
7. BUG: expected both changes to be present, only first is present
8. esc to main menu and go back into the game screen
9. both changes reflected as expected

this appears to be the same behavior that shaders used to exhibit (at least i _think_ it was fixed, i remember complaining about it in the past)

**Comment by vchelaru** [comment]
This is 2 bugs:

1. The ODS shouldn't result in the page restarting. Fixed here: https://github.com/vchelaru/FlatRedBall/issues/1347
2. The CSV is itself reloaded, but the variables from the CSV must not be "copied" for hotreload to work. If they are, then an explicit page reload can be performed.
