### ISSUE TITLE
Consider taking scaling into account when listing resolutions

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1348]
This concept could apply to both the new project wizard and the camera settings in Glue...

![image](https://github.com/vchelaru/FlatRedBall/assets/711100/b6909b22-e0ab-4719-8d6b-0c9dc64684a2)

In the above image, what I probably want as a developer, is to create a game with a specific _viewport_ resolution such as 1920x1080 (1080p). But I also want 200% scaling for that classic pixely look. That means my _game_ resolution is actually 1/2 the viewport resolution.

There's opportunity to make this clearer for users. For example, you could dynamically update the resolution list based on the scaling chosen by the developer. An example line might look like this:

`[x] 16:9 - 1920x1080 (960x540@200%)`

This lets the developer see that their game resolution will be 960x540 but the viewport resolution will be 1920x1080 in terms of screen pixels the game occupies, because of the chosen scaling. Otherwise developers must understand and do this math themselves and it's not super intuitive to guess how it works.

**Comment by vchelaru** [comment]
I added a new label that dynamically adjusts based on the options above.

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/92cad583-3885-4ca7-917b-35f92d9970ea)

**Comment by vchelaru** [comment]
Also added this to the camera settings:

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/db7212ed-750c-4f7a-bb5b-1c31beb4e9b4)
