### ISSUE TITLE
Gum numeric value mouse drag issue

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1349]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/7c1a7517-98aa-4879-aa6d-6b40e88e7e4e)

The issue happens when modifying numerical values by dragging the mouse cursor. The dragging behaviour should stop when you release the mouse button but it does not, it keeps showing the modified cursor and continues changing the value while you move the mouse.

**Comment by vchelaru** [comment]
Fixed in Gum commit

ecc4a656ea2ba920779792fa3691874919e3eedc
