### ISSUE TITLE
Gum's text "Max Letters To Show" crashes app if modified via mouse drag

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1355]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/135036a3-dbcc-4ebd-b9a5-54508ddef6e7)

**Comment by vchelaru** [comment]
Fixed on Gum commit d20d2e8a1f82f00179dfa0f02beca26bd61c44b7
