### ISSUE TITLE
Gum's BBCode style tags not working correctly

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1356]
As can be seen on the next image, all the reamaining text is styled with Arial font when only the word "hatch" should:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/39336658-f4de-4782-a24f-59369ef98f10)

Also if "Max Letters To Show" is filled, parts of the differently styled text still show up when it shouldn't:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/bf0bc5f0-932c-41cd-adca-0619173f256c)

**Comment by vchelaru** [comment]
Lots of progress has been made on this, but there are still some problems related to setting bbcode text at runtime.

**Comment by vchelaru** [comment]
I believe this is ready to be tested

**Comment by mfigueirido** [comment]
No matter how I set the font's tag it's the same. It just refuses to work:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/365712a7-17f3-45ae-8e1d-54b2fe93186e)

"Max Letters To Show" appears to be fixed 👍

**Comment by vchelaru** [comment]
Still need to add support for styling across pages, but the initial card is solved. Lots of bug fixes so ..yay!
