### ISSUE TITLE
Gum does not align to the pixel centered elements

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1374]
I have this sprite element in my Gum project which its X units are set to "pixels from center":
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/0394807c-719b-4f95-945f-01980e4254d3)

Depending on the current resolution this sprite gets distorted because -I suspect- its position isn't falling into an whole number and thus causing the artifact:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/a6a66a4f-a712-45f8-97fb-a2d28e07a78c)

This is how it should look instead:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/51e592ab-226b-4239-94f7-22686c1feccb)

Edit: This seems to happen with any position setting that does not guarantee whole numbers, por example when using "percentage parent" or setting any of the origins to "center". It would be nice to have some setting that enforces whole number rounding of positions (maybe it already exists and I'm not aware of).

**Comment by vchelaru** [comment]
I believe this has been fixed here:

https://github.com/vchelaru/Gum/commit/20cb6d0624f3790bc283e8cb6bacda3c3d55514a

Will close after Miguel verifies.

**Comment by mfigueirido** [comment]
Confirmed as fixed. I'll close this.
