### ISSUE TITLE
Add ability to reorganize bookmarks

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1384]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/52024e86-52e7-4cb5-89bf-1fc87a57060d)

Having the possibility to drag and drop bookmarks around to organize them would be a nice boost.

**Comment by vchelaru** [comment]
You can currently click on an item, hold down ALT, then press up or down arrow.

![01_21 58 23](https://github.com/vchelaru/FlatRedBall/assets/729631/574fda5f-c7e9-4517-95b6-189d1e86f148)

Is this good enough? Or would you need drag+drop.

**Comment by mfigueirido** [comment]
Didn't realize I could do that!
Nevermind then, that's more than enough.
Thanks.
