### ISSUE TITLE
Add "copy file name" menu option for content

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1385]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/94aa5004-4168-4404-9053-a2785e093622)

It would be really cool to have a menu option on content files which allows you to copy the name of a file (not the path, and without the extension). This is helpful to quickly paste the name of a resource on a property in Tiled.

**Comment by mfigueirido** [comment]
Ok, what we got now is this:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/f725a2e5-266d-4d6e-9103-bc1368338cdf)

It copies the full resource name that's used to access the resource in GlobalContent and that could have its uses, but what I would really need is not "Resources_Screens_HouseAttic_Boxes", but only "Boxes" because of how my content loader works.

I understand adding that option could be cluttering the menu with something that may be specific to my game, so I'll leave adding that to your discretion :)

**Comment by vchelaru** [comment]
Sorry this took so long to get to, but I've finally revisited it. I think this will work.

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/447b3692-dad9-4479-be2a-787b52da063b)

aeee4a661e7b27cae1462618bd4d91d5c9d0386b
