### ISSUE TITLE
Make the MapDrawableBatch layers in a LayeredTileMap have a Texture scaling property similar to that of a Sprite

### ISSUE THREAD

**Issue by mza299** [vchelaru/FlatRedBall#1391]
The Sprite class has a TextureScale float property but a MapdrawableBatch does not have one.

**Comment by vchelaru** [comment]
I forgot this already exists. Documentation:

https://docs.flatredball.com/flatredball/tiled-plugin/flatredball-tilegraphics-mapdrawablebatch/renderingscale
