### ISSUE TITLE
No way to uninstall on Windows 10

### ISSUE THREAD

**Issue by paul-gilbertson** [vchelaru/FlatRedBall#14]
FlatRedBall does not register itself as an App that can be uninstalled. Very bad practice.

**Comment by vchelaru** [comment]
Hi Paul,

Thanks for reporting, this is something on my todo list. Been working on lots of bug reports lately impacting the runtime of the engine so I haven't gotten back to any installer/update/uninstall issues.

**Comment by vchelaru** [comment]
We no longer have an installer, but rather a .zip file that is unzipped to the project. Since there is no official install, there is no uninstall - you just delete the files where you unzipped them now.
