### ISSUE TITLE
Lots of consecutive file disk changes cause erratic behaviour

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1408]
We have a packer tool which creates an atlas per screen. Each atlas includes every entity from the game (including .achx) plus that specific screen graphics (one atlas for the whole game would not fit a 8K texture).

When we execute the packing of all the screens in our game, FRB exhibits the next behaviour:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/b4802e7a-9d00-4dbc-a50a-9e2c3af35887)

1. It starts by detecting consecutive file changes and adds a cooldown, but it seems like the cooldown isn't refreshed by newer disk changes so it starts updating files again after two seconds.
2. It looks like files are being copied over to two different build locations... This doesn't seem like a necessity, maybe FRB can be smarter about this?
3. This is a guess, but it looks like the same file is being queued many times, probably because of queuing at file create, and another at file modify. A file should be only queued once.

The processes take several minutes to complete.

**Comment by vchelaru** [comment]
This requires aseprite so I downloaded it.

**Comment by mfigueirido** [comment]
Ok, thank you!

You can grab the app here:
https://drive.google.com/file/d/1BjSxZ7dpWJvpqDEBshPL9nL_h5XrqpM6/view?usp=sharing

After running it you need to check "background content generation" and fill the path fields:
First: location of Aseprite's exe.
Second: location of Deadvivors "Resources" folder which is inside GlobalContent. This folder is used as a source for creating the atlases.
Third: location of Deadvivors "Atlased" folder which is inside GlobalContent. This folder is used to store the created atlases and modified achx.

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/dfce99f3-83bc-4f7d-b1e2-278d14bfa9c0)

After that just hit the "build all screens" button.

**Comment by vchelaru** [comment]
Lots of performance improvements have been added to the ProcessAchx branch. Let's see if this is fast enough now...

**Comment by vchelaru** [comment]
We ran a test and got way better speeds, so closing this issue.
