### ISSUE TITLE
Screen restart on TMX change is broken

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1409]
The screen should reload after changing the TMX of the current running screen, but it doesn't. It looks like it has been broken recently.

This is checked:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/49266ba4-3e1e-4cf9-81f2-e3725599a4d3)

Behaviour shown on this video:
https://github.com/vchelaru/FlatRedBall/assets/24922404/3a911c1d-ec18-47f8-997c-4ebf3e5f7c83

**Comment by vchelaru** [comment]
This has been solved with a hacky workaround as documented here: https://github.com/vchelaru/FlatRedBall/issues/1412
