### ISSUE TITLE
Glue doesn't provide access to SetInDerived objects on entities beyond the first level of inheritance

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#141]
See https://github.com/coldacid/glue-bugs/tree/entity-grandparents-missing-objects for a test project demonstrating the situation.

The `SetByDerivedCircle` object on BaseEntity is expected to be visible and configurable on GrandchildEntity since it should be settable at that level. Variables with Access/SetByDerived set properly appear at each level of inheritance, as do objects with Access/ExposedInDerived set, but objects with Access/SetByDerived set only appear for the immediately derived entity.

![image](https://user-images.githubusercontent.com/130681/122492372-a177a300-cfb3-11eb-9e4b-3c29aff6b7f4.png)

**Comment by vchelaru** [comment]
This is behaving as designed. SetByDerived means - this is not defined in the current inheritance level, but it must be defined in the next inheritance level. If you want the most derived (GrandchildEntity) to be able to define this, then the ChildEntity must also set the object's SetByDerived to True.

I have updated the documentation to explain this subtlety:
https://flatredball.com/documentation/tools/glue-reference/objects/glue-reference-objects-setbyderived/

Thanks for bringing this up. I had forgotten the intended behavior and it definitely wasn't documented anywhere.
