### ISSUE TITLE
Zooming in the Texture Coordinate Selection is broken

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1410]
When trying to select a small texture on a large sprite sheet, you need to zoom in but zooming is broken in the texture coordinate selection window. See gif below:

![texture-zoom-fail](https://github.com/vchelaru/FlatRedBall/assets/711100/9a3fd9b0-b3df-4637-ac1b-69dfecfd1f5c)

**Comment by vchelaru** [comment]
This is fixed on the SpeedImprovements branch. It will get merged in to NetStandard in a few days, most likely.
