### ISSUE TITLE
Cannot select inherited movement types in derived entity in Glue

### ISSUE THREAD

**Issue by charabaruk** [vchelaru/FlatRedBall#142]
When setting variables on a derived entity type, the dropdowns for the movement type variables do not include the movement type values from the base entity type. The only selectable item in the dropdown is "<NULL>".

*Expected behaviour:* If the entity does not have any overridden movement type values, then Glue should let us select from the values provided for the base entity.

*Actual behaviour:* No movement types are selectable. There is only the option "<NULL>" for explicitly setting null on the variable.

*Workaround:* Inherited movement types can still be set in code. That is what we are currently doing for our project.

**Comment by vchelaru** [comment]
For clarification, this is when dealing with a platformer entity, and the variables being set are the variables on the variables on the entire entity for the default air and ground movement types.

**Comment by vchelaru** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/729631/131584516-9e0ed09f-816d-4df0-b8d3-31897ec691a4.png)

4d304c6bb73c411dc2d4e2a88ed39169b68227c8
