### ISSUE TITLE
Default Camera TransformMatrix not working with IDrawableBatch and SpriteBatch Draw

### ISSUE THREAD

**Issue by lozzajp** [vchelaru/FlatRedBall#1420]
As discussed in Discord.

Setup a DrawableBatch class as per docs: https://docs.flatredball.com/flatredball/api/flatredball/graphics/drawablebatch

Implement a simple spritebatch draw:

```
_spriteBatch.Begin(transformMatrix: camera.TransformationMatrix);
_spriteBatch.Draw(myTexture, new Rectangle(0, 0, 320, 320), Color.White);
_spriteBatch.End();
```

Cannot find texture drawn, likely due to the stray(?) `40` in the matrix.

Identity matrix, or no matrix input to Begin, will draw a texture as normal.

**Comment by lozzajp** [comment]
If I create a new matrix from what I think should be coming from the camera matrix, things seem to work nicely:

```cs
            Matrix matrix = Matrix.Identity;
            matrix *= Matrix.CreateTranslation(camera.OrthogonalWidth / 2.0f, camera.OrthogonalHeight / 2, 0);
            matrix *= Matrix.CreateTranslation(-camera.X, -camera.Y, 0);
            var scale = camera.DestinationRectangle.Height / camera.OrthogonalHeight;
            matrix *= Matrix.CreateScale(scale, scale, 1);
```

**Comment by vchelaru** [comment]
Camera.TransformationMatrix cannot be used "raw" in SpriteBatch.
