### ISSUE TITLE
Pathfinding only works if the entity is outside the graph

### ISSUE THREAD

**Issue by NicusorN5** [vchelaru/FlatRedBall#1421]
While attempting to follow [this tutorial](https://docs.flatredball.com/flatredball/tutorials/top-down-entity/enemy-movement/enemy-pathfinding), the enemy NPC doesn't move unless it is spawned outside the node network. I'm not sure if I'm missing something, or if this is indeed a bug within FRB.

Video: https://www.youtube.com/watch?v=OzJ_TsTOuAY (click the image)
[![https://www.youtube.com/watch?v=OzJ_TsTOuAY](https://img.youtube.com/vi/OzJ_TsTOuAY/0.jpg)](https://www.youtube.com/watch?v=OzJ_TsTOuAY)

Repository: https://github.com/Yirade/USV-game/tree/monogame

**Comment by NicusorN5** [comment]
I have uploaded a separate copy of the map here: [LvlC0.zip](https://github.com/user-attachments/files/15746544/LvlC0.zip)

**Comment by vchelaru** [comment]
Fixed in the next release of FRB, but in the meantime as a workaround add this to your Guard's CustomInitialize

```cs
 topDownAiInput.RemoveTargetOnReaching = true;
```

**Comment by NicusorN5** [comment]
Okay, thanks!
