### ISSUE TITLE
AnimationEditor should remember scroll position when refreshing tree view

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#145]
Repro:

1. Have animation chain list with lots of animations
2. Delete or reorder an animation in the list
3. The AnimationEditor will refresh the list, losing your scroll position

This becomes annoying at scale when you're trying to sort, move, or duplicate a lot of chains.

![anim-list-scrolling](https://user-images.githubusercontent.com/711100/126041390-c48784db-dc0b-41f5-8d80-cda82b0a31d3.gif)

**Comment by vchelaru** [comment]
Fixed
