### ISSUE TITLE
Glue SourceClassType should be alphabetized

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#146]
I think the current order of SourceClass type is based on folder structure but it doesn't show the folder structure. So the list appears to be in arbitrary order. This makes it hard to find things as your project grows and the list does not allow you to search.

Expected Behavior:

1. I can quickly scroll to the custom SourceClass I want
2. FRB base SourceClasses are separated from my project SourceClasses
3. My project SourceClasses are alphabetized regardless of folder structure

Actual Behavior:

1. No obvious sort exists... it appears to be random (though I know it's not)

![image](https://user-images.githubusercontent.com/711100/126043552-cf0d7a49-e1d2-48e0-84a2-9692037e4f34.png)

**Comment by vchelaru** [comment]
Fixed.
633406c72ab56a3381c3c4e2089a3a7ce8494dd0
