### ISSUE TITLE
Spine Instances should render with the correct sorting when interleaving with normal FlatRedBall entities

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1460]
Note that my project could be misconfigured but I think this is an interleaving problem with different types of drawable batch.

I have entities set up such that their visual baseline is at 0,0 and their Z value is 0:
![image](https://github.com/user-attachments/assets/6bf8411e-f946-4d57-adfc-ec2587160484)

I have this call in the `CustomInitialize` method of my base `GameScreen`:
```csharp
SpriteManager.OrderedSortType = FlatRedBall.Graphics.SortType.ZSecondaryParentY;
```

But in the game, the player character (which is a Spine instance and Spine instances don't even support setting a Z value) renders over the top of the house:
![image](https://github.com/user-attachments/assets/6eb8989f-ae07-4acc-a8cd-5f1f23374cda)

The expected behavior is that entities on the screen with a lower Y value (the house) sort with a higher Z value and appear above items that are higher on the screen.

**Comment by vchelaru** [comment]
This has been fixed with the latest versions of FRB and FlatRedBall.Spine
