### ISSUE TITLE
Entities should sort predictably both inside and outside of their parent

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1461]
I have a complex use case where I have house entities that are composed of a base house sprite and decorative sprites for things like windows and doors. Here is a house entity:

![image](https://github.com/user-attachments/assets/85152814-d8c6-4043-a4d8-77d093051149)

Note that the order of sprites in the entity has the Footprint (collision shape), shadow, house, then windows and doors. The expected behavior is that the decorative window and door sprites sort _above_ the base house sprite because they are later in the list. I cannot give them a Z value because the game uses "Secondary Sort on Parent Y" which means they will sort above other game content if they are not at Z zero. So, the only way I can control their rendering order is through the Object list order.

In the entity, this is appearing correctly. However, in the game the windows and doors are sorted below the house. If I give them a Z value, they will appear above the player when the player walks in front of the house:

![image](https://github.com/user-attachments/assets/2f519ae5-dcdb-43d2-8c89-251c2bcbe923)

Ultimately, entities need to have three layers of sorting logic in a top-down game like this:

1. The entity and it's children should be sorted based on their Z value
2. Sprites should have a secondary sort based on their Y value if they have the same Z value
3. Within an entity (and in any list?) the final sort should be based on list add order: items late in the list should be rendered late and thus be on top

**Comment by vchelaru** [comment]
Fixed by d1d54d9c378a1354496f101bb9a79b4846d1eb78
