### ISSUE TITLE
Polygon editing in Glue should have more helpful features

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1474]
Polygon manipulation in Live Edit mode can be finicky. Here are some recommended features to improve this experience in priority order:

- [x] "Auto-close shape" button that links the first and last polygon nodes
- [x] `[mod key]` + click to add point on line
- [x] Selecting a node in the list or in the editor results in both the list and the editor node being highlighted
- [x] ~Snap to [increment] should be enabled for polygons to make it easier to align polygons with tiles~
- [x] "Render name" checkbox should render the polygon's name in the live editor (helpful for map zones!)
- [x] "Render collision circle" should render the polygon's calculated collision circle
- [x] ~Recalculate circle button should recalculate the polygon circle (unless this happens automatically when adding/moving~ points)
- [x] ~Quick shapes buttons for 3, 4, 5, 6, and 8 sided polygons~

**Comment by vchelaru** [comment]
* Render name can be implemented using EditorVisuals.Text: https://docs.flatredball.com/flatredball/api/gluecontrol/editorvisuals/text
* Render collision circle can be implemented using EditorVisuals.Circle: https://docs.flatredball.com/flatredball/api/gluecontrol/editorvisuals/circle

**Comment by profexorgeek** [comment]
I crossed out three of the items for these reasons:

- Snapping works for points already but you set it in the editor overall panel, not in the polygon panel. This makes sense but was not obvious.
- Recalculating the polygon circle does happen automatically and the preview shows while you drag a point. If you want it to always show you can do that with custom editor activity code in your screen
- There was already an N-shaped polygon button, I just missed it 🤦‍♂️

**Comment by vchelaru** [comment]
Just pushed some changes for two-way communication between game<->FRB Editor on selected point index.

**Comment by vchelaru** [comment]
All features above have been addressed.

You can see demos (gifs) of all of the features here: https://docs.flatredball.com/flatredball/glue-reference/enable-live-edit#editing-polygons

The latest commit adds the final features. I'm happy to continue refining the polygon editing behavior, but I think this is a solid start. The latest commit that fixes this is e6f59c56f08a449a648fac71abeac1e3faebba51
