### ISSUE TITLE
Glue should not crash when nuget packages are updated

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#148]
1. Have Glue running
2. Update NuGet packages (Parme for instance)
3. Glue attempts to overwrite csproj
4. When dialog pops up in VS, choose "Overwrite" to preserve NuGet changes
5. Glue crashes

Glue should not try to overwrite NuGet changes and should not crash.

**Comment by vchelaru** [comment]
I believe this has been fixed with a previous commit which now waits for all tasks to finish before reloading the csproj.
