### ISSUE TITLE
Panels no longer carry over the previous session width/height

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1482]
Before closing the app:
![imaxe](https://github.com/user-attachments/assets/ddbca269-3906-4bff-b23b-2bc6339cbd9a)

Opening again:
![imaxe](https://github.com/user-attachments/assets/c5f5f717-4313-4fee-abf5-d7c6f6fbf7d0)

It should remember the size of the panels but it doesn't.

**Comment by vicdotexe** [comment]
After building and running from the [August Release commit](https://github.com/vchelaru/FlatRedBall/commit/799971ca7a739d566c62a4822330d557cd1266ce) (where I initially branched off), I'm finding that _only_ the left-panel's width persists between app launches... Unless there are some reproduction steps I'm missing, I will plan on fixing the broken behavior for the left-panel.

**Comment by mfigueirido** [comment]
Yes, I didn't remember exactly if all of them were saved or only the left one. Saving only the left panel works for me.
