### ISSUE TITLE
Glue should set the Gum project resolution when scaling is applied

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1485]
Glue normally sets the Gum project resolution when you change display settings. That way when you open Gum, the layout size you see is consistent with the resolution of your game.

However, if you set a custom scaling resolution for Gum, this value is not applied to the Gum project even though Glue knows how to calculate it.

Example Glue settings, note that it is telling me the correct game and UI resolution scaling:
![image](https://github.com/user-attachments/assets/967775b6-a067-43b5-981e-1ea4941f990f)

This is what happens in game, this is expected behavior (no problems here)
![image](https://github.com/user-attachments/assets/dace068f-e5d4-412d-b35e-42df3a6fdb4a)

However, in Gum the resolution is set to match the game resolution without the Gum scaling applied. This results in a resolution that is too low and doesn't accurately represent the scaling as seen in the game:
![image](https://github.com/user-attachments/assets/0872547d-1ab2-4d35-af49-1998a5e734dc)

**Expected behavior**: Glue sets Gum project properties so that the layout resolution in Gum matches the practical UI resolution in game.
**Actual behavior**: Gum resolution is wrong when scaling values < 100% are applied in Glue

**Comment by vchelaru** [comment]
Fixed by 9f2a2f0cbc5ca12a389355b18a01d80909de46ef
