### ISSUE TITLE
Dragging to change variable can result in very jerky value changes

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1499]
This can be seen by changing the scale of a sprite in edit mode, but also if you just pay attention to values when they dragging is happening.

**Comment by vicdotexe** [comment]
@vchelaru 
This is for the `Variables` tab right? When clicking/dragging over a variable's label? Regardless, I think there's something going severely wrong in the depths of the wpfdataui stuff, every time a single value is changed, every single control in there is re-created. I think this is actually what's causing the problem.

Set a breakpoint inside `CreateInternalUserControl()` (line 96 in `SingleDataUiContainer.xaml.cs`) and just change the value of a single variable (from 0 to 1 and press enter, or simple combobox selection change) and watch how many times that gets hit.

**Comment by vchelaru** [comment]
Thanks to the comment above I was able to find the problem quickly. It's been fixed.
