### ISSUE TITLE
Glue should not fail to create folders

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#150]
On the Editor branch, Glue is failing to create subfolders for entities. See gif for repro.

![folder-fail](https://user-images.githubusercontent.com/711100/128096961-5639a55f-6b7d-4ca2-b357-a07eec0dcf57.gif)

**Comment by vchelaru** [comment]
![2021_August_03_175522](https://user-images.githubusercontent.com/729631/128098588-ce37d362-382a-4ec0-b92a-17cd51216775.gif)
