### ISSUE TITLE
Adding new polygon points should consider the selected node

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1507]
When adding a new polygon point, it should add the point just after the node you have selected, not at the end of the list. You could also consider adding the new point halfway between the selected node and the next node if the selected node is in the middle of the list.

**Comment by profexorgeek** [comment]
Here's a video showing why this scenario is useful. In the video, I want to change the shape of the polygon but I have to:

1. Add a node
2. Move the node index
3. Change the node position
4. Repeat

For large polygons this becomes very arduous.

![polygon-node-scenario](https://github.com/user-attachments/assets/44d75a59-4d98-4d74-b6dd-8516a8c3bb80)

**Comment by vchelaru** [comment]
The new logic does the following:

1. It adds a new point after the current point
2. The new point is positioned in the middle of the segment following the new point

If no point is selected, then a point is added between index [0] and [1], also in the center of the segment.
