### ISSUE TITLE
Trying to change polygon shape in states should not result in bad generated code

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1508]
I have a bookshelf object that needs to have Up, Down, Left, and Right states. Its footprint changes slightly for these states so I thought I'd try exposing the polygon points as a variable that can be edited in the state.

This doesn't work, and that's okay, but it shouldn't leave my project unbuildable due to not generating the right namespace:

![image](https://github.com/user-attachments/assets/9a59b648-5085-4ca6-8d93-444baf4947f5)

Marking as "Blocking" because this prevents a project (mine in this case!) from building.

**Comment by vchelaru** [comment]
A popup should appear when pressing the << button on the Points variable because this is something that is not currently supported in states. The FRB Editor should let you know so you aren't wondering what to do.

**Comment by profexorgeek** [comment]
Update, removing the variable gets it building again. For anyone who might find this, changing polygon points in a state is not a supported scenario as of this comment!

**Comment by vchelaru** [comment]
For now, FRB prevents including any variable of list types since they will not be editable in state data, and they will generate code incorrectly.

![image](https://github.com/user-attachments/assets/03437133-aed0-4c33-a212-71fa2be96bb3)
