### ISSUE TITLE
Right-click option for view in explorer should use one of the folder icons

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1523]
Not sure which to use, but probably one of these?

![image](https://github.com/user-attachments/assets/34c2a0a5-f3df-48a1-b385-b5ad7b355d76)

**Comment by vicdotexe** [comment]
> Not sure which to use, but probably one of these?

@vchelaru 
I'll probably go with the colored one since it's stemming from the tree view that uses them, and these are all implemented in code-behind with expectations of an image as a parameter.
