### ISSUE TITLE
Create/Update contributing docs to talk about PR acceptance criteria

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1532]
Right now we do not have a document that talks about PR acceptance, specifically what kind of tests need to be done.

Create a document, link it from the github contributing MD which also probably needs to be revisited.

**Comment by Lucasharskamp** [comment]
Creating UnitTests would be good where specific features are being tested, both of the engine, the runtime as well as background tasks.

**Comment by vchelaru** [comment]
I have made the following changes:

* The FlatRedBall auto test project is now up and running. I've removed a few parts of the auto test for features that we no longer support. More info here: https://docs.flatredball.com/flatredball/contributing/automated-test-project
* I have added a section discussing PRs and feature work including guidelines for what kind of PRs will be accepted and how to test them: https://docs.flatredball.com/flatredball/contributing/contributing-code-pull-requests
