### ISSUE TITLE
IsDatabaseForLocalizing Feature & Possibly Integrate access for Multiple CSV feature 

### ISSUE THREAD

**Issue by kaewdev** [vchelaru/FlatRedBall#1534]
== IsDatabaseForLocalizing Feature - Here are my notes from testing it.  ==
+ You can have multiple CSV with IsDatabaseForLocalizing = true and the game will still build fine.
+ Loading Text - It looks like only the latest CSV IDs and values will be accessible. e.g. if LocalizationDatabaseA.csv and LocalizationDatabaseB.csv (latest to be loaded) then only LocalizationDatabaseB.csv IDs and values are accessible.

== FRB DOC Update ==
https://docs.flatredball.com/flatredball/glue-reference/files/glue-reference-isdatabaseforlocalizing
Setting the Language > Step 2: Find GlobalContent.Initialize(); and add the following after it:
+ There does not appear to be a GlobalContent.Initialize() line of code in Game1.cs. May need to update the Docs for this. I ended just placing it in Game1.cs Initiliaze at the top which worked fine.

== Additional Features Integration ==
+ Add access for multiple CSVs via filename.
+ Add method for accessing CSV columns values by ID and column name. e.g. string translatedText = LocalizationManager.FindByID("T_Hello").GetColumnValueByName("Speaker");
Notes:
This would be a great feature for creating custom Dialog such as Dialog with Answers. Custom Columns for Dialog with Answers can include additional column for the ANSWER IDs etc.
With methods to access multiple CSVs and per Column values, it also opens up the possibility for not only more custom Dialog but possibly integrating Save Files as well.

**Comment by kaewdev** [comment]
*Save Files = Save Game.

I guess this means integrating methods for updating and writing to the CSV file by ID and column if wanting to use it for the Save Game feature as well.

**Comment by vchelaru** [comment]
I've created a branch `1534-LocalizationDatabase` which has support for multiple CSV files and I've tested it - it works fine for me.

**Comment by vchelaru** [comment]
Updated documentation to set language level before GeneratedInitializeEarly();

**Comment by vchelaru** [comment]
You can access columns by doing the following:

LocalizatoinManager.TranslateForLanguage("T_StringId", columnIndex);

**Comment by vchelaru** [comment]
I believe I have addressed all issues except:
> Add access for multiple CSVs via filename.

I'm not sure what this means - the LocalizationManager can accept multiple files, but they get merged into one dictionary at runtime. You access the row by string ID regardless of which it comes from.

Perhaps I'm misunderstanding what you want?

**Comment by kaewdev** [comment]
Yes, don't worry about accessing multiple CSVs via filename at this stage. I was more thinking along the lines of separate Dictionaries for management and organising data and having different column names structure between different files. So possibly this can be used for the Save Game feature. 

e.g.
Unique List for Dialog
Unique List for Game Elements e.g. buttons text, UI text, hints etc
Unique List for Game Save Data

**Comment by kaewdev** [comment]
Thanks @vchelaru. Much appreciated. For the multiple Dictionaries feature, this can possibly be looked into again in the future.
