### ISSUE TITLE
Allow Glue to automatically open the Visual Studio project when loading a Glue project

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#154]
When I startup would it be possible that i could do
```bash
GlueFormsCore.exe -StartVisualStudio
```
In the commandline so that Visual Studio for the last opened project starts when starting glue

This would be especially helpful when trying to automate things

**Comment by vchelaru** [comment]
For this issue, I think we should have an option under the Visual Studio Toolbar which the user can check which says

"Open Visual Studio when Glue Project is Loaded"

This will save the extra step when opening Glue.

**Comment by vchelaru** [comment]
Fixed.
