### ISSUE TITLE
Unable to add new synced project to current FRB project due to external dependencies

### ISSUE THREAD

**Issue by ValorZard** [vchelaru/FlatRedBall#1543]
![image](https://github.com/user-attachments/assets/dd73ecf6-218a-48a4-900f-237ac6ebf186)
Tried adding a synced project that uses FNA to test, and it didn't work 
https://github.com/ValorZard/FlatRedBall-WebRTC-Demo
repo for testing

**Comment by vchelaru** [comment]
I will update the docs to explain this, but synced projects include all of the same files (code and content), but it is up to you to `#if` parts of the code which are not cross platform. In this case, the code you are referencing is not compatible with web projects. I believe there was discussion in Discord explaining that this library that you are using would work on desktop GL but not on web, and that you would need to use JavaScript for the Web side (or a library that eventually uses JavaScript).

**Comment by vchelaru** [comment]
I have updated this document to explain the available compilation symbols available:

https://docs.flatredball.com/flatredball/glue-reference/multi-platform

You would need to conditionally include or exclude code based on your platform. FlatRedBall itself attempts to keep the code cross platform, but we do not maintain other libraries which may or may not work on WEB.
