### ISSUE TITLE
Bookmarked items should show the icon corresponding to their type

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1554]
Same type as would be used in the normal treeview.

![image](https://github.com/user-attachments/assets/3d72ae4e-8237-4ba8-8976-7bdbea4b37b4)

**Comment by vicdotexe** [comment]
@vchelaru 
Unable to reproduce:

![image](https://github.com/user-attachments/assets/3bcd2552-61ac-454f-8d3d-9b061e52701a)

**Comment by vchelaru** [comment]
Interesting - if I try it in a new app and add a bookmark, the icon shows up correctly. However, in my Cthulhu game it does not. I'm going to debug to spot the difference.

**Comment by vchelaru** [comment]
Fixed by 8492918df74c5a93ee4221db427d65e1bcfb24a5
