### ISSUE TITLE
Slider Runtime can't find ThumbInstance

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/FlatRedBall#1566]
Creating a custom slider runtime following the example from the custom button runtime produces an error that the slider class can't find a ThumbInstance on the component. The component has a ThumbInstance and a TrackInstance. GetGraphicalUIElementByName seems to not be able to find the components.

This project showcases the error when ran. If you comment out the runtime registrations for the sliders then it will build and you can see that the form controls are working for buttons. 

[SliderError.zip](https://github.com/user-attachments/files/17369629/SliderError.zip)

**Comment by vchelaru** [comment]
Fixed
