### ISSUE TITLE
Glue should not generate duplicate parameter names

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#157]
I'm not sure exactly the chain of steps to repro this. Here's what I did immediately before this problem occurred:

1. I refactored a bunch of entities around into different folders
2. The entities impacted by refactors are outlined in red here:<br />![image](https://user-images.githubusercontent.com/711100/128907367-80d94e34-1a0f-4104-acb8-9fbe598e0c36.png)
3. I fixed various consequences of the refactor in code
4. Glue codegen for events is now broken, both method arguments have the same name:
![image](https://user-images.githubusercontent.com/711100/128907569-69add821-76aa-4eba-ba45-a60d619febd2.png)
5. I have tried regenerating the code in Glue but it regenerates in the broken state

**Comment by vchelaru** [comment]
https://github.com/vchelaru/FlatRedBall/commit/ac57380c027a32d9d90bfb172fb6b939d24bea55
