### ISSUE TITLE
Glue-generated factories should have a CreateNew overload that takes a Z parameter

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#158]
The factories generated by Glue for entities (and the `IEntityFactory` interface) have two `CreateNew` method signatures:
`object CreateNew(float x = 0, float y = 0);`
`object CreateNew(FlatRedBall.Graphics.Layer layer);`

It seems arbitrary that you can specify X, and Y, but not Z. They should either have another overload or the first one should be changed to allow Z:
`object CreateNew(float x = 0, float y = 0, float z = 0);`

Since this argument has a default, changing the interface and methods shouldn't break anything.

**Comment by vchelaru** [comment]
Fixed
