### ISSUE TITLE
Generate properties in screens to easily access instances created from named objects in Tiled

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1596]
In our game we create our game entities by setting up objects in Tiled layers that are later turned into FRB entities by the Tiled plug-in.
![imaxe](https://github.com/user-attachments/assets/d6abe4fc-a773-46b6-88f8-52d2d2f217ec)

Later, when coding we usually access these entities and manipulate them to fit the gameplay. For that we need to declare a field at screen scope and retrieve the instance from it's corresponding PositionedObjectList at initialization.

![imaxe](https://github.com/user-attachments/assets/12b083c0-a5ed-4c69-8a51-d7f18fc3afb6)
![imaxe](https://github.com/user-attachments/assets/7bf0be0a-bcca-48b8-bfa9-2b8fd1757423)

All of this boilerplate code could be avoided if the Tiled plug-in was able to code generate these objects for easy access. This would greatly speed up development times and would help a lot with debugging, since generated properties would throw an error at compile time if not found instead of crashing the game while testing.

Vic said in Discord:
"We could...
- Add something to the plug-in to generate members for all objects on an object layer. This should be optional since many games may not want this
- Investigate "partial" glue files. I started down this path a while ago so that you could have a Level1.glsj and Level1.TiledObjects.glsj

We could then generate the partial .glsj. This is a more complex feature, but it has the benefit of all items showing up in Glue as native objects in case you want to interact with them there."

The first part of the solution would be more than enough for us.

**Comment by vchelaru** [comment]
This is currently being tested on the branch `1596-generate-properties-in-screens-to-easily-access-instances-created-from-named-objects-in-tiled`. If this works okay for @mfigueirido, I'll merge it in to NetStandard soon.

**Comment by mfigueirido** [comment]
It works very well in my project.
