### ISSUE TITLE
Glue should apply object names when creating objects

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#160]
Steps:

1. Right click Objects in an Entity and create new
2. Choose a Gum object to create
3. Name the object and hit okay
4. Object has the default name in glue

![glue-object-name](https://user-images.githubusercontent.com/711100/131054331-dec27590-7377-428e-b3eb-f56dfac4ee50.gif)

**Comment by vchelaru** [comment]
Fixed
