### ISSUE TITLE
Gum does not find content after saving a new project and after the app being opened from FRB

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1614]
This happens after saving a new project:
![imaxe](https://github.com/user-attachments/assets/2e0ecd2e-fa41-4cd9-9109-aae92bf1f067)

If you opened Gum from this button:
![imaxe](https://github.com/user-attachments/assets/df9d081c-3f7a-42a8-a28e-726724bf5dd6)

**Comment by vchelaru** [comment]
Fixed by Gum commit 169044727bb20f1bc691b0e37e082b94a4cf8062
