### ISSUE TITLE
Gum does not handle correctly files sitting on the root of the project

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1615]
I have a project with this structure:
![imaxe](https://github.com/user-attachments/assets/3774b4d0-4839-494a-b981-16799060b4ca)

When I assigned the font *Mousetrap2Outline.fnt* to a new text component I created the app crashed.
After that, whenever I click on that component the app throws this error:
![imaxe](https://github.com/user-attachments/assets/fa2a99d1-d7d2-41ec-8c58-82b4a9d95c4d)

It seems Gum does not like fonts to be sitting on the root of the project, ```GetDirectory()``` returns ```String.Empty``` and crashes.
![imaxe](https://github.com/user-attachments/assets/2a0efe8d-3cff-4d1d-b37e-56df6d8c3d0d)

**Comment by vchelaru** [comment]
Fixed by Gum commit 2b050618be81599fce72fee07391db35eed0a4eb
