### ISSUE TITLE
Glue does not remember the last project folder

### ISSUE THREAD

**Issue by RychuP** [vchelaru/FlatRedBall#1620]
Closing a project via File/Close Project and a subsequent File/Load Project results in Glue starting in top drive directory C: rather than last opened folder. Suggested behaviour: Load Project starts in last opened folder or a folder containing FRB projects.

**Comment by vchelaru** [comment]
Fixed by b4ad4bbdbec3daba5d6c6dad6e0725fbb0a62e03
