### ISSUE TITLE
Pop up window layout overlapping buttons

### ISSUE THREAD

**Issue by RychuP** [vchelaru/FlatRedBall#1635]
Changing BaseEntity results in a pop window with layout issue as per image below.

![IMG_20241114_194811.jpg](https://github.com/user-attachments/assets/b61f3109-9e70-48e3-a5b1-12df57b0875d)

**Comment by vchelaru** [comment]
To reproduce this:

1. Create a new platformer project
2. Right-click on Player and select the option to create a derived entity. Name it anything, like DerivedPlayer
3. Once the DerivedPlayer entity has been created, go to its Properties and change the base type to <NONE>

The pop-up appears. In my case I wasn't able to get the text to overlap, but I suspect it might have to do with UI scaling in Windows. If the UI scale is 100%, it renders okay, but if it's scaled up, this may not render correctly.
