### ISSUE TITLE
Document new TileIcon uses

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#166]
During the course of WeeRPG I created two new tile icons which will almost definitely be used in other games:

![image](https://user-images.githubusercontent.com/711100/131425605-34fb4c57-25d9-46bd-8443-351f1ba1a177.png)

1) This is a "FenceCollision" tile. FenceCollision should be used for low obstacles such as tables, fences, or pits. You can shoot over, fly over, or potentially jump over fence collision but you cannot walk or drive over it.

2) This is a "NavMesh" tile. NavMesh tiles should be used to define where node networks generate navigation points on a tilemap.

These icons will be available in the FRB png file the next time I update the engine.

**Comment by profexorgeek** [comment]
Tilesheet is updated as of commit 460cc2d785eb678e431bbf5b99f80b1841d6395d

**Comment by vchelaru** [comment]
Currently most icons are not documented anywhere, and the standards haven't been 100% settled on so there's no documentation to add yet.
