### ISSUE TITLE
XNB files not created when WAV files are drag and dropped into the FRB editor

### ISSUE THREAD

**Issue by mza299** [vchelaru/FlatRedBall#1667]
I found this issue by doing the following.

1.) Dragging a FRB supported WAV file onto the "Files" folder of a Screen.
2.) Ran the program in VS.

VS gave me an error saying that the XNB was not found.

I checked the documentation and found this:

https://docs.flatredball.com/flatredball/glue-reference/files/file-types/glue-reference-wav-file-wav#wav-and-xnb-files

However, When i right-click to attempt to rebuild it, that option is not there.

**Comment by vchelaru** [comment]
I have updated the documentation with an additional screenshot to show how to set UseContentPipeline to true. Perhaps this is the problem?

I ran a quick test and it worked okay for me:

![24_19 57 41](https://github.com/user-attachments/assets/36b88685-8d39-4bb2-bd8c-527a2801f034)

![image](https://github.com/user-attachments/assets/2af2e7bc-aa0a-4547-9512-0cb8cd2c6adb)

Something must be different about your setup or your particular steps. Can you verify that you have this value set? Perhaps you can take a screen recording of the problem?

**Comment by mza299** [comment]
Somehow, I missed the contentpipeline property. my bad. It works now.

**Comment by vchelaru** [comment]
Thanks for bringing it up, the docs did need an update.
