### ISSUE TITLE
Document SolidCollision consequences

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#167]
I fell into a trap in WeeRPG that we should document for beginners.

1. I know that FRB can handle large tilemaps so I created my tilemaps way larger than I needed.
2. Since I'm generating nodes wherever there _isn't_ a SolidCollision tile I filled all the empty space with solid collision
3. Map load times were suddenly 20-30 seconds and I had to profile to figure out why

Basically when creating large maps, users should minimize SolidCollision and use NavMesh tiles instead of filling empty space with nodes. We should probably mention this in whatever docs/tutorials are relevant!

**Comment by vchelaru** [comment]
Instead of documenting, I've greatly improved the performance of creating large sets of collision. Larger tests should be about 9x as fast, so this should be good enough to cover most cases.
