### ISSUE TITLE
Reload in the GlueView Update

### ISSUE THREAD

**Issue by potato667** [vchelaru/FlatRedBall#170]
So after the GlueView update reload wont work so i spammed on the reload and tried to switch from game to edit and vise versa
then nothing happend...
minutes later the game started opening and crashing the doing the same for like 10 times and i also gave it paitence and time but it didn't work

**Comment by vchelaru** [comment]
The game project was old. Newer versions of Glue now perform version checks and don't show the check box if the project is too old.
