### ISSUE TITLE
Glue should show actual default for derived circle radius

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#179]
1. Create an Parent entity that has a circle and make the circle `SetByDervived = true`
2. Set a radius on the circle in the Parent
3. Create a Child entity that derives from Parent
4. View the Child circle's Variables in Glue
5. The Radius of the Child's circle will show zero and be green, signifying the default value but this is not the actual default

**Comment by vchelaru** [comment]
Fixed 7a3c8681edd9cf35398f501a4d8a2dccd81f252f
