### ISSUE TITLE
Getting factories dynamically by entity name shouldn't throw an NRE

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#180]
The `IEntityFactory.Generated.cs` file in my project has this code:

```csharp
var factory = factories.FirstOrDefault(item =>
            {
                var type = item.GetType();
                var methodInfo = type.GetMethod("CreateNew", new[] { typeof(FlatRedBall.Graphics.Layer), typeof(float), typeof(float)});
                var returntypeString = methodInfo.ReturnType.Name;

                return entityType == returntypeString ||
                    entityType.EndsWith("\\" + returntypeString) ||
                    entityType.EndsWith("/" + returntypeString);
            });
            return factory;
```

This code throws an exception because `methodInfo` is null. The `methodInfo` is null because the method signature provided to `GetMethod` is wrong. We recently added the `float z = 0` optional parameter to the `CreateNew` method but this code generator has not been updated so a `CreateNew` method with only two float arguments doesn't exist!

This is the actual method signature generated into one of my factory classes:
```csharp
public static AreaOfEffect CreateNew (Layer layer, float x = 0, float y = 0, float z = 0)
```
The code generator should be updated to emit a `GetMethod` request that looks for three float arguments, not two.

**Comment by vchelaru** [comment]
Fixed.
19c90270f4fa93601e1ed6a4d2b30821e47d0b76
