### ISSUE TITLE
Showing and Hiding Gum tools should do something

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#184]
Clicking these options does nothing:

![image](https://user-images.githubusercontent.com/711100/132911337-55dc1579-9dde-4137-a4d5-5a02c56833eb.png)

**Comment by vchelaru** [comment]
This was working at one time, but broke when a new WPF-based panel was introduced. Now it's fixed for the new panel.

4437c16a0a9cd6f37897323caec65ad642ca3314
