### ISSUE TITLE
Gum should show calculated heights

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#185]
In this situation, I don't know the exact height of a component. If I want other components to exactly match the height in absolute units, the only way to do it is to guess:

![image](https://user-images.githubusercontent.com/711100/132911590-8b8af7cd-92ad-4119-a4c7-f3a829c54596.png)

This was a problem in CSS for years until finally the front-end dev tools showed exact breakdowns of size. Gum does not need something this complex but it should have a way to see the final dimension of a component whose size may require nested calculations:

![image](https://user-images.githubusercontent.com/711100/132911755-6f2728af-3590-4f20-8762-b637364bc327.png)

**Comment by vchelaru** [comment]
Fixed 

https://cdn.discordapp.com/attachments/586997460233093133/886687020552974357/12_12_57_12.gif
