### ISSUE TITLE
Glue should detect and rebuild XNB files in projects that use the content pipeline

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#188]
Repro steps:

1. Clone a new project or open the gum xnb fontcache folder here: `[YOUR PROJ]\BuiltXnbs\DesktopGL\gumproject\fontcache`
2. Delete the XNBs
3. Restart Glue

**Expected result:** on Glue startup it should detect missing XNB files and generate them automatically

**Actual result:** You must manually generate content pipeline content here:
![image](https://user-images.githubusercontent.com/711100/133183984-ecb8cf8e-fe6d-4ab2-a20a-3722ed8e9e45.png)

**Comment by vchelaru** [comment]
Fixed.

37485936e25bc67cc50be6e41852f58c4b6a69e9
