### ISSUE TITLE
Localization error for presumably all non-english Windows machines.

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#195]
The 'Program files(x86)' folder is not the same across all languages.

For example the German machine name of the folder is 'Programme (x86)'.

This is causing problems when it tries to find MGCB.exe under C:\'Program Files (x86)'\MSBuild\MonoGame\v3.0\Tools\MGCB.exe

![GlueFormsCore_ehh7Y1FQ8a](https://user-images.githubusercontent.com/69159664/133937148-f27c68bd-0881-4750-999b-30a4c84b75a4.png)

![RGpfajzrka](https://user-images.githubusercontent.com/69159664/133937238-9cd110e2-ea32-4ec3-adcb-76980d1ff90e.png)

As you can see MGCB.exe exists.
![explorer_DBrKzeAHYw](https://user-images.githubusercontent.com/69159664/133937275-f8ee4bca-4701-4fae-b2f1-00e13adc61dd.png)

**Comment by vchelaru** [comment]
I would like to fix this by adding the MonoGame 3.7 content pipeline tools right to Glue so users don't have to manually install Monogame.

**Comment by vchelaru** [comment]
Attempted a fix: 
7cef7f531804aad2e5e1bd7f74c88eb4abe8a291
