### ISSUE TITLE
Dragging components in Gum should be absolute, regardless of rotation

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#198]
When a component is rotated 90 degrees, the component dragging is incorrect:

![gum-broken-rotation](https://user-images.githubusercontent.com/711100/134098809-6feaf1d5-f9c0-419c-8f2e-927eb9517b94.gif)

**Comment by vchelaru** [comment]
Fixed.
![23_18 51 49](https://user-images.githubusercontent.com/729631/134602170-64e0d0f7-b1fd-4fd9-a9be-f9c348815966.gif)


03eb630441190022616b9793442f093a3c9599a7
