### ISSUE TITLE
Gum dimensions should always be readable

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#199]
In some cases, the dimension readouts (which are super helpful, btw) appear behind other UI. These should always be readable and the dimension color should probably be selectable by the user, in the same way that the grid colors are configurable - this is the only way you can guarantee the color won't blend into existing UI.

Note that both the color and the layering make it difficult or impossible to read:
![image](https://user-images.githubusercontent.com/711100/134365784-edb84c00-fd49-4d72-8744-4b05c2834c07.png)

**Comment by vchelaru** [comment]
Talked to @profexorgeek about this and we're going to solve this by adding option to change color of these.

**Comment by vchelaru** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/729631/134601137-09287d4e-715a-4e5a-8ed2-9c42797cffb2.png)

e64977b7333cbdcaf68551a49285855d0f76b136
