### ISSUE TITLE
Gum should not change grid color on resize hover

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#200]
How this happened:

1. I opened project properties
2. I changed both grid colors
3. I went back to working
4. Grid colors change on hover

Note that the colors they change to are not colors I have selected at any point so I don't know what's happening here.
![wee-gum-dimensions](https://user-images.githubusercontent.com/711100/134366697-1f05a4a5-dbf6-468e-b69f-d037b0efb637.gif)

**Comment by vchelaru** [comment]
Closing this for now, it's  rare bug and I'm not sure how to fix it :(
