### ISSUE TITLE
Gum does not refresh image file changes reliably

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#201]
We may have to collaborate to repro this. I've noticed this in cases when I change the spritesheet with photoshop and reported it. However, photoshop does some weird stuff with spamming the file system with changes and so there were some cases where it was photoshop's fault and not Gum.

However I just cleared and refreshed the font cache after fixing a font problem and Gum didn't react to that change either. So we should revisit whether Gum is reacting to image file changes, otherwise the artist must restart Gum whenever they change a spritesheet.

**Comment by vchelaru** [comment]
To solve this, I believe there should be a window that has diagnostic information on which files are awaiting refresh. This could list the # of files, time since last file change, and provide viewable snapshot of which files are awaiting refresh.

**Comment by vchelaru** [comment]
The latest Gum has a **File Watch** tab which can be used to look at which files are changing.

![image](https://user-images.githubusercontent.com/729631/147834900-fc8684ea-18ae-474a-9a75-eab337266e49.png)

@profexorgeek whenever you're ready we could fire it up and look at that to get a sense of what's changing.

**Comment by vchelaru** [comment]
Could not reproduce this, but now we have more diagnostic information, so if it happens again, take a screenshot of the File Watch tab and we'll know what's blocking updates.
