### ISSUE TITLE
Entities and Screens with SetByDerived should give the user some kind of indication of an error before runtime

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#207]
1. Create entity BaseEntity
2. Add a Sprite to BaseEntity
3. Select the Sprite and mark it as SetByDerived
4. Drag+drop an instance of BaseEntity into a Level
5. Set the Level as the starting level
6. Play the game

Observe: Game compiles, but crashes
Expected: Glue or the compiler should give some indication of an error prior to a confusing crash.

Additional information:

When a base entity has SetByDerived on one of its objects, that means the instance will not be created by the base. Therefore, a derived is required to actually create that object. If instantiating the base, the object will always be null.

Using the example above, this means the Sprite object in BaseEntity will always be null, so any variable assignment on this Sprite will crash due to a NullReferenceException. This could be solved in one of two ways:

1. Make the base class `abstract` so that it cannot be instantiated by itself
2. Make all variable assignments be null protected

Option 2 is more flexible as it allows instances of the base to be created, but it has some downsides. First, every property will have an if check around it, which will make performance (slightly) slower. More importantly, it is likely that some cases will not be caught by code generation, especially when dealing with plugins, so completely solving the issue using option 2 is going to be difficult to do. But option 1 is a potentially breaking change and it could be too restrictive. Are there cases when elements with objects that have SetByDerived=true should be instantiated by themselves? Need to think about it.....

**Comment by profexorgeek** [comment]
## Null check option

I think I'm opposed to the null checks everywhere. That's overly defensive and would probably hide bad behavior. It'd be better to blow up early so we know and can have these conversations.

## Abstract option
Most of the problems I can come up with are really contrived. This is about the best case I can come up with:

1. ShipBase: spaceship class that has some basic physics functionality but no objects
2. ScoutShip: deriving class that specifies that the ship will have one (SetByDerived) sprite called `HullSprite`
3. DragonScoutShip: specific class that sets `HullSprite and it's unique behavior

Theoretically you might want to create generic `ScoutShip` objects and set their sprite in code but also create `DragonScoutShip` objects that have special behavior? I would avoid that as a pattern but it's hard to guess all the things a dev might want to do and why.

## Base class flag idea

I had a third idea but I don't think it's good.

What if you codegen a (static?) property like `IsBaseClass` whose value is `true` as long as any child is `SetByDerived`. And Glue codegens verbose exception, thrown just before setting properties if `IsBaseClass` is `true`. So the developer will either:

1. Know what they are doing and either swallow the exception or manually set `IsBaseClass` to true
2. Have an exception thrown that explains the problem so they can fix it



**Ultimately after thinking (typing) this through I think the `abstract` idea is probably best. You can work around it by creating another derived type that safely sets the `SetByDerived` object. Other ideas are more complex and defensive.**

**Comment by vchelaru** [comment]
The fix is to mark the entity class as abstract. The following changes are needed:

1. Codegen the class as `abstract`
2. Do not show the **Add instance to GameScreen** quick action button for abstract entities
3. Do not allow Drag+drop instances into other screens of the base type
4. Do not allow adding a single instance through right-click on the list of the base type
5. Do not allow adding a single instance by selecting the base list type and then clicking the button in quick action
6. Do not show the "Add factory" button in quick actions when selecting the base entity
7. If the user changes the CreatedByOtherEntities to true on BaseEntity, warn and set it back to false

**Comment by vchelaru** [comment]
Fixed.

62cb11be4e3f0b2d1d4136817f44a81ff87bf242

**Comment by vchelaru** [comment]
I am reopening this because this change needs to be revisited for the new live edit.

A common task when working in live edit is to add a new Level. Levels are screens which inherit from GameScreen, and GameScreen has a Map object which has a SetByDerived value set to true. Therefore, GameScreen is an abstract class.

When creating a screen in edit mode, one of three options exist:

1. The Screen has not been edited at all - this would instantiate the object using the type that is code-generated and compiled on the project.
2. The Screen is a brand new screen which does not inherit from any other screen. In this case, a DynamicScreen is instantiated. DynamicScreen is fully dynamic, and uses no codegen.
3. A screen is either modified during edit mode, or is created new but inherits from another screen. In that case, a HybridScreen is instantiated. The HybridScreen references a code generated screen, but it can modify this screen with changes made during edit mode.

In the case of a Level screen, option 3 is necessary since the level inherits from GameScreen. This causes a problem because HybridScreen requires an instance of the underlying screen (GameScreen), but GameScreen cannot be instantiated since it is abstract.

Therefore, the `abstract` should be removed from any Screen or Entity which has an object that is SetByDerived. This should only undo the code generation of `abtract` - all other functionality outlined above and all other functionality related to abstract screens/components which has been implemented since this card was first written should also remain.

**Comment by vchelaru** [comment]
Fixed on GlueDynamicManager branch.

6b20ae5cb62cb3be47a338e4fbaad317b8db36ab
