### ISSUE TITLE
Gum and Glue should react to deleted states and state categories

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#208]
I got to a point where Glue generates bad code for a gum screen and this is how I think it happens:

1. Create a state category
2. Create a bunch of states in that category
3. Create animations that animate between those states
4. Make sure Glue has generated code referencing those states
5. Delete the state category

Expected behavior: Gum should warn me that I have animations referencing those states and possibly delete those animations? Glue should potentially warn about animations missing states too.

Actual behavior: The Gum animation pane is hidden by default so I forgot all of the animations existed. Glue codegen started throwing errors and I had to dig through the codegen and remember that I had bad animations and delete them manually

**Comment by vchelaru** [comment]
Fixed.

98eb5a01d52d5339128c4a50d05d263dcbec9523
