### ISSUE TITLE
Level editing ideas to consider

### ISSUE THREAD

**Issue by dantogno** [vchelaru/FlatRedBall#209]
An edit mode resolution setting that the game switches to when edit mode is entered. This allows for more screen real estate when editing maps if your game resolution doesn't use the whole screen.

**Comment by dantogno** [comment]
I double clicked a script in glue to open it in VS. I didn't realize it, but it opened in the same instance as my already running glue. It didn't open the game project .sln. This confused me because ctrl+, wasn't finding things and it appeared that the game was running when it wasn't (glue was running), etc.

**Comment by dantogno** [comment]
Each time I start glue by running it in VS, it is loading with no project loaded, which causes me to add an extra step of loading the project to my workflow. In the past I recall glue loading the previous project unless you held down shift or something like that.

**Comment by dantogno** [comment]
![image](https://user-images.githubusercontent.com/3150710/134785527-172cfce6-3a33-4ff4-82f0-3bc884cf0efa.png)
This is a compile error when I try to run the game from glue. But it is hard to notice. Red text would help. I was just wondering, "why isn't it doing anything?" for a bit.

**Comment by dantogno** [comment]
I had a gnarly bug where I made a map from copying level 2, then I added a new spawn group by using the quick action (it gave it the name SpawnGroup3, which made sense because 1 and 2 were there from copying level 2). Then I added a new spawn action in custom initialize and hit save and it closed my running game. It turns out it removed SpawnGroup1 and SpawnGroup2 from my new level (which, why did these copy anyway?) and it also removed them from Level2 (no clue why). This gave me compile errors since there was code in Level2.cs referring to SpawnGroup1 and SpawnGroup2. The icing on the cake is that somehow SpawnGroup3 wound up in Level2... Very confusing. BUT, to relate this to FRB workflows in general...

It kind of sucks because I can't just discard the changes on Level2, because the changes live in the .glux file
and discarding that would lose a bunch of other stuff
So, one note would be that keeping level data in the glux vs the tmx is  kind of more risky
or at least it's more complicated to undo changes
or restore a particular level
to a previous version
without collateral damage.

**Comment by dantogno** [comment]
The play / edit toggle might make more sense UX wise up at the top where the play button is. Kind of like how VS play button turns into a stop button while the game is running. Maybe the FRB play button should somehow show the play / edit buttons up where the play button is in glue.

**Comment by dantogno** [comment]
In Unity, when debugging, sometimes it is useful to be able to see the game window and the scene editor window at the same time while the game is running, for example to have a different camera angle in the scene view or see the triggers that aren't visible while the game is running. 

For instance, in our game, I kind of want to see the zoomed out perspective with the camera outline and my spawn group triggers visible while the game is running.

**Comment by dantogno** [comment]
In Unity, it's pretty essential to double click on game objects in the hierarchy to have the scene view camera center on them.

In Glue, it would be good to have a way to click something in the entity list and have the game camera focus on it (as opposed to trying to find it manually by moving the camera around)

**Comment by dantogno** [comment]
It would be cool to have some sort of FRB Launcher helper app. It could have a shortcut to update the repos and a button to build and run glue. That would be nice. It takes a lot of clicks to get everything up and running to start working now.

**Comment by vchelaru** [comment]
I'm closing this as most of the issues have either been addressed. Remaining issues are large enough that I think they're not worth adding at this time.
