### ISSUE TITLE
Error when tunnelling a variable in a contained object

### ISSUE THREAD

**Issue by FletcherK** [vchelaru/FlatRedBall#23]
Hi,

I've recently installed FRB for a college (UK) computer science project. I've been completing the tuorial project Beefball to get to grips with Glue and FRB. All has been going well untill now.

While creating the logic for the "ScoreHud" entity, I need to tunnel a variable from the "Team1Score" object. However, when attempting to do this via drag and drop, the variable fails to be created (no error, pop-up etc.), it just doesn't appear in the "Variables" tree.

Attempting the other method in Glue - right click, "Add New Variable", "Tunnelling a vari...", and completing variable setup that way, I receive an error:

"A plugin has had an error. Shutting down the plugin Embedded Plugin version 0.0"

Followed by some "Additional information:" which I shall add at the end of this post as it is quite lengthy.

Can anyone help with this problem? I'm not sure if I'm doing something wrong or if there's a problem with my installation of FRB, XNA Framework, VS, etc.

Thanks,

Fletcher

 NOTE: I've not added the additional information as I said I would as the window containing the error message has no ability to copy and paste. If it is needed to provide help, let me know and I'll type it up.

**Comment by vchelaru** [comment]
I'm investigating now. BTW, when a popup appears, you can still CTRL + C and Windows will copy the entire contents of the popup to the clipboard.

**Comment by vchelaru** [comment]
I've reproduced it, am working on a fix now.

**Comment by FletcherK** [comment]
Okay, cheers.

**Comment by vchelaru** [comment]
I have a fix, am testing it now and will start a build. I'll message where when the build is live.

**Comment by FletcherK** [comment]
Okay, thanks again, surprised with the quick response and help so thanks again.

**Comment by vchelaru** [comment]
The automated build is finished, you should be able to re-download Glue and use the newly-downloaded version to continue.

Also, feel free to ask anymore questions here, or if you'd like you can also join our Gitter chat room for quicker turnaround, or just to say hi.

https://gitter.im/vchelaru/FlatRedBall

**Comment by FletcherK** [comment]
Gonna show my British-ness here: thanking you for the fifth time! Cheers for the quick help and fix, and of course for the brilliant engine (and Glue). I'll be sure to drop in on Gitter at some point again.

Thanks (once again),

-Fletcher-
