### ISSUE TITLE
Glue (gluj version) should not break top down codegen on restart

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#234]
Steps (test with WeeRPG)

1) Open project in Glue, try to build in Visual Studio
2) Notice that `DataTypes` codegen fails to generate required values and game won't build
3) Change top down movement values, code generates correctly
4) Close and reopen Glue - code is generated incorrectly again

GIF:

![glue-break-topdown](https://user-images.githubusercontent.com/711100/137001202-7c713cc7-b033-4af4-93cb-cc6246d7c267.gif)

**Comment by vchelaru** [comment]
Fixed.
