### ISSUE TITLE
Runtime exception in game from a VisibilityGrid

### ISSUE THREAD

**Issue by FletcherK** [vchelaru/FlatRedBall#24]
visibilityGrid is an instance of VisibilityGrid (FlatRedBall.AI.LineOfSight.VisibilityGrid)

When attempting to use its method Activity(), the following exception is thrown:
System.ArithmeticException: 'Function does not accept floating point Not-a-Number values.'

Details attached incl stack trace

**Comment by FletcherK** [comment]
Having trouble with github attaching a file, will update

**Comment by vchelaru** [comment]
Okay, let me know if you can include an image or stack trace or (best) a sample project and I'll investigate.
