### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by VedVid** [vchelaru/FlatRedBall#25]
Hello.

Is it possible to browse docs offline? I don't see them shipped with engine, nor option to download them from website or build from source. 

Best regard,  
Ved

**Comment by vchelaru** [comment]
No the docs as a whole are hosted in wordpress on FlatRedBall.com so I don't know if they can be exported from there.

Of course, the engine itself has XML docs so you can get information about the engines in Visual Studio just like any other library.

Sorry, I hope that helps.

**Comment by VedVid** [comment]
Thank you for answer. In that case, I'll just convert docs into pdf for myself, if you don't mind - I like working when I'm in my plot, but there is no way to access internet there.

**Comment by vchelaru** [comment]
I don't mind at all! Please do, and let me know if you run into any issues. 

Also keep in mind that the FRB docs are a "living" - I update them very frequently to clarify, add new info, and fix errors.
