### ISSUE TITLE
CameraControllingEntity should have easy way to set single targets

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#250]
The CCE has a `Targets` property that is a `List<PositionedObject>`. This is awesome b/c it auto finds the middle of the targets and smoothly tracks that. However, many games have a single target and may want to swap between targets and get the benefit of the entity's smooth interp.

You should have a convenience property that is something like:
```csharp
public PositionedObject SingleTarget
{
  get {
     // return first index? throw error if count > 1?
  }
  set {
     Targets.Clear();
     Targets.Add(value);
  }
}
```

I don't have a strong opinion on what the `get` behavior should be.

**Comment by vchelaru** [comment]
Fixed.

didn't add a getter.

9c282d431664d95cfa892d18b5de2aef7fc73d2b
