### ISSUE TITLE
Glue should display correct defaults

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#252]
Steps:

1. Create base entity with a circle
2. Set the radius on the circle to 48
3. Make the circle Set By Derived
4. Create a derived entity
5. Observe the radius on the circle

Expected result: The circle radius on the derived object should be 48 and green (because it's default)
Actual result: The circle radius on the derived object is 0 and green (wrong default)

![glue-default-values](https://user-images.githubusercontent.com/711100/140615354-9b5813aa-a34f-46d9-8e9d-c3624fdc9972.gif)

**Comment by vchelaru** [comment]
I believe this is fixed on the latest version of FRB. You can see that the new version also colors default values as green:
![06_10 44 28](https://user-images.githubusercontent.com/729631/140617223-39f08657-74dc-4741-a0aa-f82f71c704d9.gif)
