### ISSUE TITLE
Animation Editor should have expand/contract all option

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#256]
The animation editor should have icons that expand all chains or contract all chains.

**Comment by vchelaru** [comment]
Fixed
831f24679c6e2a83e6198298deaaa20f53bafff6
![05_11 03 36](https://user-images.githubusercontent.com/729631/144758096-2ae07a1a-4c85-43c2-a13b-003f87117ab8.gif)
