### ISSUE TITLE
Disabling generation of display settings is undone when re-loading the Glue project.

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#265]
This is caused by the Default values in DisplaySettings.cs. Default values will apply when excluded from the .glux/.gluj.

Reported by @mfigueirido

**Comment by vchelaru** [comment]
Fixed 

45200cf353b13514c37218ccef0ce6df152ae75f

**Comment by mfigueirido** [comment]
Now the setting stays unchecked. Thanks @vchelaru!
