### ISSUE TITLE
Last file added to global content is always shown first in the list

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#273]
Steps to reproduce:

1. Open any Glue project or create a new one.
2. Right click on Global Content Files and select "Add File->Existing File".
3. Hit "Browse" and select a bunch of files.
4. Notice how Glue doesn't sort alphabetically the last file added. Happens on subfolders as well.
![imaxe](https://user-images.githubusercontent.com/24922404/143910606-2b01d974-1d3f-4b6a-b5ca-55bfff4a5b69.png)
![imaxe](https://user-images.githubusercontent.com/24922404/143911578-bd33b645-61e0-457c-a567-44f0ece4efb3.png)
![imaxe](https://user-images.githubusercontent.com/24922404/143911641-2a0e0017-9dd7-469f-b48b-025f5e0bb8fe.png)

**Comment by vchelaru** [comment]
Fixed:
![30_09 20 12](https://user-images.githubusercontent.com/729631/144086011-eab53e07-2aed-4fa3-95fd-9a0bb9bfcbac.gif)

39a8b9d4bd5cfc111e0625ae94e0d0c301810f2f
