### ISSUE TITLE
Project Setup wizard gets stuck if user elects to not create player and game screen

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#275]
Steps to reproduce:

1. Open glue and hit "File->New Project".
2. Set name and location of the project.
3. Configure the wizard without adding a player nor a game screen:
This are the full wizard settings:
{
  "NoGameScreen": true,
  "AddTiledMap": true,
  "AddSolidCollision": true,
  "AddCloudCollision": true,
  "PlayerEntityImportUiVisibility": 2,
  "PlayerControlType": 1,
  "AddPlayerSprite": true,
  "AddPlayerListToGameScreen": true,
  "AddPlayerToList": true,
  "CollideAgainstSolidCollision": true,
  "CollideAgainstCloudCollision": true,
  "OffsetPlayerPosition": true,
  "NumberOfLevels": 2,
  "IncludStandardTilesetInLevels": true,
  "IncludeGameplayLayerInLevels": true,
  "IncludeCollisionBorderInLevels": true,
  "AddGum": true,
  "AddFlatRedBallForms": true,
  "AddCameraController": true,
  "FollowPlayersWithCamera": true,
  "KeepCameraInMap": true,
  "CreateLevels": true,
  "ElementImportUrls": []
}
4. Notice how Project Wizard gets stuck (but you can still do things in Glue).
![2](https://user-images.githubusercontent.com/24922404/144104482-3c990922-ae17-4df3-bd34-6d7dafe3c6f5.png)

**Comment by vchelaru** [comment]
There are lots of bugs here:

1. When an error occurs, showing the .txt error file crashes glue.
2. The .glux can't be saved because another operation is accessing the object list while the .json serializer is iterating.
3. The settings say to not create a game screen, but the logic still creates one.

**Comment by vchelaru** [comment]
This bug resulted in lots of other issues being found and fixed. All have been fixed:

79051d9483d2189a9e0cc67ff9473dfa74c54d44
