### ISSUE TITLE
error CS0234: The type or namespace name 'CameraSetup' does not exist in the namespace 'FlatRedBall.screens'(are you missing an assebly reference?)

### ISSUE THREAD

**Issue by Fynja** [vchelaru/FlatRedBall#28]
I'm trying to get started in using FlatRedBall, however this error apears when I try to make a project.
Is there some way of fixing this?

Thank you, Fynn.

**Comment by vchelaru** [comment]
Sorry for the late reply but I believe this has been fixed a while ago.
