### ISSUE TITLE
Icon need - focus on selected object

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#280]
My apologies @profexorgeek I forgot about this one:

![image](https://user-images.githubusercontent.com/729631/144721726-cf6adce3-51c4-4614-9e70-396d87a8397b.png)

This is the icon you can click on to focus on your current selection. We came with this as an idea but I think it needs coloring and line thickness fixes.

**Comment by profexorgeek** [comment]
Made a slight change to use our existing design language:
![image](https://user-images.githubusercontent.com/711100/144876115-06fa3243-37f4-4669-9d16-62ce6b6d10f0.png)

**Comment by vchelaru** [comment]
I still need to implement this...

**Comment by vchelaru** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/729631/145631032-86658922-7277-498c-acee-ef9aaed89204.png)
