### ISSUE TITLE
Support .NET 5 game project for DesktopGL

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#283]
Requirements:

- [ ] Create a FRB engine (dll) which runs on .NET 5. This might be called FlatRedBallDesktopGLNet5 ? Is that too long of a name? For starters it's best to probably just do the engine alone before moving on to...
- - The setup for this is easy - create a new SLN that has .NET 5 versions of all the projects. This should be somewhat easy because there are already shared code projects for all the other types.
- [ ] ...Support all FlatRedBall.Forms libraries in .NET 5.
- [ ] Create a new FRB template which references FRB .NET 5 and all monogame .NET Core (or 5?) projects.
- [ ] Add Glue support to understand SDK projects
- - This one is tricky because it requires that Glue delete files rather than just remove them from .csproj
- - Glue should not have to ever explicitly add files to projects when using this. Therefore all code that adds files to CSPROJ's needs to use the specific version type....
- [ ] Add Glue support to understand this new platform

Actually maybe the solution is to create a new SDK style project which doesn't require adding and removing explicitly. Can SDK style projects be used in .NET Framework?

Moving to .NET 5 specifically may not be as complex as moving to SDK style CSPROJ files. Therefore, it might be worth trying to create a SDK-style game project using .NET Framework 4.7X first before moving on to .NET 5. That way, Glue could be updated to support this without introducing multiple variables at once (.NET vs Framework, new MonoGame version with nuget, etc.

**Comment by charabaruk** [comment]
> Can SDK style projects be used in .NET Framework?

Yes, it's just a matter of specifying the appropriate framework target in the csproj file.

It will still be useful to explicitly add certain files to SDK-style projects since Visual Studio won't otherwise pick up on file dependencies (i.e. `<DependentUpon>`) otherwise unless the developer has installed VS extensions which handle that in the UI.

**Comment by vchelaru** [comment]
Update - Okay, so it seems that we can upgrade a .NET 4.7.1 project to .NET 6. I used this tool and it worked great:

https://github.com/dotnet/try-convert

After upgrading to .NET 6, I was able to build and run a FRB project in Visual Studio.

The problem comes from loading this project in Glue. First, when loading I ran into an issue loading .NET 6 projects in general:

https://stackoverflow.com/questions/73348274/how-to-load-net-6-project-in-a-net-6-console-application

The solution in this post solves the problems when trying to load .NET 6 projects in a .NET 6 console application. Unfortunately, doing this in Glue does not work.

Currently, Glue references Microsoft.Build libraries 16.9:

![image](https://user-images.githubusercontent.com/729631/184518312-cebef289-4a0d-474f-8b03-c2a1516acd0b.png)

I don't know if this is why .NET 6 isn't loading, even with the environment variable assignment code.

But then I realized that one problem may be that I'm referencing msbuild nugets 16.9 here, but my console project that did work referenced 17.2. But after upgrading to 17.2 I ran into a different problem:

![image](https://user-images.githubusercontent.com/729631/184518363-b704806c-0b4d-440e-bee9-027d27bf3663.png)

This error now happens on all projects, not just .NET 6 projects. It seems like we're looking specifically for 15.1 and upgrading from 16.9 -> 17.2 breaks this. Not sure why, because I didn't upgrade from 16.9.

However, Glue has a bunch of app.config files:

![image](https://user-images.githubusercontent.com/729631/184518390-5f1f2e90-fc6a-4d27-ac5b-2a09d481c4a8.png)

These explicitly redirect to 15.1, but I don't know why! I think this may have solved some earlier bug but I can't find a reference to it. It was added in commit 73aa66bbcaf93f7157419d0d7df42740ee3afa9c .

So, I think someone with a better understanding of msbuild will have to tackle this for me, because I really don't get the problem.

**Comment by vchelaru** [comment]
Update - I tried downgrading the project from .net 6 to .net 5. Then from .net 5 to .net core 3.1. Still won't load in Glue...

**Comment by vchelaru** [comment]
Fixed!!

![image](https://user-images.githubusercontent.com/729631/189454272-59accc90-717c-42ae-b392-06fb973039e4.png)

008a05ba2be92ec0d9a2dd4f81c466d80cfc0f66

**Comment by charabaruk** [comment]
Looks like I've got some work to do this weekend to switch over my project! Thanks for the hard work, @vchelaru!
