### ISSUE TITLE
More msbuild options

### ISSUE THREAD

**Issue by KallDrexx** [vchelaru/FlatRedBall#285]
When attempting to compile your game from Glue, Glue looks for MSBuild in specific locations.

However, now with the `dotnet` cli, you can invoke msbuild via `dotnet msbuild`.  That should be an option, especially if no other msbuild location was found.

Otherwise, there's also an MSBuild in `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin` that glue can't find.

**Comment by vchelaru** [comment]
Kinda fixed...

aacc7babaa126c2b902fa46f2c6501fd66b1a6bd

For some reason code referenced by nuget isn't understood. I don't know if it's because it's an old csproj, so maybe when moving to sdk style csproj files, this gets fixed automatically?

**Comment by vchelaru** [comment]
Update - I added a checkbox to output the msbuild command so that tests can be run on the command prompt outside of Glue:

7b9267ba04a205bdb76b2b8601cc094de8fa82d8
