### ISSUE TITLE
Glue should allow PositionedObjectList of Parme Particle Emitters

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#291]
I'm not sure if this is a FlatRedBall issue for @vchelaru or a Parme issue for @KallDrexx...

Creatures in my game can have dynamic particle (Parme) effects based on spell damage they have taken. I want to create a POL managed by Glue to hold these objects so they are automatically updated appropriately.

I can create a ParmeEmitter as an object on an entity:
![image](https://user-images.githubusercontent.com/711100/146426654-bcae9d78-d392-4ad9-9965-ee25fce26212.png)

But I cannot add a list of ParmeEmitters to a positioned object list:
![image](https://user-images.githubusercontent.com/711100/146426444-ee4a11e8-ec97-44bb-9e94-4b33bd56c151.png)

**Comment by profexorgeek** [comment]
I'm not sure if Parme Emitters actually are PositionedObjects so the answer to this may be to just use a regular `List<T>` in code and the emitters will be managed by the Parme manager.

**Comment by KallDrexx** [comment]
Closing as Parme emitters aren't a `POL`, and after talks in discord having one or a `List<T>` of emitters doesn't make much sense, as Parme has it's own management systems for this use case.
