### ISSUE TITLE
When writing new screen names and adding invalid characters it will throw an error but still proceed to add it

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#297]
Step 1:
Forget that space is an invalid character
![ybSHfGaAIq](https://user-images.githubusercontent.com/69159664/147160174-21b94723-399f-42a1-80cf-4e517b4b2b10.png)
Step 2:
Glue throws an error that space is an invalid chracter
![7devKqv89e](https://user-images.githubusercontent.com/69159664/147160178-bb0faf42-b28b-4832-b374-935c72f8a817.png)
Step 3:
Click ok that glue can add it anyway
![GlueFormsCore_HNwVGweBCu](https://user-images.githubusercontent.com/69159664/147160182-29bf4ad0-892d-4518-84cb-16e3f779a8f3.png)
![devenv_CAE1mtO3FZ](https://user-images.githubusercontent.com/69159664/147160185-9ca34062-1de0-497c-9ef9-2d5993406902.png)

**Comment by vchelaru** [comment]
![24_16 49 51](https://user-images.githubusercontent.com/729631/147374416-9d368ee2-c2fa-4883-91c0-1d3adaaf8f35.gif)

d2cb16b9c1ac2f7eb71ff5d313f73f3834cee1d2


Added real time validation and I think I prevented it from getting into this state. I could not reproduce...
