### ISSUE TITLE
Changing stuff inside a screen doesnt modify collision relationships

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#298]
Step 1:
Create entity
![dcJ594KFdn](https://user-images.githubusercontent.com/69159664/147162884-dcf99a3c-6c1a-4250-bbca-8b28d26c8266.png)
Step 2:
Have entity automaticall added as a List to GameScreen
![GlueFormsCore_reluARZ440](https://user-images.githubusercontent.com/69159664/147162890-198bb678-3222-450f-89bd-6d7271f27f96.png)
![GlueFormsCore_nduGNNZ7KL](https://user-images.githubusercontent.com/69159664/147162897-a836bbba-9b86-4460-ad14-9bfeeec1b830.png)
Step3:
Add Collsion with Player entity
![GlueFormsCore_b4oQetuCD3](https://user-images.githubusercontent.com/69159664/147162901-222664dd-5168-4931-a939-9fd373834a78.png)
Step 4:
#Remove it for some reason
![GlueFormsCore_H4TZCoQ7UF](https://user-images.githubusercontent.com/69159664/147162902-597d2181-12dc-46cd-a89e-c32bc054d46b.png)
Step 5:
Have Errors
![Discord_9pseJ0865y](https://user-images.githubusercontent.com/69159664/147162906-cba45e60-0394-4def-bec6-9cc5af0bfaa9.png)
![GlueFormsCore_LN3E94GYOY](https://user-images.githubusercontent.com/69159664/147162933-812f4b02-1d7a-4c41-a5d2-61112be8da9e.png)

**Comment by vchelaru** [comment]
I think the solution is - if an Object in a Screen is deleted, the following should be determined *before* deleting:

* Derived objects (if it is SetByDerived)
* Derived objects (if it is ExposedInDerived)
* Variables (if there are tunneled variables)
* Contained objects (if it is a list)
* Collision relationships (if it is part of a collision relationship)

The popup should list all of these things and let the user pick to delete or cancel the object. 

If it is deleted, then all objects including collision relationships will be removed.

**Comment by vchelaru** [comment]
Fixed 

96f927745e2896ffbf4acc0220a9503b22941c26
![23_17 17 53](https://user-images.githubusercontent.com/729631/147301752-fc4aa9a0-926e-4e32-90f7-2d074970a11b.gif)
