### ISSUE TITLE
Running game from visual studio while game edit and game embed is enabled, will cause the game to not display at all sometimes

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#308]
Here would be an example where I ran the game from visual studio and had the problem that it didnt display anywhere
![image](https://user-images.githubusercontent.com/69159664/147422480-3c16dd74-f5e0-4db3-b911-b6738cb0810c.png)

**Comment by vchelaru** [comment]
I don't see the problem - there is a game window in your screenshot. Also, do you have consistent repro steps to make this happen? Otherwise, I don't think I can solve this.

**Comment by vchelaru** [comment]
I am going to close this for now until we get some good repro steps.
