### ISSUE TITLE
TiledNodeNetworkCreator should not set Visible to true

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#343]
I recently profiled my game (WeeRPG) to understand why screen load times were creeping up. My profiling technique was as follows:
1. Force a specific level map to load for consistency
1. Debug break right before a level transition
1. Start recording a CPU profile
1. Continue and perform the level transition 
1. Break again immediately when transition is complete
1. Observe CPU usage by method call

Before making any changes, a call to `UpdateShapes` was eating roughly 20% of the CPU time for the profile period:
![image](https://user-images.githubusercontent.com/711100/148975409-b3e5ce6f-b26b-4056-9b4e-6d7686a7c63a.png)

The `UpdateShapes` method is [called when a NodeNetwork's `Visible` property is set to true](https://github.com/vchelaru/FlatRedBall/blob/NetStandard/Engines/FlatRedBallXNA/FlatRedBall/AI/Pathfinding/NodeNetwork.cs#L175).

The [`UpdateShapes` method has 5 `while` loops, and a `for` loop with a nested `foreach`](https://github.com/vchelaru/FlatRedBall/blob/NetStandard/Engines/FlatRedBallXNA/FlatRedBall/AI/Pathfinding/NodeNetwork.cs#L917). It's a computationally expensive method to run but it only needs to be run to visualize a node network, which only happens occasionally in debug. But the TiledNodeNetworkCreator sets `Visible` to true when creating a node network from a tile collection as shown here:

This is the first method in `TiledNodeNetworkCreator` and notice that it sets `nodeNetwork.Visible = true`.
```csharp
public static TileNodeNetwork CreateFrom(LayeredTileMap layeredTileMap, DirectionalType directionalType,
    Func<List<TMXGlueLib.DataTypes.NamedValue>, bool> predicate)
{
    TileNodeNetwork nodeNetwork = CreateTileNodeNetwork(layeredTileMap, directionalType);

    FillFromPredicate(nodeNetwork, layeredTileMap, predicate);

    nodeNetwork.Visible = true;

    return nodeNetwork;
}
```

I commented out `nodeNetwork.Visible = true` and the CPU time dropped from 20% to 0.03% of execution time in a repeat profile of the same transition. However, this is a generated file so this problem will reoccur when Glue regenerates the file. The template needs to be investigated to understand why `Visible` is set to true, and fixed to eliminate the performance problems caused by an unnecessary `UpdateShapes` call. Here's the profile after commenting out the `Visible` set:

![image](https://user-images.githubusercontent.com/711100/148976475-4b11cb84-9045-4a22-a87d-365335e47c8f.png)

**Comment by vchelaru** [comment]
Thanks for explaining this. I agree, Visible should not be set to true right away. I suspect I did this to make it obvious when new node networks are created, but it causes performance problems for larger maps.

I'm going to set this to false.

**Comment by vchelaru** [comment]
Fixed

657be0785de720acd543b23fec3c4ca4be6ae09a
