### ISSUE TITLE
Gum doesn't save changes in canvas size

### ISSUE THREAD

**Issue by aleksandergogoc** [vchelaru/FlatRedBall#354]
In Gum it's possible to set canvas width and height in Project Properties. Those values are not saved, so after restarting Gum one needs to set it again every time:

![image](https://user-images.githubusercontent.com/37595991/150087817-beabe703-8514-40c2-8642-9a1536583aa5.png)

**Comment by vchelaru** [comment]
Are you using this with a FlatRedBall project? If so, the Gum project will match the resolution settings in FlatRedBall.

For example, if you have a project in FlatRedBall, it will have Display Settings in the FlatRedBall Editor:

![image](https://user-images.githubusercontent.com/729631/150160736-95f5f0d8-87f5-467a-ac62-402022d01a0d.png)

These will be matched in Gum:

![image](https://user-images.githubusercontent.com/729631/150160872-37ff5659-c6d0-4d5c-adfe-7d68141e6f2e.png)

If you make changes to the **Canvas Width** or **Canvas Height**, those changes will be overwritten the next time you restart the FlatRedBall Editor.

You can make changes to the Display Settings to change the resolution of the entire game, which will be matched in your Gum project, but this does require a restart of the FlatRedBall Editor. This is a bug and I can fix this issue. However, if you do restart the FlatRedBall Editor (and Gum), then the resolution changes will apply from FRB to Gum:

![image](https://user-images.githubusercontent.com/729631/150161420-3caac44e-5594-4dca-8097-592fb4abdd02.png)

Let me know if this solves the problem for you.

**Comment by vchelaru** [comment]
Oh I forgot to mention, if you do not like this behavior, you can:

1. Expand Global Content Files
2. Select GumProject.gumx
3. Click the **Gum Properties** tab
4. Uncheck **Match Game Resolution in Gum**

![image](https://user-images.githubusercontent.com/729631/150163840-b908b2db-5b47-4d02-bb85-dd9d90843e12.png)

Please let me know if you still need help and I can re-open the issue.

**Comment by vchelaru** [comment]
![19_08 46 18](https://user-images.githubusercontent.com/729631/150165434-b6d3c415-7d90-4d1c-8b19-d3f7cc841d14.gif)

This bug will be fixed in the next version of FRB which is being built now and will be available in a few minutes.
