### ISSUE TITLE
Gum graphics are shown with wrong proportions after Glue auto-reloads on a TMX change

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#404]
This happens in a game which uses it's own camera code. That means this setting is disabled:
![imaxe](https://user-images.githubusercontent.com/24922404/152844346-452e30f9-957d-4adb-b694-1bbdaf55ebb9.png)

Tested on a new empty project with default values and it didn't reproduce.

The first time I hit play the UI is displayed correctly:
![imaxe](https://user-images.githubusercontent.com/24922404/152846498-293886b7-e21c-4c51-ab3f-2d33e848a450.png)

After a Glue auto-reload:
![imaxe](https://user-images.githubusercontent.com/24922404/152846616-09ca90e1-5f07-43b4-8f84-0a50dccf95ba.png)

I suspect this happens because the comunication code between Glue and the game is resetting some stuff related to the camera. I think camera stuff should not be executed when Glue camera settings aren't enabled even if Game Edit is enabled (enabled in order to use auto-reloads, edit mode never worked properly to begin with in this project).

![imaxe](https://user-images.githubusercontent.com/24922404/152846888-739af550-8e9d-4e75-ba63-17b96ae95a75.png)

**Comment by vchelaru** [comment]
I believe this is fixed now

54bea0932f779e30b3c72735e500cb7f7c5bcd98

Testing this out with @mfigueirido  ...
