### ISSUE TITLE
Creating a Glue variable of a Gum State category that is exposed in derived causes Generated code with an invalid reference to the type property's in the Entity's VariableState

### ISSUE THREAD

**Issue by Cabrill** [vchelaru/FlatRedBall#405]
1.  Create a Gum Component
2.  Create a category and states for the Gum Component
3.  Create a Glue Entity, and add the Gum Component as an object
4.  Expose the State of the Gum component on the Glue Entity, and set it as 'Set by Derived'
5.  Create a new Glue Entity that is derived from the first
6.  Create a State on the newly derived entity that attempts to set the State of the Gum component

Expected:  
Gum component state can be set by the derived Glue entity's state

Observed:
Generated code prevents compiling

Example repro project:
[GumStatesOnDerivedGlueRepro.zip](https://github.com/vchelaru/FlatRedBall/files/8019749/GumStatesOnDerivedGlueRepro.zip)

**Comment by vchelaru** [comment]
Fixed.

96a8ce942d3921b4252e65ef7ffefd2f1d78b8e5
