### ISSUE TITLE
Very high CPU usage while rendering a Gum layer despite nothing is visible

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#406]
Gum takes a lot of CPU time to render despite no components are visible. This is the scene:
![imaxe](https://user-images.githubusercontent.com/24922404/152977725-3242b937-dc9a-44bc-ac4d-ae40eebb8e7f.png)

These are the components the game screen contains. Only the debug text is visible in the scene:
![imaxe](https://user-images.githubusercontent.com/24922404/152978338-f8a3dc62-0227-4e28-bb67-ffdcfc001826.png)

Here can be seen how GumIdb rendering takes much more CPU time than rendering the whole scene (tiled maps, entities and other custom stuff):
![Tempo de CPU](https://user-images.githubusercontent.com/24922404/152976910-cab9f2f7-9d34-492d-91af-866e55c62f30.png)

Taking a look at Gum rendering, PreRender and Render CPU usage is high:
![imaxe](https://user-images.githubusercontent.com/24922404/152979214-de600696-b6b6-4188-8031-e63de79302c3.png)

Also noticed two GumIdb on the same list which I find strange:
![imaxe](https://user-images.githubusercontent.com/24922404/152979477-e11917d8-0a9f-44fc-badd-0b918c4ff1cb.png)
![imaxe](https://user-images.githubusercontent.com/24922404/152979535-2bded105-f43a-42a2-a039-7a04ca07a0d2.png)

I noticed not visible components were being processed. I suspect Gum rendering might be ignoring the visible states and that can be a blow to performance if the UI has a little complexity.

**Comment by vchelaru** [comment]
I have reduced the amount of CPU usage, and in my tests, screens render more quickly. This is definitely an improvement, we'll see if it's enough.

This was a change in the Gum repository.
