### ISSUE TITLE
Gum should allow time factor for animation playback

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#413]
**Use case 1: Normalized animation timing**
In my game, all animations are normalized to 1 second. This allows me to dynamically change attack times, walk speed, or whatever in the game based on a consistent starting point: if I want an attack to take 0.45 seconds, the math to play the attack at exactly that speed is easy. But, it's not always easy to preview animations at the normalized speed. I would like to adjust the playback speed for visualization without changing animation timing.

**Use case 2: Stretch/Squash**
Sometimes it's not easy to know what's wrong with an animation. Is it too fast or too slow? Why is a specific part jerky? Being able to quickly squash or stretch the animation time visually and _consistently_ is important. Dragging the slider does not produce the same result as drag speed may not be constant and you can't watch a loop over and over at different speeds to evaluate.

**Comment by vchelaru** [comment]
Fixed
![11_18 04 45](https://user-images.githubusercontent.com/729631/153689988-43a7bab3-dcef-475e-b283-7f070d81dbb4.gif)
