### ISSUE TITLE
Typing a Gum component state name into the DefaultValue property of the Glue entity's properties causes compile error

### ISSUE THREAD

**Issue by Cabrill** [vchelaru/FlatRedBall#414]
Desceription:  Typing a default value for a Gum Component state into the Glue entity properties (either in the 'DefaultValue' textbox, or the variables list) causes a compile exception due to codegen in attempting to assign a string value to a type property.  It correctly converts if used as a Glue entity state value, but not as a default.

Dev repo steps:
1.  Open repro project in Glue: [DefaultValueOfGumStatesOnDerivedGlueRepro.zip](https://github.com/vchelaru/FlatRedBall/files/8028965/DefaultValueOfGumStatesOnDerivedGlueRepro.zip)
2. , Rebuild project, inspect error on L234 of CardEntity.Generated.cs

User repo steps:
1.  Create Glue w/ Gum project
2. Create a Gum component with states
3. Create a Glue entity with an instance of the Gum component
4. Expose the Gum component state by tunneling the property
Either:
5a. Click Variables on the Glue entity in Glue Explorer, then type the Gum component state name
or
5b.  Click the exposed variable's name in the list of variables, and type in a Gum component state name in 'DefaultValue'

Expected:  Codegen recognizes the state assignment
Observed:  Codegen attempts to assign string to type property

Location in Glue of Variable assignment (5a):
![image](https://user-images.githubusercontent.com/2907579/153111514-f613dc60-7d98-456c-a003-bde6bd170173.png)

Location in Glue of DefaultValue (5b):
![image](https://user-images.githubusercontent.com/2907579/153111691-f7a688cb-7ba7-4f80-b566-7e8955440f12.png)

**Comment by vchelaru** [comment]
Removed low priority - since it's a codegen issue, it could be total blocker, so I think it's at least normal priority.

**Comment by vchelaru** [comment]
Fixed

bbf4ccd1a829a8d0edbb67e3da39c9024b9b346d
