### ISSUE TITLE
4.6.1 required when building Glue

### ISSUE THREAD

**Issue by zdman2022** [vchelaru/FlatRedBall#415]
Instructions on site had me install 4.7.1 but when opening the solution, it said it required 4.6.1.  After installing 4.6.1, it opened correctly.

**Comment by vchelaru** [comment]
I upgraded one library from 4.6.1 to 4.7.2. There is another library that requires 4.7.2 so I thought it was best to unify them.

1910bfdb4e53f9115721cd68ebac523ac6dfa6a1
