### ISSUE TITLE
Source folder name required to be FlatRedBall

### ISSUE THREAD

**Issue by zdman2022** [vchelaru/FlatRedBall#416]
I checked out the source and had named the parent folder FRB.  But, a nuget reference goes up the chain with ..\..\ to the parent of "FlatRedBall".  After renaming the folder to "FlatRedBall", I was able to successfully build the solution.  Website does not indicate this is required.  Either fix it so it doesn't matter or add instructions on the website that says it's required.

**Comment by vchelaru** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/729631/153716565-78cc1f0d-66c8-4047-ad6e-514a0e74755b.png)
