### ISSUE TITLE
Enable keyboard movement in screen/tmx search controls

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#417]
![imaxe](https://user-images.githubusercontent.com/24922404/153191852-3ce25c16-7ca7-4c33-9b7c-270a842a47a7.png)

It would be nice to allow moving through filtered items while pressing up/down arrows and be able to hit them by pressing enter. This way no mouse input is needed becoming the whole operation faster.

Edit: I meant being able to jump to the items from the search box by pressing down arrow as well.

**Comment by vchelaru** [comment]
Fixed

c9ece67182b01dd00ed1605a0e2f79b5394bef40

![14_08 21 05](https://user-images.githubusercontent.com/729631/153892298-e3559a0d-fc77-4320-a50f-4fbb91add9a2.gif)
