### ISSUE TITLE
Gum should not allow multiple animation windows to exist

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#419]
You can choose State Animation > View Animations multiple times. I did this accidentally the first time and then tested to see what happens if you do it multiple times. It just keeps adding windows and these windows can't be closed or removed.

There's a side question here of: if the Animation window can be added, but not removed, why have the option to add it at all? Why not just always have the animation window available and remove the menu option?

![image](https://user-images.githubusercontent.com/711100/153243318-36283c47-a6c5-48a0-a56f-197d7983546d.png)

**Comment by profexorgeek** [comment]
Update: this also breaks animation. Once multiple windows exist, animations won't play and the application must be restarted.

**Comment by vchelaru** [comment]
Fixed

Gum repo commit:

be987c52279f051a36c417765fe2345e1f8c2d8e
