### ISSUE TITLE
Glue System.Windows.Forms v4.0.0 cannot be found

### ISSUE THREAD

**Issue by gortok** [vchelaru/FlatRedBall#42]
I have a Windows 10 developer machine, and when I try to run the compiled version of Glue I receive the following error on startup:

 
![System.Windows.Forms.ContextMenu ](https://user-images.githubusercontent.com/699891/98274977-184eb700-1f62-11eb-8416-e466b8eba910.PNG)

The error is:

```
System.TypeLoadException: Could not load type 'System.Windows.Forms.ContextMenu' from assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. 
  at FlatRedBall.Glue.Controls.PluginTab..ctor()
  at Glue.MainGlueWindow.InitializeComponent() in
C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\FRBDK\Glue\Glue\MainGlue Window.Designer.cs:line 108
  at Glue.MainGlueWindow..ctor() in
C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\FRBDK\Glue\Glue\MainGlueWindow.cs:line 84
  at Glue.Program.Main() in
C:\BuildAgent\work\a22593881c1cbdfe\FlatRedBall\FRBDK\Glue\Glue\Program.cs:line 35
```

I have the following .NET Framework versions installed, according to DotNetVersionLister:

```
PS C:\WINDOWS\system32> Get-STDotNetVersion
ComputerName : localhost
>=4.x        : 4.8 or later
v4\Client    : Installed
v4\Full      : Installed
v3.5         : Installed
v3.0         : Installed
v2.0.50727   : Installed
v1.1.4322    : Not installed (no key)
Ping         : True
Error        :

    Script start time: 11/05/2020 12:37:09
    Script end time:   11/05/2020 12:37:09
```

At this point, I'm not really sure what to do here, what am I missing?

**Comment by vchelaru** [comment]
Currently Glue requires a specific version of .NET Core installed (3.0.1). I'm not sure why this is currently a requirement, but you can install it from here:

https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.0.101-windows-x86-installer

As explained here:

http://flatredball.com/download/

We hope to resolve this by making Glue a self-contained app with no install necessary.

**Comment by vchelaru** [comment]
Matt says - try using 

`dotnet publish ".\Glue with All.sln" -r win-x64`

**Comment by gortok** [comment]
I had multiple versions of .NET Core installed; but not that version.  Making it a SCA would help the issue; but the reason that exact version is required is in the next version (3.1) Microsoft removed System.Windows.Forms.ContextMenu from .NET Core.  That's why 3.0.1 is required.
