### ISSUE TITLE
Typo in Beefball Tutorial

### ISSUE THREAD

**Issue by zdman2022** [vchelaru/FlatRedBall#420]
Should be DashFrequency instead of DashSpeed.

https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-adding-dashing/

![image](https://user-images.githubusercontent.com/1099520/153282594-f0162179-1c37-4ae8-a2f7-82e4f9806dd0.png)

**Comment by vchelaru** [comment]
Fixed.
