### ISSUE TITLE
Tree view search bar is slow on big projects

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#422]
From this:
![imaxe](https://user-images.githubusercontent.com/24922404/153458104-7019322a-c7ec-4e05-8507-f1fe258658c5.png)

To this:
![imaxe](https://user-images.githubusercontent.com/24922404/153458324-bc4b30b1-a646-4785-8d83-edd88994ae12.png)

Takes around 5 seconds and the UI becomes unresponsive meanwhile.

**Comment by vchelaru** [comment]
Fixed. Flattened the list to work more like the old list, and it's MUCH faster
![14_07 07 14](https://user-images.githubusercontent.com/729631/153879267-24002a0a-c2f0-4ec1-b498-ed74dcfbabf5.gif)


b5d1370e7138250cba5abe7d2dc4f748a496f573
