### ISSUE TITLE
Running the game with F5 doesn't work if you just opened FRB Editor and nothing is selected

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#427]
Edit: Also if you just opened the editor and select a screen with the mouse in the screens drop-down it doesn't work.

**Comment by vchelaru** [comment]
I fixed the F5, but I don't understand the bug with the screen with the mouse.

ca2626111ac1ba5b72f55c5fa6782afa9c1c0c5d
