### ISSUE TITLE
Tree contains previous project items when opening new project

### ISSUE THREAD

**Issue by zdman2022** [vchelaru/FlatRedBall#428]
In Glue, if you have a project open and if you open a new project or close the existing project and reopen using the File menu, then the tree keeps the old projects items and adds the new projects items.  You can see the duplicates in the attached screenshot.
![image](https://user-images.githubusercontent.com/1099520/154115931-43ffb593-51e7-4445-a044-e40808d8ac84.png)

**Comment by vchelaru** [comment]
Fixed

6c345d4474153e38257483a39be4c236629c5c32
