### ISSUE TITLE
Animation Editor AdjustOffsetForm Adjust All window hides Y value

### ISSUE THREAD

**Issue by dantogno** [vchelaru/FlatRedBall#432]
### Repro Steps

1. Load the AE. 
2. Right click an animation and choose Adjust Offsets
3. Select Adjust All

**Observe:** no visible Y value (see screenshot)
**Expected:** user should be able to see Y value field
![image](https://user-images.githubusercontent.com/3150710/154398974-f7a5d1a1-4715-4a6f-b8c4-9da9c618173e.png)

**Comment by vchelaru** [comment]
The fix here is to convert this window to WPF, but that's going to be a little bit of work. I'm on it...

**Comment by vchelaru** [comment]
Fixed.

63036c713f29ef7f382fc666249c6b822a7d9b5c
