### ISSUE TITLE
Cant connect to flatredball.com

### ISSUE THREAD

**Issue by FennichMoncef** [vchelaru/FlatRedBall#44]
#### Is it just me or the [site](https://flatredball.com) doesn't work at all
I can't acces to the site it just take alot of time then '*this site can’t be reached*'
Everything just work well except for flatredball.com

**Comment by vchelaru** [comment]
The site is currently not https, so you must go to http://flatredball.com/

**Comment by vchelaru** [comment]
Updated- site is now https!
