### ISSUE TITLE
Gum should export spritesheets of animations

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#444]
This came up during a "future of FRB" discussion. Gum entities may not always be the right solution for FRB but the animation tools can still be useful. Gum could have the capability to export an animation as a spritesheet at a chosen frame rate.

Note that this may be a waste of time (hence the low-pri label) as most rigging softwares already do this.

**Comment by vchelaru** [comment]
This would be a lot of work for something that may never get used. Marking this as won't fix.
