### ISSUE TITLE
Exposing the X/Y values of a Gum component on a Glue entity causes invalid generated code

### ISSUE THREAD

**Issue by Cabrill** [vchelaru/FlatRedBall#454]
Repro Steps:
1. Create a Gum component
2. Create a Glue entity
3. Add an instance of the Gum component to the Glue entity
4. Use tunneling to expose the X or Y value of the Gum component as a Glue entity variable

Expected:  GumComponentX (or Y) are accessible on the Glue entity
Observed:  Compile error in `GlueEntity.Generated.cs`:  CS1061: 'GumComponentRuntime' does not containt a definition for RelativeX/Y

**Comment by vchelaru** [comment]
Additional step - the tunneled variable must be set in a state.

**Comment by vchelaru** [comment]
Fixed

b2c659805410356a9a8216257368cac2ff06b4a2
