### ISSUE TITLE
When you click the "Variables" node the variables panel should be made visible

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#455]
"Quick Actions" is shown instead. Fewer clicks would be necessary if "Variables" is automatically shown.

![imaxe](https://user-images.githubusercontent.com/24922404/156005965-2efbe252-d7c6-460c-bafb-11c322b57948.png)

**Comment by vchelaru** [comment]
Fixed

dd9546b05c6288d105e918aab4e713b1453a1e6c
