### ISSUE TITLE
Glue should update GameScreen lists on refactor

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#458]
I refactored an entity and Glue failed to update screen lists. I had to manually regenerate the `Generated.cs` file.

Steps:

1. Create a new entity (mine was a deriving entity if it matters)
1. Make sure to have Glue create a factory and a list of that type in the GameScreen
1. Run the game and make sure the screen contains the list
2. Rename the entity in the Glue Properties window
3. Attempt to run the game again, should get an error about the list type

Expected outcome: Glue refactors screen lists when refactoring an entity name
Actual outcome: Must manually regenerate screen code to trigger the update

**Comment by vchelaru** [comment]
Verified - this also happens if there are instances of that object in the GameScreen.

**Comment by vchelaru** [comment]
Also, Game1 should be re-generated to update factory event assignment.

**Comment by vchelaru** [comment]
f7bbe9f856fb33185fc062f3288a801789f223fe
