### ISSUE TITLE
Glue should not create multiple treeview items for code files

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#459]
![image](https://user-images.githubusercontent.com/711100/156210541-0d906c80-d912-4bdc-968d-72a67fb84950.png)

Repro steps:

1. Open your game screen's Code folder, right click, and regenerate the `.Generated.cs` file (this may not be required but was part of my steps)
2. Click on a list in the game screen's Objects folder
3. Press alt + up/down arrow to try to move the object up or down in the tree

**Expected result**: You can move Objects up and down in the tree view with alt + up/down
**Actual result**: Object does not move and Glue creates multiple treeview elements for each code file! These go away when Glue is restarted. No errors are thrown.

**Comment by vchelaru** [comment]
I tested and I believe this has been fixed. It was likely caused by the change to the searching functionality.

**Comment by profexorgeek** [comment]
I know this is closed but I rebuilt with latest and confirmed that the problem went away as well.
