### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by fractalV** [vchelaru/FlatRedBall#46]
Hi!
How to build FlatRedBall.ContentXna4 solution if Microsoft.Xna.GameStudio package is not compatible with Microsoft Windows [Version 10.0.19041.630]?

**Comment by vchelaru** [comment]
FlatRedBall XNA is in sunset mode - all new projects should be using FlatRedBall DesktoGL.

Old starter projects may be converted, or they can serve as a code example, but may not run if you do not have XNA installed on your machine.

Also, I wasn't aware that XNA isn't compatible with Windows - I thought it was last time I checked, and the download page has installation steps.
