### ISSUE TITLE
New wizard project sometimes doesn't include Level1 and Level2 gum projects

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#462]
This is inconsistent, possibly because it's not running in a task?

**Comment by Snorvarg** [comment]
It might be related; the Gum tool was not installed when it happened.

**Comment by Snorvarg** [comment]
I tested it with the Gum Tool installed: If I create a new project, the same settings, the Level1Gum and Level2Gum projects get created properly. Flatredball should install the Gum Tool as well?

**Comment by vchelaru** [comment]
I believe this has been fixed with the latest change. I'll create a new feature request card to add Gum as part of the FRBDK.zip file.

Fix:

f42ac585ce91142ce070d99fff3857768dd9b358
