### ISSUE TITLE
Properties panel should be the preferred panel for nodes like file, object or variable types

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#464]
![imaxe](https://user-images.githubusercontent.com/24922404/156766779-2ccb76f3-54cc-4dfb-8a74-566bee101a2c.png)

Well, I think this would be the most logical behavior instead of Glue relying on the last tab clicked because this is the way I usually work (with the "properties" panel)... But I might be wrong.

I also use the "variables" panel sometimes to be honest... Maybe just default to something other than the "Quick Actions" panel?

**Comment by vchelaru** [comment]
Added Properties as the default for Variables and Files
Added Variables for the Objects (this is quite common when working with the live edit)

58877accef1f61463151ee098db4e2acf33bd4f1
