### ISSUE TITLE
Creation of render targets in Glue should be documented

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#47]
I'm implementing a "fog of war" system in my game. I want white circles (where players are located) to be subtracted from a dark background and then overlaid on my game to obscure areas outside of a vision circle. This requires using a render target to perform the subtraction operation before overlaying it as a sprite.

I know that this is possible in code but, per our discussion, it's also possible in Glue but undocumented.

Documentation of this feature should exist.

**Comment by vchelaru** [comment]
This is not (yet) supported in Glue, but I did add a new object called RenderTargetSprite and documented it here:

https://flatredball.com/documentation/api/flatredball/flatredball-graphics/flatredball-graphics-texture/rendertargetsprite/
