### ISSUE TITLE
Gum Text MaxLettersToShow value of 0 should not show letters.

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#477]
If users set MaxLettersToShow to 0, they probably expect zero letters to show. In practice, a 0 value will show one character. This happens in both Gum the application and when set in bound ViewModels.

![image](https://user-images.githubusercontent.com/711100/157949803-bfc4984b-9ebd-45d1-a659-73c6051cdfde.png)

**Comment by vchelaru** [comment]
Note - this feature was added a while ago. Old projects didn't have this variable set, so when the property was added, old projects had a value of 0. Therefore, to be backwards compatible, Gum treated 0 as "no max letter limit". However, I agree that it should support a 0 value.

To solve this, we need to increment the GumProjectSave file version. If the file version is old, use 0 to mean "all letters". The new version will have a nullable value, where the default of null means to show all letters, and a non-null value indicates the actual number of letters.

**Comment by profexorgeek** [comment]
I don't think part of that is correct. If a zero value means "no max letter limit" then why does it show 1 character? If you are correct, it should show all of the characters. Additionally, the default value of the `Max Letters to Show` field in Gum is `<NULL>` which strongly implies that the file save already supports a nullable value.

The default `<NULL>` value shows all characters. If you change it to 0, it shows 1 character.

**Comment by profexorgeek** [comment]
Demo of the above point:

![gum-max-letters](https://user-images.githubusercontent.com/711100/158000820-d0b07ac8-ce11-4570-a7ad-0341bef0627f.gif)

**Comment by vchelaru** [comment]
Thanks for the extra info on that, you're right, I just assumed it was a nullable int thing, but turns out I was wrong. Or rather, the system was already implemented with a nullable int, so the problem was a logical bug. Fixed here:

755382bcb993158a52effdb5db99537be0a59b01 (Gum repo)

![12_08 32 23](https://user-images.githubusercontent.com/729631/158024418-fad34840-02d1-4fcc-b938-0db13fa61159.gif)
