### ISSUE TITLE
Gum NineSlice should not be misaligned at 100% scale

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#478]
![image](https://user-images.githubusercontent.com/711100/158022712-9a24550b-399b-4ade-93fd-86f501211028.png)

This repros 100% in WeeRPG, feel free to use my project to test. I don't think this is unique to my project unless this is something to do with the specific pixel size and rounding.

Repro steps:

1. Set scale to 100%
2. Start game
3. Create a character if you don't have one
4. Observe character left/right arrows once joined

Here are the Glue Camera settings for this behavior:
![image](https://user-images.githubusercontent.com/711100/158022795-34232799-0d86-4585-a226-d1b01bd2df96.png)

**Comment by vchelaru** [comment]
This may actually be fixed. Need to test to verify.
