### ISSUE TITLE
Glue, entity instance variables: unable to copy or paste values from or into input fields

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#479]
While trying to copy-paste values from one entity instance variable to another entity instance variable, it wasn't accepting the paste command (Ctrl+V). It seems that the copy (Ctrl+C) didn't work either. There was nothing in the clipboard. And, even when copying a number from elsewhere to ensure it ends up in the clipboard, it wouldn't paste into the variable field.

Here's the fields I'm referring to, in case it helps, though I'm wondering if this might be a more generic problem with the input fields.

![Screenshot of Glue showing the Variables tab with fields for X, Y, and Z.](https://user-images.githubusercontent.com/713665/158043784-a092bea4-9fc1-4598-a505-cee00e9bfa3a.png)

**Comment by vchelaru** [comment]
Fixed

c67d4b1249ea0278a6694de38efa3e1cabeab8f7
