### ISSUE TITLE
Possible to use ur Engine with new MonoGame 3.8 due to massive improvements?

### ISSUE THREAD

**Issue by Shpendicus** [vchelaru/FlatRedBall#48]
Title.

**Comment by vchelaru** [comment]
@Shpendicus what kind of "massive improvements" does 3.8 offer? I haven't tried using 3.8 but it might be a simple matter of replacing the .dlls in the Libraries folder. It may "just work". Have you encountered any problems with it?

**Comment by Shpendicus** [comment]
@vchelaru I still didnt come to the possibility to use it, i mean massive improvements of using netcore 3.1 LTS , easier Build process and full-NugetIntegration, and a handfull of fixes, so it is indeed kind of important improvement IMHO, i hope u are right for just replacing the .dlls

**Comment by vchelaru** [comment]
I see. Well, that is currently a larger effort. The Glue app has moved from .NET Framework 4.7 to .NET Core 3. Soon we will be adding templates that support FlatRedBall .NET Standard to simplify cross-platform projects.

So...it seems you're not specifically asking about 3.8 but rather .NET Core/Standard, and yes, this is in progress.

I would like to close this issue unless you have other questions about the current status.
