### ISSUE TITLE
Glue, entity list collision: unable to reset Subcollision selection

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#480]
While following along with the [platformer enemy movement tutorial](https://flatredball.com/documentation/tutorials/platformer-plugin/enemy-movement/03-enemy-input-logic/), I ran into something that confused me while setting up the enemy list vs. solid collision.

![Screenshot of Glue pulled from the tutorial, showing setting up a solid collision.](https://user-images.githubusercontent.com/713665/158044662-31271417-2943-4949-836a-03dc6d9f6f3c.png)

While working through the dialog, I clicked into the **Subcollision** drop-down list. But, once I did, I could no longer leave the selection empty as it the tutorial was asking.

My initial thought was that there needed to be some way to reset the field to default again. After talking on Discord, it sounds like the empty selection is the same as `<Entire Object>`. So, maybe it would be better if that value is selected by default.

**Comment by vchelaru** [comment]
Blank values and "<Entire Collision>" do mean the same thing. I've updated the behavior to help clarify this.

![image](https://user-images.githubusercontent.com/729631/158694309-a92c19f4-7765-4756-b079-89ef33879c6a.png)

91e3f1b793ae9d3bc7a0a5345b3a70b680b9a7a3
