### ISSUE TITLE
Glue scale (zoom) should work in 3D

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#484]
Note that I repro'd this with the camera in 2D and 3D mode.

Rolling the mouse wheel and clicking the buttons does not seem to scale anything:

![glue-no-scale](https://user-images.githubusercontent.com/711100/158291634-8b876b95-b3bf-4730-a290-053eaa1650f4.gif)

**Comment by profexorgeek** [comment]
UPDATE: this _does_ work in 2D. I was wrong. It just takes some time to rebuild after you change the camera mode. However, it does NOT work in 3D and it should.

**Comment by vchelaru** [comment]
Fixed

![16_10 39 05](https://user-images.githubusercontent.com/729631/158656939-42ea7cf2-5087-4bbb-8ab1-8221f9a2af7e.gif)

b36c7c6a563dde638cfa7723469d7a856ca6cee8
