### ISSUE TITLE
Refactoring variable names shouldn't cause errors

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#485]
Repro steps:

1. Create a simple entity with a sprite
2. Tunnel expose a variable on the sprite
3. Rename the variable
4. Go to an entity instance in a screen
5. Click the renamed variable (the name will show up correctly in properties)
6. Attempt to set value on the variable
7. Output window gets errors because the variable name is not properly refactored somewhere!

In this case I tunneled RotationZ but then renamed it to just Rotation. It shows up correctly in the UI but attempting to set a value throws errors:

![image](https://user-images.githubusercontent.com/711100/158291955-6938c635-0708-4108-9ac5-d8ab2e2b51ac.png)

**Comment by vchelaru** [comment]
Fixed
![15_17 06 20](https://user-images.githubusercontent.com/729631/158487216-c238d4c3-a1b0-4f76-89b6-0de7a026e394.gif)

38a99cb49301d0fdb24c219a8522c9a0e2d08637
