### ISSUE TITLE
flatredball.com: Tutorials sometimes nested visually

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#487]
![Screenshot of flatredball.com showing a tutorial entry nested within the prior tutorial entry's description block.](https://user-images.githubusercontent.com/713665/158298793-bd64ac89-ac41-49a5-ab72-b4e753263ba2.png)

https://flatredball.com/documentation/tutorials/

Depending on the browser screen width and the shortness of the prior tutorial's description, some tutorial entries are being displayed nested within the prior entry. This appears to be a result of the CSS-`float`ed image not being `clear`ed before the next tutorial entry. I'm not sure how best to resolve this in a way that is friendly to the visual editor, though.

**Comment by vchelaru** [comment]
Any thoughts on this @profexorgeek ?

**Comment by profexorgeek** [comment]
We can put CSS overrides in a theme file. Alternatively, we might just be able to structure these differently. I haven't looked at the page yet. Can you get the link into this issue so it's all in one place?

**Comment by patridge** [comment]
Sorry, totally spaced on that. Link is in the description now. (And [here](https://flatredball.com/documentation/tutorials/).)

**Comment by vchelaru** [comment]
This is fixed, or at least not a problem anymore now that we're on a new docs site.
