### ISSUE TITLE
Render targets should consider render scale

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#49]
Render target sprites attached to a game sprite do not consider the render scale, causing a parallax effect due to bad positions:

200% scale (incorrect)
![wee-fog-of-war1](https://user-images.githubusercontent.com/711100/102674256-a964a080-4152-11eb-9133-0b376f2a9d00.gif)

100% scale (expected behavior)
![wee-fog-of-war2](https://user-images.githubusercontent.com/711100/102674265-aff31800-4152-11eb-853c-48b25f8a2763.gif)

**Comment by vchelaru** [comment]
Fixed!
