### ISSUE TITLE
Editor background color should be configurable

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#495]
I'm working with some black sprites but I can't see anything because the sprite matches the background color:

![image](https://user-images.githubusercontent.com/711100/159106179-859b0068-282d-474f-9bdb-57b128653a82.png)

**Comment by vchelaru** [comment]
Fixed

29b467047fa734be5e4ee6cad43e6d13aa9d03b2

![25_14_53_43](https://user-images.githubusercontent.com/729631/160203498-b7d47e34-4e4b-4bbc-bacb-53f10602a650.gif)
