### ISSUE TITLE
Editor does not reload textures

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#496]
I created an Entity with some sprites. I made some edits to the sprites. The edits showed up in the Animation Editor (after switching chains) so I know the changes were propagated to the file.

The Editor never updated. I tried switching to a different entity and back but it still didn't pick up the changes.

**Comment by vchelaru** [comment]
@profexorgeek this one requires a little more info like - 

Where the textures part of GlobalContent? Or only part of the current Entity? If they were only part of the entity, is the entity marked as global? Is the current screen using global content? ARe you using XNBs? 

Can you get me more repro info here?

**Comment by profexorgeek** [comment]
Sorry, that was a poorly filed bug. I must have been in a hurry. Here's repro and gif:

1. Have all sprites loaded through the content pipeline as XNBs
2. Have animation chains mapped in an ACHX that's in global content
3. Create an entity that has a sprite who's texture is defined by a chain in the ACHX
4. Update the sprite
5. The editor preview will not update

I suspect it's probably the XNB rebuild that's not being picked up. It's acceptable to say "you can't dynamically reload XNBs" - the only reason I have content pipeline turned on is this is the same project where I was testing 3D models, which require it!

Gif:
![no-texture-update](https://user-images.githubusercontent.com/711100/159934899-952215d9-1398-4fcd-9945-02df1c9c2b91.gif)

**Comment by vchelaru** [comment]
Fixed

8ed78a1e5c5bcd65af0dc252695a1fb46d56097a

![25_11_52_07](https://user-images.githubusercontent.com/729631/160175513-439ee0dc-893d-49e9-a244-f7deef28f2c9.gif)
