### ISSUE TITLE
Copying an object to a new entity does not display and properties aren't correctly applied

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#497]
If you copy an object from one entity to another, it does not show up in the editor and properties, such as X, Y, Z, do not seem to be honored - even after a Glue restart.

Steps:

1. Create a new entity
2. Copy (drag) an object, such as a sprite instance from an existing entity to the new entity
3. Observe the new entity in the editor: the object does not exist in the editor
4. Restart Glue
5. The object now exists in the editor but its properties are not correct (not sure about this last part)

Gif:
![object-no-propagate](https://user-images.githubusercontent.com/711100/159106726-742ac6a8-8ae2-43e3-ae72-4379dcb9a027.gif)

**Comment by profexorgeek** [comment]
UPDATE: The properties part of this mentioned in Step 5 above are a separate problem. I tested and repro'd this and filed a separate issue here:
https://github.com/vchelaru/FlatRedBall/issues/498

**Comment by vchelaru** [comment]
Update - fixed the drag drop not showing up, but there's an error caused by missing file. Need to decide how to handle this.

![image](https://user-images.githubusercontent.com/729631/159736384-0dd360a1-cb88-4591-a469-c9465ffdb28f.png)

**Comment by vchelaru** [comment]
Fix #2 - the Sprite object now has its Texture using an editable ComboBox, which means incorrectly-set texture values will appear:

![image](https://user-images.githubusercontent.com/729631/159833039-7ffbfab8-9376-42ce-b669-35d21d8174a9.png)

There's more that could be done, like ask the user "do you want to bring the file over with the sprite?". Also, could show an error in the error window but...this feels like a rabbit hole, and I've already made a few improvements here, so let's see if others run into these problems before making more fixes.

The root bug has been solved.
