### ISSUE TITLE
Editor does not properly load and display X value for object instances

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#498]
This may affect more than just the X value but that's what I noticed and tested with. Repro:

1. Create an entity with a Sprite instance
2. Set the Sprite instance X value to a positive number
3. Close Glue
4. Restart Glue
5. Navigate to the Entity
6. Start the Editor preview
7. The Sprite X will not display correctly
8. Change the X value
9. It now displays correctly

Gif:
![no-save-x-value](https://user-images.githubusercontent.com/711100/159107208-24cb8157-c598-4eff-8718-4cc28fd56047.gif)

**Comment by vchelaru** [comment]
This is caused by the sprite being animated. Editor now shows you a warning:
![19_11_59_00](https://user-images.githubusercontent.com/729631/159133968-24150b84-36a5-421d-befe-9af246376ad3.gif)

Fixed: d8cd2d6d25da471c17cc47431def4e8c0deecdba
