### ISSUE TITLE
Gum should paste components into the selected item

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#502]
**Repro Steps:**

1. Create a Gum component with several internal objects of any type
2. Copy an object instance
3. Select another object
4. Paste the object instance
5. Observe that it does not paste into the selected object

Expected behavior: A copy of the object instance is pasted into the selected object as a child
Actual behavior: A copy of the object instance is pasted at the same level as the copied object instance

**Alt Repro Steps:**

1. Create two Gum components A and B
2. Select component A and copy
3. Select component B and paste

Expected behavior: An instance of A is pasted as a child of B (the selected object)
Actual behavior: Instance A is duplicated at the folder level and results in A1 being created as a new component

Gif:
![gum-wrong-paste](https://user-images.githubusercontent.com/711100/159131888-f6459536-046e-43f1-9aad-906195d2cd09.gif)

**Comment by vchelaru** [comment]
Fixed issue 1:

(gum commit)

0697298008977c7215a0504881050f1843ea4ef6
