### ISSUE TITLE
Unable to set Gum state in certain cases

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#503]
This is a complex edge case so I have a set of steps and a gif to help illustrate the problem.

**Context:**

1. I have a `IconButton` component intended to show button hints. It has states that set a button visual for most buttons across keyboard, mouse, and gamepad
2. I have an `AbilityDisplay` component that shows whether an ability (spell) exists, is ready, is disabled, or is recharging. This display can show a button hint that tells the player which button activates the ability
3. I have a `PlayerHud` component that will have a Gamepad and Keyboard state. If it is in Gamepad state, it will show gamepad button hints for the 4 potential abilities. If it is in Keyboard state, it will show keyboard button hints

**Problem:**

When I try to set the button state, it will not allow me to set 3 specific states on the ButtonIcon component. Repro steps...

Commit: https://github.com/profexorgeek/WeeRpg/commit/78e7fe004d6b5cdc9dc6b50de00c61ab3ad6e937

1. Open the `WeeComponents` > `PlayerHud`
2. Open the `ControllerCategory` state category
3. Select the `Keyboard` state
4. Select the `PlayerHud` > `AbilityContainer` > `Ability2` component
5. Attempt to set the `ButtonIcon` state on the `Ability2` component to `KeyA`, `KeyS`, or `KeyD`
6. Observe that the dropdown is blanked out and the state does not set
7. Any other state will work correctly but these three specific ones do not work for any of the `AbilityDisplay` component instances

Gif:
![unable-to-set-state](https://user-images.githubusercontent.com/711100/159399436-84584a6c-2311-4311-bf88-410ea547a303.gif)

**Comment by vchelaru** [comment]
Fixed. Very weird bug, I don't understand it, had to hack it.
