### ISSUE TITLE
Slider knob hitbox not accurate at edges

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#509]
First, this problem is arguably unique to my specific game and not a FRB/Gum issue. However, fixing this is hacky and also I just skinned the existing DefaultForms object so other people will have this same problem.

**Issue:**
The slider knob hitbox works as expected for middle values but at the extreme right value the hitbox is clipped. It appears to be clipped to the edge of its parent container. I suspect fixing this will require some interesting nesting to allow the knob to not be partially extended outside of its parent.

**Gif:**
![slider-hitbox](https://user-images.githubusercontent.com/711100/160889457-889e65a0-7652-49b8-af49-bc4740d459bf.gif)

**Comment by vchelaru** [comment]
This behavior is explained here:

https://flatredball.com/documentation/api/flatredball-forms/controls/slider/

See the **Using RaiseChildrenEventsOutsideOfBounds to Enable Grabbing the Thumb** section.
