### ISSUE TITLE
RGB Sliders shouldn't reset position

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#513]
Steps I took:

1. Created entity with sprite
2. Exposed sprites RGB as Red, Green, and Blue tunneled variables
3. Dragged entity into Level1 list of entity type
4. Attempted to set RGB values
5. RGB value sliders reset

Note that this was happening while Glue was also failing to embed game in Editor so not sure if that is causing problems.

Gif:
![rgb-sliders](https://user-images.githubusercontent.com/711100/161139021-b4fb031a-80ab-437d-af7a-16abc7ffc6af.gif)

**Comment by vchelaru** [comment]
This was a fix in the Gum repo

3c7d7442e328fb6086b8e5a700357d1b70db9237
