### ISSUE TITLE
Glue shouldn't crash the screen on unload

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#514]
I'm not sure the exact repro but I think this is it:

1. Be running Level01 (or whatever is NOT the game screen) in the editor
2. Add a circle to the GameScreen
3. Observe that it's also added to the editor
4. Take an action to trigger screen unload
5. An exception is thrown because the screen didn't clean up

I _think_ this is because of the circle being added in the base class but not properly cleaned up on unload.

![image](https://user-images.githubusercontent.com/711100/161142890-4f9da6db-b711-4904-aca3-89a3920696cb.png)

**Comment by vchelaru** [comment]
Could not reproduce.
