### ISSUE TITLE
Fix bitmap png references

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#517]
From Tristan (Victris games):

https://flatredball.com/documentation/api/flatredball/flatredball-graphics/flatredball-graphics-bitmapfont/
[FlatRedBall](https://flatredball.com/)
[Vic Chelaru](https://flatredball.com/author/vicchelaru/)
[BitmapFont](https://flatredball.com/documentation/api/flatredball/flatredball-graphics/flatredball-graphics-bitmapfont/)
Both links point to the .fnt file, but people also need the "font18arial_0.png"
This is the right URL:
https://files.flatredball.com/content/Tutorials/Graphics/font18arial_0.png

**Comment by zdman2022** [comment]
I don't have access.  I'm missing an edit page option.

![image](https://user-images.githubusercontent.com/1099520/172986531-d5279464-efdd-4b40-b4c9-75161fe6f907.png)

![image](https://user-images.githubusercontent.com/1099520/172986628-ee227b65-df6f-4aed-856b-6a6b7b817d42.png)

**Comment by zdman2022** [comment]
Fixed the link.
