### ISSUE TITLE
Move up/down should work when there are only two layers

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#52]
You can't reorder layers using alt + up/down or by right clicking and choosing move up/down when there are only two layers. Move to top works.

Repro:
1. Create two layers in a screen
2. Choose the last layer in the list and press alt+up
3. Layers do not reorder

**Comment by vchelaru** [comment]
I believe this actually happens because the reordering happens at the level of all objects in a list, even though visually the layers should only sort with themselves. The same problem occurs with CollisionRelationships and objects outside of the sub-folders.

**Comment by vchelaru** [comment]
Fixed.
