### ISSUE TITLE
New variable dialog is shown outside of the screen bounds

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#522]
After clicking the "Add variable" item:

![imaxe](https://user-images.githubusercontent.com/24922404/161542957-0d154bec-9ded-4d42-85d5-05450c117721.png)

The new window is shown like this:

![imaxe](https://user-images.githubusercontent.com/24922404/161542746-38c604d1-952f-4f4c-bcb0-8a4e261cb382.png)

**Comment by vchelaru** [comment]
Fixed

71c6bb128f87353ec253f7307d645f1b28dec7b4

![06_22 29 52](https://user-images.githubusercontent.com/729631/162120390-b963df5f-e9a7-40d3-a924-9507171bbaa5.gif)
