### ISSUE TITLE
Gum Forms TextBox control should have placeholder property

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#532]
The TextBox control in FRB Forms should have a Placeholder text element and an associated property that are separate from the actual user input. This text should show when no text is entered and the box is unfocused. If the box is focused, the cursor should appear and the placeholder text should disappear. The placeholder text should never be bound to user input.

This makes it easier for developers to implement field hints and is a common feature in other UI systems.

**Comment by vchelaru** [comment]
WPF doesn't provide this, but Xamarin.Forms does, so we'll follow that pattern. The property is Placeholder.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry#set-placeholder-text

**Comment by vchelaru** [comment]
Fixed

![11_08 30 12](https://user-images.githubusercontent.com/729631/167874876-59f36f45-e6fe-48a9-8921-af158f1b145c.gif)

079a56fa3a771335dd1ab3d055b8ddab09fc1d7c
