### ISSUE TITLE
Engine doing per-frame memory allocations

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#539]
While doing some optimization work to avoid a slowdown in my game I decided to take a look at memory allocations using CLRProfiler. In the end my frame drops where not caused by this -and the issue was subsecuently fixed- but I found out the engine was doing every-frame memory allocations.

In particular the engine was leaking IEnumerables:
![imaxe](https://user-images.githubusercontent.com/24922404/165335341-fb1362f6-0d06-43fc-bcce-a2d8627fb5dd.png)

These every-frame leaks seem to come from the CollisionManager:
![imaxe](https://user-images.githubusercontent.com/24922404/165335832-630c7a9b-6a1e-4f4a-969e-1fb1dbacf9e7.png)

Also, there are IEnumerable leaks while updating Gum components layout:
![imaxe](https://user-images.githubusercontent.com/24922404/165336443-183e3631-17ec-41ea-9dea-7c2af1abba7e.png)

Maybe I'm being a little paranoid but I pooled all my entities and gameplay allocations are residual. I think it would be best if the engine ran allocation-free during gameplay if possible, specially for games which use heavy collision checking I imagine it could be a problem if the garbage collector kicks in frecuently.

**Comment by vchelaru** [comment]
Thanks for researching this. I think this is a good thing for me to fix, so I will remove the Low Priority tag.

**Comment by mfigueirido** [comment]
Nice. If you need some testing let me know :)

**Comment by vchelaru** [comment]
CollisionRelationship Partition foreach allocation has been fixed:

077f1a4311bd9627249fc0f0e1986b24ec42d7c5

Still need to do Gum

**Comment by vchelaru** [comment]
Fixed Gum GraphicalUiElement to not allocate. Note that this is a Gum repository fix:

cd1591a2a02eb50e2218161cda25b191c13cb95c
