### ISSUE TITLE
TextBox cursor should properly react to whitespace

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#54]
**Repro steps:**

1. Add a Gum object containing a Forms text box to a Gum screen
2. Build and run the game screen
3. Focus the text box and enter several space characters
4. Enter some other characters
5. Note that the cursor and text box do not properly render whitespace

**Expected behavior:**
Entering whitespace into a textbox should preview correctly with the cursor being offset by the spaces.

**Actual behavior:**
The cursor and spacing renders incorrectly.

Gif:
![gum-whitespace-issue](https://user-images.githubusercontent.com/711100/102724018-932d2080-42c9-11eb-8c98-23f097526564.gif)

I filed this in the FRB repo and not the Gum repo because this is a runtime issue and not an issue with the Gum application.

**Comment by vchelaru** [comment]
Note, this requires space being the very first character entered. If the first character is non-space, then all renders okay.

**Comment by vchelaru** [comment]
Fixed. This is a Gum change, not FRB change.
