### ISSUE TITLE
Add CollideAgainstClosest function to ShapeCollection vs Line

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#545]
As talked in the Discoord room it would be needed in order to support scenarios like this one when the collision list is a ShapeCollection and the closest point needs to be provided.

![imaxe](https://user-images.githubusercontent.com/24922404/165782477-3b1a10bf-f90b-417e-9f75-3de431e5618d.png)

**Comment by vchelaru** [comment]
Fixed

fcdc327ca25191c5594a66dc265fae68c61d8f79
