### ISSUE TITLE
Add rectangle support per frame in .achx file

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#548]
## Motivation

Often times entities change size as they play animations, such as a character standing tall vs ducking. In these situations the collision should change, and it's easiest to define the collision when creating the animation chains since the AnimationEditor lets you see the animations visually.

Rectangle definitions and rectangle editing in .achx would enable the definition of shapes through .achx files.

## One vs Many

Should the .achx support just one rectangle? Or many? Supporting just one makes it easier to deal with conceptually. In FRB Editor we could have a rectangle use the .achx as its source, and leave it at that.

However, some games may need multiple hit boxes. For example, games like Mega Man X3 include Zero who can swing a sword. When swinging the sword, the hit box of the sword depends on the swinging animation.

![image](https://user-images.githubusercontent.com/729631/166109191-b332f25b-773d-418a-baf6-c719f3014cc6.png)

To support this case, the .achx should have multiple rectangle support.

When referencing rectangles in FRB Editor/Code, the user should be able to get the rectangle by name. By default, new rectangles should get the name "Default".

## Creating/Editing Rectangles

Each frame can be expanded. Right-clicking on the frame provides a new option "Add Rectangle". Clicking this option adds a new rectangle which will match the size of the frame.

The rectangle can be selected in the tree view, and it will highlight in the editor window and will have handles for moving/resizing.

Copy/paste is important, both within the same frame, and also inbetween frames. Copy/paste frames which contain rectangles should paste all contained rectangles.

## FRB Editor Behavior

Rectangles in FRB Editor will support having a SourceType of File and a SourceObject being one of the names in the .achx. The animation plugin needs to provide all available names.

When a frame changes, the rectangle needs to update (how?). Will this be in codegen? There's no manager to handle this purely in code, but maybe there should be? Need to think on this...

I think it probably should be in codegen since we don't want to complicate things with a new editor. 

If there is no rectangle as part of a frame, then the rectangle will not be updated. This could result in old frames lingering, but rectangles cannot be "deactivated" so this is the easiest solution.

## What about Polygons?

In the future we may also want to support polygon editing in .achx for more complex hit boxes (think of Smash Bros). Create the file format to support this system.

**Comment by mfigueirido** [comment]
We've hit this problem in our game and solved it by making some ugly looking shape transformations in code based on the entities state. I think this would be a good way to solve it, the only extra thing I see could be nice to have is the support for circles or capsules. In some scenarios it could be better to have something without edges to do collisions against the level (for example with this kind of collision it's harder for a pathfinding AI to get stuck somewhere in the level). I would support many shapes (just one is too optimistic) and the user should be able to select which type.

**Comment by vchelaru** [comment]
Yea, I think I'll want to have the .achx file allow each frame to have its own complete ShapeCollection, so that will provide the ability for all shapes in the future, and also enable other modifications like perhaps you want to change the color of shapes for debug mode, etc. 

Initially, the editor itself might only support a very small subset of the features allowed in a ShapeCollection, but the file format will be built to handle everything.

**Comment by vchelaru** [comment]
Work started in branch 

https://github.com/vchelaru/FlatRedBall/tree/AchxShapes

**Comment by vchelaru** [comment]
Update - currently the AnimationEditor uses FRB XNA, which no longer opens in VS 2022. While this could be worked around for a  while, it may be time to introduce a SkiaGum solution. SkiaGum may also be needed in Glue, so it's worthwile to consider that here.

For reference/discussion about SkiaGum:

https://github.com/vchelaru/FlatRedBall/issues/494

Actually....this means I'd have to rewrite the entire wireframe system which is no good. Maybe it's best to try out the wpf + monogame

Update - the AnimationEditor needs to be more like Glue in its architecture to make these things easier. That is:

* Use AppCommands and AppState rather than directly interacting with objects like the Wireframe Manager. This allows the Wireframe Manager to be swapped out easily
* Create tabs for the different components
* Move the creation of objects out of the winforms visual editor and instead do it in separate objects that add themselves
* Create new project that uses WPF + monogame

This is an incremental process so we'll stick with XNA for now and keep using VS 2019.

**Comment by vchelaru** [comment]
This is implemented, but as of this writing, is still in the AchxShapes branch.

966c0eb67ed24461732ec22cace6de5964defc63

To use this, the user can add shapes to the AnimationEditor. The easiest way to use this is to add the following code to an entity which is both an ICollidable (has Collision ShapeCollection) and also has an animated Sprite:

```
private void CustomActivity()
{
    if(SpriteInstance.JustChangedFrame)
    {
        SpriteInstance.CurrentFrame?.ShapeCollectionSave?.SetValuesOn(this.Collision, this, true);
        // optional if you want to see the shapes update immediately visually:

        this.ForceUpdateDependenciesDeep();
        this.Collision.Visible = true;
    }
}
```

## Note about using XNA vs WPF

In the end I decided to stick with XNA + Winforms for now. To migrate to something like WPF, we'd want to first have the AnimationEditor separate out the rendering window the way Glue has its tabs separated into plugins. I've started this migration by adding AppCommands and AppState similar to GlueCommands and GlueState. This will be a gradual process, and it will either be completed incrementally or whenever VS 2019 is too difficult to find.
