### ISSUE TITLE
Double click on code file nodes should open the file in VS

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#553]
![imaxe](https://user-images.githubusercontent.com/24922404/166906759-a1b32cd0-a4f8-4c5b-b383-cf864baf4566.png)

This way it's faster when you need access the code when you are using the tree view rather than having to go back to Visual Studio and search for the file there.

**Comment by vchelaru** [comment]
This was actually a bug caused by the new tree view.  Fixed

3599f313dbdd574bf1b258767da12bafd3d1a0ba
