### ISSUE TITLE
Right click menu item for quick access to entity/screen code

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#554]
![imaxe](https://user-images.githubusercontent.com/24922404/166907838-f04587ab-0a02-43a4-9c2c-93e6a85659ca.png)

Adding a menu item to the right click menu in the entity/screen node to open "EntityXX.cs" or "ScreenXX.cs" files in Visual Studio would enable faster access to code files.

**Comment by vchelaru** [comment]
Added 

8357f17377a8249b85abf963d18a03b2e5db39a0
![05_08 42 15](https://user-images.githubusercontent.com/729631/166949075-8dbaeba3-abaf-4dce-8232-e078e222d3dc.gif)
