### ISSUE TITLE
Glue tells the user the there is no Windows association with the file but there is

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#555]
When double clicking a png file this window shows up:
![imaxe](https://user-images.githubusercontent.com/24922404/167134887-42f654c8-6a37-4256-ad36-5722e7de7d80.png)

But there is a Windows association with that file, in fact, after clicking "yes" no file association dialog is shown and the file is opened normally with the "Photos" Windows app.
![imaxe](https://user-images.githubusercontent.com/24922404/167135542-f8821529-1f18-4f2a-b7a7-c7fa2d262ae7.png)

**Comment by vchelaru** [comment]
Update - this is caused by the fact that there is no specific program set to open PNGs, so Windows falls back to the default Photos app.

Need to research how to suppress this dialog if Windows knows how to natively handle a file...

**Comment by vchelaru** [comment]
Fixed

38ca8a2e8e9edf7b2614c22b7d2044c512c789ed
