### ISSUE TITLE
Create wildcard file icon

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#556]
Wildcard files in FRB have a few differences from normal files. Also, since you are not explicitly adding them to FRB, it's useful to know if they have been picked by the editor.

I've created a new icon for them:

![image](https://user-images.githubusercontent.com/729631/167312358-54272e52-460a-4ade-a883-ec33dad287d2.png)

If you want to reference it or replace it, it's in the WildcardRfs branch of FlatRedBall, made in this commit:

3c6d7f3a27172e91092dc72efa8ea2a3df2159aa

Relative path: `FRBDK\Glue\OfficialPlugins\TreeViewPlugin\Content\icon_file_wildcard.png`
![icon_file_wildcard](https://user-images.githubusercontent.com/729631/167312411-a11c5457-0b24-428b-b386-8fc6c8c4c39b.png)

**Comment by profexorgeek** [comment]
@vchelaru  Your file looks fine but I want all of the icons that are in use to exist in the FRB Media repo so I created a similar one there in the appropriate src files. Switching to mine is up to you. The difference is small.
