### ISSUE TITLE
Glue should delete events when a collision relationship is deleted

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#56]
Repro:

1. Create a collision relationship
2. Create an event from the collision relationship
3. Delete the relationship
4. Event is not deleted

Glue should delete the event in Glue but not the actual custom code.

**Comment by vchelaru** [comment]
I could not reproduce this.

![2020_December_24_120010](https://user-images.githubusercontent.com/729631/103103812-fa581700-45e0-11eb-9026-bc95b112a2ef.gif)
