### ISSUE TITLE
Reload screen when LocalizationDatabase.csv changes

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#561]
I'm adding/modifying some localization strings inside LocalizationDatabase.csv and for them to be available I need to stop the game and restart it manually. I expect the game to reload when these files change on disk, not only the TMX.

I understand this option only reloads screen related content:
![imaxe](https://user-images.githubusercontent.com/24922404/168260615-4b66a015-934c-4da9-ac23-639b07524217.png)

Maybe another option to reload when global files are changed could be a good addition.

**Comment by vchelaru** [comment]
I have added this, but it is currently only if the game is in 'edit mode'. Are you doing this in edit mode, or do you need tit to happen even if in "normal" game running mode?

**Comment by mfigueirido** [comment]
Yes, it would need to reload the game on regular running mode the same way it works for TMX in the option explicited above.

**Comment by vchelaru** [comment]
Okay, I just tested everything and it works, including if the game is running (if you have that option checked)

a1f159dd974a1af78bc335aa5c5f850a7e25163d
