### ISSUE TITLE
Wildcard files feature doesn't add files deep into the file system

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#563]
Inside this folder I want the .achx and the .png added to Glue:
![imaxe](https://user-images.githubusercontent.com/24922404/168578845-d9e101b2-5422-419c-a62f-cc44d5da42e2.png)

So I add this wildcards to the .gluj file:

    {
      "Name": "GlobalContent/Resources/**/*.achx",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": [],
      "IncludeDirectoryRelativeToContainer": true
    },
    {
      "Name": "GlobalContent/Resources/**/spritesheet.png",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": [],
      "IncludeDirectoryRelativeToContainer": true
    },

And this is the result, the files weren't added:
![imaxe](https://user-images.githubusercontent.com/24922404/168579509-c2b801f8-5821-4216-a2d9-0cd5a3cea523.png)

This seems to be a problem which happens when the recursive function reaches a deeper folder level.

**Comment by mfigueirido** [comment]
I have fixed it in af48731a7da4c0ac31bc81db98ad8175b1b23ce2.
@vchelaru, I don't know if this could break something else. It looks good to me.

**Comment by vchelaru** [comment]
Big thanks! I tested it with a large subfolder structure and all is working well
