### ISSUE TITLE
Long startup times again after adding all the game's content to Glue

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#564]
After adding wildcard files to Glue and having everything managed from the app the startup times have worsened again. This is the output after the application becomes responsive, the total time is longer that this (including the loader window time):
[output.txt](https://github.com/vchelaru/FlatRedBall/files/8702149/output.txt)

This is problematic since the game will get even bigger. Maybe there's a way to check if the content file didn't change and skip it?

**Comment by vchelaru** [comment]
I was able to reproduce this by creating a large project as well. In my case, the loading process took 29.34 seconds before the UI was responsive.

I believe I can make this faster...

**Comment by vchelaru** [comment]
First pass on improvements, reduced it to 24.19 seconds. Not great, but it's a start...

80ed5d8f3b121e248a5d6663f904086a9c84cbd4

I can definitely do more!

**Comment by vchelaru** [comment]
Improved to 18.10 seconds.

a274045ab77537fed94d6b2b587e3b3072ab89e0

I think this can be improved even more...

**Comment by vchelaru** [comment]
Improved to 9.11 seconds.

1df3d65ca9b66e4a76f3d5832906d376273721ee

Still working on it...

**Comment by vchelaru** [comment]
Getting there! Improved to 5.64 seconds.

5c6e2ba6e0bae5b470f4c2cd720a69ad8048b1f5

I may be able to go a little faster..

**Comment by vchelaru** [comment]
4.13 seconds. Probably not going to get much faster than this for now, would take some seriously deep optimization and this may be fast enough for now? Let me know @mfigueirido 

If not, we may need to work together on diagnosing the performance issues. I used a project with > 1000 wildcard files and was able to get these improvements. Let me know how it goes for you.

bc44069e1fd956c5107d3eabbe006c1c7cf34b5b

**Comment by mfigueirido** [comment]
Done tests on our project and load times were reduced to around 22 seconds including loader screen time! 6 seconds loader, 16 seconds tasks in-app. It was almost two minutes before...

Startup times are good for now. Thanks.
