### ISSUE TITLE
After the latest performance improvements FRB Editor gets stuck after pressing F5

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#566]
It happens every time on my computer. Pressing the play button works fine.

Sometimes it would get unstuck after trying to kill the app and this shows up:
![imaxe](https://user-images.githubusercontent.com/24922404/169325527-259ec05a-7cc4-43f8-be44-d14f4cbd3941.png)

**Comment by vchelaru** [comment]
I am unable to reproduce this problem on my machine using the Wee RPG game (which is a fairly large game). Of course, I do have a desktop with a SSD so maybe it will reproduce on slower machines? 

@mfigueirido if you have time maybe we can work together debugging to figure out the problem?

**Comment by vchelaru** [comment]
Fixed.

7b363de399c26428eff6bf150f37228633197345
