### ISSUE TITLE
Null ref when adding Level1 screen as part of Tiled tutorial

### ISSUE THREAD

**Issue by Megacannon** [vchelaru/FlatRedBall#567]
I'm following the Tiled tutorial, but I get a null ref when trying to add the Level1 screen.

Steps I'm following are on this page under the "Adding Level1 Screen" heading

https://flatredball.com/documentation/tools/tiled-plugin/using-the-tiled-plugin/02-creating-a-gamescreen/

I've attached screenshots of the settings used for each phase of adding the screen as well as the final exception details.  For what it's worth, it _does_ ultimately create the screen--it's there once I restart and load the project again.  It just has to crash first.
![2022-05-20 13_08_51-Window](https://user-images.githubusercontent.com/3453242/169578464-9435b930-7394-4a9c-9fa6-8704db9357f8.png)
![2022-05-20 13_02_38-Window](https://user-images.githubusercontent.com/3453242/169577669-28ffeb8b-bef3-4fcf-8b08-6b85b663743e.png)
![2022-05-20 13_02_49-Window](https://user-images.githubusercontent.com/3453242/169577667-02fb7ec9-7bb8-4c5d-b4d4-8bc7b8aad51d.png)

**Comment by vchelaru** [comment]
Thanks for reporting this! I believe this was fixed just a few days ago, but it didn't get picked up in the last build.

2c31d52cf0f09db0a0f4f39a93f981766136d010

I have kicked off a build just now and will be finished in just a few minutes. After it is done, you can re-download the FRBDK.zip from the website's download page and unzip it. Be sure to remove the old unzipped folder to avoid picking the wrong version.

https://flatredball.com/download/
