### ISSUE TITLE
Glue should generate clearer errors if TMX is not sane

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#57]
I forgot to create a layer called "Gameplay" in a new map. A null ref exception occurs because the Generated code just expects this layer to exist. Instead, it should throw a clearer exception if the expected layer doesn't exist to give devs a clearer idea of what went wrong:

Here's the generated code passing the results of `FindByName` which are null:
![image](https://user-images.githubusercontent.com/711100/103157148-46d05d80-476d-11eb-9d40-e2500820639f.png)

**Comment by profexorgeek** [comment]
It turns out the `GameplayLayer` actually exists, it just doesn't have any tiles. Either way, there should be more explicit checks/errors here.

**Comment by vchelaru** [comment]
The bug was ultimately that empty Layers in TMX's would not generate layer objects at runtime. Now they do.
