### ISSUE TITLE
Glue Editor should show mouse coords

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#575]
There are things that Glue just won't be able to display correctly and you need to set X and Y for an invisible item. Or times when you want to verify what you're seeing by checking coordinates. Glue should show the mouse coordinates based on current entity 0,0 at Z = 0 (if camera is 3d)

In this specific case, I have created an emitter but Glue can't show me a preview for some reason. I don't want to run the game over and over while nudging the emitter coordinates to get it right. If I could just mouse over the spot I want, I could likely get the coordinate offset right on the first try.

![image](https://user-images.githubusercontent.com/711100/170149094-e63898d7-affd-477f-8dda-b844ef59b5ca.png)

**Comment by vchelaru** [comment]
This is problematic because it requires the game to continually send commands back to Glue. While possible it can be noisy. Right now there is a ruler on right-click so maybe the ruler should display the current location on right click?

**Comment by profexorgeek** [comment]
That seems like a reasonable workaround.

**Comment by vchelaru** [comment]
![29_13 16 39](https://user-images.githubusercontent.com/729631/181830257-b1803eac-6f23-46cb-9748-0afa6ec6460a.gif)


be0c0faa49e6139a56e50e5d4f8fdb18a1cefb05
