### ISSUE TITLE
[Docs] Typo in circle collision tutorial

### ISSUE THREAD

**Issue by njwest** [vchelaru/FlatRedBall#58]
Thanks for the great tutorials! I used your [Circle Collision tutorial](https://flatredball.com/documentation/tutorials/math/circle-collision/) while resolving some circle collisions in another language.

There is a not insignificant typo in an example code snippet, however, at the very end of the `Circle Move Collision` section:

```
circle2.X += (float)(System.Math.Cos(angle) * distanceToMove);
circle2.Y += (float)(System.Math.Cos(angle) * distanceToMove);
```

circle2.Y should use sine rather than cosine:

```
circle2.Y += (float)(System.Math.Sin(angle) * distanceToMove);
```

**Comment by vchelaru** [comment]
Thanks. Fixed.
