### ISSUE TITLE
Rename add row button on top down movement table.

### ISSUE THREAD

**Issue by dantogno** [vchelaru/FlatRedBall#580]
Instead of "Add control values" I propose "Add movement type" (that matches the language used for the table rows.).

**Comment by vchelaru** [comment]
Fixed

![image](https://user-images.githubusercontent.com/729631/172073532-4492a865-943f-4202-8ae2-fed3fa20014f.png)


40adaf78b9d36f888e71ebdb40200c7dd6e60126
