### ISSUE TITLE
Setting a background color in Glue shouldn't break editor visuals

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#583]
In this image the editor appears to be working but no visuals can be seen:

![image](https://user-images.githubusercontent.com/711100/171653715-dda2d43e-5d8e-4c54-a09d-af27a0a70e5e.png)

Turning off the background color fixes this problem.

**Comment by vchelaru** [comment]
This was caused by a recent change to EditorVisuals which made the default Layer the AboveAll layer. The background drawing code used EditorVisuals.Sprite, which placed the sprite above everything else.

c5b543c6cbdf8fc22b3f336ef7dbeaf85307e203
