### ISSUE TITLE
New pathing system should clean up debug visualizations

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#59]
If you enable debug visualizations for the new top down pathing system, it doesn't clean up the lines causing a crash on screen unload. Repro:

1) Create a top down entity and node-network TMX
2) Implement node traversal using new pathing system
3) Turn on line visualizations
4) Navigate away from screen while lines are visible
5) Screen will crash because lines aren't cleaned up

**Comment by vchelaru** [comment]
Line visualization is being turned on in custom code, so they must be turned off in custom code. 

@profexorgeek
