### ISSUE TITLE
Exposing sprite color to the editor should be less awkward

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#591]
Colorizing sprites is likely to be a common operation in the editor. However, to change the color of a sprite you must tunnel the RGB channels individually and they appear as sliders with values of 0 - 1.

CRITICAL - As an artist I would expect:

- RGB channels to be 0 - 255, not 0 - 1, so I can use values from any graphics program
- Alpha channel to be 0 - 1
- To be able to paste a hex color as a string and have it parse to RGB channel values

OPTIONAL - As a dev I would expect:

- To expose Sprite color more easily than tunneling the R, G, and B channels separately for every Sprite.

![image](https://user-images.githubusercontent.com/711100/172875296-cfa8a360-f4ed-4b4f-8c63-17ef7e57dcb7.png)

**Comment by vchelaru** [comment]
Progress

![image](https://user-images.githubusercontent.com/729631/173250275-70434570-0e6f-4400-a0c8-17b5dc98490c.png)

**Comment by vchelaru** [comment]
There's (currently) no way to tunnel all variables at once, but there's now a shortcut menu which cuts the number of clicks by quite a bit.
![wz0NQmcdOG](https://user-images.githubusercontent.com/729631/175206624-f5c214b3-50ce-4da8-a7f5-cd6ec3754fca.gif)

I'm closing this issue, but if specific improvements are still needed please re-open or create a new issue.
0fe267d0f6cf890f6d025a8069c7a2ce9fe282a8
