### ISSUE TITLE
FRB.Forms should include a virtual keyboard object

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#60]
Not sure exactly how this should work but some potential requirements:

- [ ] Keyboard should be isolated from other UI such as an input dialog
- [ ] Keyboard should be shareable across UI components that can accept text input
- [ ] Keyboard should be skinnable
- [ ] Keyboard should support basic punctuation used for game input. Suggestion: `.,!?-_$@'`
- [ ] Keyboard should support moving cursor between characters
- [ ] Keyboard should support space character
- [ ] Keyboard should support backspace
- [ ] Keyboard should support "Complete Input" which returns focus to the UI control

**Comment by vchelaru** [comment]
I believe this will do it @profexorgeek :
https://flatredball.com/documentation/api/flatredball-forms/controls/games/onscreenkeyboard/
