### ISSUE TITLE
AnimationEditor copy/paste should copy/paste the right chain

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#61]
Repro steps:

1. Create some animation chains
2. Multi-select several chains and delete
3. Attempt to copy/paste using keyboard shortcuts
4. Windows system plays "you did a bad thing" noise
5. No chains are pasted or the wrong chain is pasted

![copy-paste-fail](https://user-images.githubusercontent.com/711100/108603113-44e8dc00-7363-11eb-8323-600f6c3dbf1d.gif)

**Comment by vchelaru** [comment]
I believe CTRL+C / CTRL+V were never implemented. I implemented it now. Let me know if this fixes it @profexorgeek
