### ISSUE TITLE
Destructive actions should have cancel option in Glue

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#614]
If I accidentally change the value for something like SetByDerived, I'm given several options.

But there's no option to cancel the action entirely. Because of this, it's also unclear what the close button does. I would expect it to cancel the action but I don't know what "damage" it did to my deriving entities.

All dialogs like this should have a cancel button that returns the field to its original value and the close button should perform the same action.

**Comment by vchelaru** [comment]
Fixed
![09_13 09 30](https://user-images.githubusercontent.com/729631/178119591-172404bb-e931-458d-9feb-f1374bab789c.gif)

2265770d1af5bbe3871ea20768e5757c237c1fa1
