### ISSUE TITLE
Editor should allow locking entities to prevent accidental selection and drag

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#616]
- [x] Entities should be lockable
- [x] Entity can still be selected in tree view
- [x] Locking entity disallows selection in the game view
- [x] Can drag entity when manually selecting in treeview
- [ ] Locked entities have colored (red?) selection box when selected in treeview to remind that they are locked

**Comment by vchelaru** [comment]
Mostly fixed, still need to have a red selection.

d0254209c94f7a9cb39c83dd3a19645b4d7f3bbc
![28_09 51 26](https://user-images.githubusercontent.com/729631/176224937-fcafdbd9-99dc-4279-90c3-b22ea6117fe8.gif)

**Comment by vchelaru** [comment]
Spoke to @profexorgeek about the last issue (highlight color) and we decided to postpone this until the new feature is used and we see if it's really needed.
