### ISSUE TITLE
Typed list should show type

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#619]
This dialog is confusing. I forgot it was a typed list and couldn't figure out why I couldn't select the Sprite type:

![image](https://user-images.githubusercontent.com/711100/175829147-1d2ba53c-25e0-4061-9a04-51bb7a85ced4.png)

**Comment by vchelaru** [comment]
Update - currently the new object window has multiple problems:

1. All types are shown but the list box is disabled and the selected type is not scrolled. This means that the type that is being created is not obvious.
2. If the user selects a List of base entity types, the user should be able to add an instance of a derived entity, but this window does not allow that.

The solution is - the list should never be disabled, but the types should be filtered down to the appropriate types.

**Comment by vchelaru** [comment]
Fixed

09a9c997e4f1d788c5ed512d0354c22e5b6d5d34
