### ISSUE TITLE
Editor handles shouldn't.... do this

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#620]
Not sure how to describe. Pull MasteroidRedeaux and examine ComponentTube to see repro. I suspect it's related to the sprite having relative velocity
![editor-handles](https://user-images.githubusercontent.com/711100/175831901-1ad755cc-f638-44fc-8ed5-a8f3287de5ab.gif)
.

**Comment by vchelaru** [comment]
This happens on resizable objects with Z!=0. Fixed

9982df12e68eed81f08c9ec42e67cf213d54bd8a
