### ISSUE TITLE
Copy, Paste, and Stamp should behave more like mainstream graphic tools

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#623]
The editor's current copy/paste implementation has some issues, the main one being that it's hard to copy and paste multiple instances without moving an instance that might already be placed and named. The editor should have this behavior:

- [x] Copy should copy the currently selected object(s?)
- [x] Paste should paste a clone of the copied object with [0,0] at the mouse cursor
- [x] If multiple objects are selected, [0,0] is the average position of their origins
- [x] Pressing paste repeatedly should continually paste a clone of the original copied object at the mouse cursor
- [x] STRETCH GOAL: copy/paste should work between levels
- [ ] ~Holding a modifier key* BEFORE you start dragging results in a cloned object being created and dragging with the cursor until released (see gif)~

\* Adobe uses ALT as this modifier. Windows and other programs sometimes use CTRL.

Demo, notice the cursor changes when you press alt to indicate that you will be duplicating the dragged object:
![alt-drag](https://user-images.githubusercontent.com/711100/176475406-18201967-ab19-45f1-99e5-26508596fd2c.gif)

**Comment by vchelaru** [comment]
The current copy paste implementation suffers from poor performance. A copy/paste of a group of objects in a large game (such as BCBombers) can take multiple seconds which really hurts the usability. I'm spending some time to make this run faster.

**Comment by profexorgeek** [comment]
As we discussed, copying large groups of objects can take some time in the editor. So, holding a modifier key ends up having inconsistent performance and is a worse experience than not having it. The other requirements provide suitable capabilities that make this less valuable anyway so I marked that requirement as crossed out. We'll leave it in here for reference though!

**Comment by vchelaru** [comment]
Fixed

bc84ff6b0e109cb89d05d0d520742544cc40d9b5
