### ISSUE TITLE
AnimationEditor should not crash with sprite batch error

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#626]
No clear repro here. I saved a file in photoshop and then renamed an animation chain, possibly while the file was still in process of saving.

Error:
![image](https://user-images.githubusercontent.com/711100/176583804-88ff1bef-b817-4b0d-b719-138c3f16d939.png)

**Comment by vchelaru** [comment]
Unfortunately this is definitely not something that can be solved with just the callstack. I know I asked for this, but I don't think this will help. Going to close it until we get a good repro.
