### ISSUE TITLE
Polygons should be easier to manipulate

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#634]
These are improvements to polygon manipulation that Glue should support, in order of priority and "resolution". Meaning that each of these builds on the last to create the ideal workflow but can be implemented one-at-a-time. Feel free to break these into separate cards.

- [x] Polygon points can be reordered: user should be able to add a new polygon and reorder the list of points.
- [x] Selected polygon is previewed: user should see a handle for the point currently selected in the points list
- [x] All polygon points are visualized: user should see all polygon handles as small rounded rectangles (like existing selection handles) when viewing a polygon, the currently-selected polygon should be a special color
- [x] Polygon points can be dragged: the final stage allowing polygons to be fully visually-manipulated

**Comment by vchelaru** [comment]
Task 1 finished:
![04_14 56 19](https://user-images.githubusercontent.com/729631/177215762-e6bc82dc-f599-4be3-85c6-e0533cdf204c.gif)
478878957849cc845674abb9d478704f17ba05e7

**Comment by vchelaru** [comment]
Added live edit support in game.
![HRQTu6NqGK](https://user-images.githubusercontent.com/729631/177674516-4d73c1f2-4199-4676-bbd9-f034a751ecb5.gif)

851bd30d5f850ea2012130247fe354bc97dc9b97

**Comment by profexorgeek** [comment]
I have tested this and all criteria are satisfied! I think you may have misunderstood what I meant with items 2 & 3... I just wanted to be able to see the points and know which point is currently selected. These were granular criteria because I assumed that visually dragging points would be difficult and take more time. In the interim I wanted good visualization in the editor while you manipulate polygons numerically.

Anyway, all criteria are satisfied and I'll close this issue.

Gif:
![masteroid-polygon-pts](https://user-images.githubusercontent.com/711100/177815498-4fc0bb8c-186d-4385-8070-beac7952d222.gif)
