### ISSUE TITLE
`Sprite.TextureFilter` should be honored during rendering

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#635]
In my project I am building a space stations that have tiled-like components. I have my game set to use `Linear` filtering and am setting specific sprites to use `Point` filtering so they don't have pixel bleed from surrounding tiles.

You can see an example of this in the ring chunk entity here (private repo, access shared to appropriate parties):
https://github.com/profexorgeek/MasteroidRedeux/blob/master/MasteroidRedeux/Entities/Stations/Components/StationRingChunk.cs#L9

But setting this does not change how these components are rendered. The ring chunks still have artifacts where surrounding pixels on the sprite sheet (or lack of pixels) bleeds into the sprite frame:
![image](https://user-images.githubusercontent.com/711100/177646598-0c01de39-cbce-4825-94dd-7853a20ba996.png)

**Comment by vchelaru** [comment]
I believe that this is in fact working just fine, and the circle you are seeing is a seam from floating point inaccuracy. I think if you do a slight overlap it will solve the issue. 

First, I ran an isolated test with sprites alternating their texture filter. All seemed to work okay:

![image](https://user-images.githubusercontent.com/729631/177806623-3215b07a-4dff-4af2-8f1e-ed6455c9600e.png)

After that, I ran MasteroidRedeux and zoomed in really far to clearly see if point filtering is used, and it is:

![image](https://user-images.githubusercontent.com/729631/177806701-e95de32d-99e0-4c91-a577-73fc72b65715.png)

**Comment by profexorgeek** [comment]
The assertion about the line gap makes sense if it's a pixel rendering issue. But it doesn't make sense when you can see artifacts around the "greebles". I will re-test and see.

**Comment by profexorgeek** [comment]
Per our conversation in Discord, we were able to repro partial sampling-like artifacts.

We experimented with turning off mipmapping, which didn't help, and verified that no artifacts happen when the whole game is in Point sampling mode - which means it's unlikely to be a sprite positioning problem.

The suspicion was that rendering mode is not being reset somewhere and bleeding across sprites in some cases. Setting the camera cull mode to "None" made the problem go away. I don't understand the implications of that but I suspect it reinforces the idea that rendering mode is bleeding across sprites.

**Comment by profexorgeek** [comment]
I tried and tried and couldn't get a simple repro. Even duplicating the screen failed to repro the problem in the duplicate screen.

It happens reliably in this commit, which is the best I've been able to do:
https://github.com/profexorgeek/MasteroidRedeux/commit/41b03368299532bcf40cccbde3b9652e47d4b7eb

**Comment by vchelaru** [comment]
FIXED!

![image](https://user-images.githubusercontent.com/729631/178022437-1d81ad59-bd5a-429d-b83d-1f49444b6eb2.png)

ed71f49c9de3c7c23322cc54bf0456ab57c6640a
