### ISSUE TITLE
Editor should allow show/hide of grid

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#636]
The grid is usually desireable for positioning things, however it can be disruptive if you just want to view the entity as it should appear in game. The editor options should allow you to show/hide the grid.

**Comment by vchelaru** [comment]
Fixed
![08_18 20 07](https://user-images.githubusercontent.com/729631/178084258-04091127-8d9a-44df-a8f0-91375e73d8e9.gif)

20f626040b3f39c448a7e0dcbaf017d376f3c107
