### ISSUE TITLE
Inherited color variables do not get sliders

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#637]
I created a base object called `DecorBase`, which is a quick way to add general decor sprites to a sector. It exposes the sprite color channels and the animation chain. These variables are `SetByDerived` so that child classes can customize them.

I created a `Planet` object that extends `DecorBase`. It uses the BaseSprite as the planet's base color and adds several layers of sprites. Each of the layers exposes it's animation chains, color and alpha sliders, and similar things.

When adding a `Planet` to a screen, all of the layers' exposed properties get sliders as expected for color channels. But the inherited color properties from `DecorBase` do not get sliders.

Here's a long gif that demos how a planet is added to a screen and customized:
![masteroid-planet-timelapse](https://user-images.githubusercontent.com/711100/177660413-19847e90-3f2e-487c-ab25-63ff88cfc41c.gif)

**Comment by profexorgeek** [comment]
In case it wasn't clear, notice that the BaseSpriteRed and similar fields are floats but the other exposed colors are bytes with sliders. Those fields come from the parent object and should be bytes with sliders.

If you pull latest MasteroidRedeaux, you can inspect these components:
Entities/Decor/DecorBase
Entities/Decor/Planet

**Comment by vchelaru** [comment]
Fixed

![image](https://user-images.githubusercontent.com/729631/177793218-3bb671f9-5f50-4ee4-87f2-8e47105c3be7.png)

67fa09fa3bfaec440ebaceb32985b86db5d89044

**Comment by profexorgeek** [comment]
I'm reopening this because I discovered the same issue with a different class of variables (sprite chain). This is the same problem but just a different variable type. We could open new issues for every variable type that exists as we find them or we could re-open this to make sure this is solved at a broader level?

In this example, BaseChain is defined in a parent entity and does not get a dropdown in the child entity instance:

![image](https://user-images.githubusercontent.com/711100/177838351-65908390-9c62-43c5-bafa-78c0b1148f39.png)

**Comment by vchelaru** [comment]
Let's try this again :D

52387656c7da778bdbe59831fd4d153edc39a538
