### ISSUE TITLE
Sprite texture mapping window should immediately apply snapping value

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#641]
When changing the snapping value in the Map Sprite Texture popup, it does not appear to respect the snapping value.

This is because in order to apply your change, the snapping field has to lose focus. But clicking in the main mapping window does not take away it's focus. So the appearance to the user is that it doesn't work. The user must click another control, such as Zoom, or press the tab key to take focus away from the snapping control and apply the value.

The snapping value should immediately be applied on text change.

**Comment by vchelaru** [comment]
Fixed

![07_18_29_28](https://user-images.githubusercontent.com/729631/177893022-c38b1f93-f6b2-4a27-8362-36e418050b93.gif)

2ffd507b2d24f4def05fd6be501a1e6f13c8e496
