### ISSUE TITLE
Editor should not crash and become buggy 

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#642]
If you assign a bad animation chain name or decide not to use animation chains and remove the chain before you remove the chain _name_, the running game crashes and the editor and Glue both become unstable.

The engine should handle animation chain names that don't exist more gracefully.

**Comment by vchelaru** [comment]
Fixed

8e8c06abad6c1c500d720d49e1bee04b4d892a48

Please note that this requires updating GLUJ to version 18.

Users who are interested in upgrading to this should check https://flatredball.com/documentation/tools/glue-reference/glujglux/
