### ISSUE TITLE
Polygon points editor should have option to snap to whole pixels

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#644]
Points currently can be set to values like "-3.8886" but in most games the editor will want these to be whole values to prevent little snagging and similar problems.

For now, you should be able to specify snapping to whole numbers. In the future, more configurable snapping may be desirable but we should work out other issues first?

**Comment by vchelaru** [comment]
Added

![08_10 19 36](https://user-images.githubusercontent.com/729631/178031471-fe954816-30d0-41a7-a5ac-eefc61443ed8.gif)

6fc7094c5c3d913430d8eb075897694fb969b047
