### ISSUE TITLE
Add extra logic for plugin code generation

### ISSUE THREAD

**Issue by zdman2022** [vchelaru/FlatRedBall#656]
Let's clean up our code generation handlers where multiple plugins can add to a method.  We should add a comment automatically saying which plugin created the code block.  We should also add curly braces around the code to prevent scope interference between plugins.  Also, add an empty line between each plugin block.

**Comment by vchelaru** [comment]
There are a few challenges with this approach:

1. Currently the code generators are added to the main list of code generators and a separate list for plugins. The main code generator doesn't know where a plugin came from unless it looks through all plugins to ask them "is this yours?"
2. Sometimes we intentionally want codegen from one plugin to be accessible by codegen from other plugins. I don't know if I can think of an example on this, but I'm pretty sure it's used somewhere. If we put everything in its own brackets, that would break this behavior.
