### ISSUE TITLE
Behavior icons should be consistent

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#669]
![image](https://user-images.githubusercontent.com/711100/181379705-d223db35-caa1-46fc-8aa0-25129d4b262f.png)

These icons seem to have meaning but it's not clear what the meaning is. Per our discord conversation, this is a bug.

**Comment by vchelaru** [comment]
Fixed

![image](https://user-images.githubusercontent.com/729631/181826882-5710ff42-1b3d-4e3d-a886-db2a673965cb.png)


Gum repo fc57e0caed9a23a402acaee89348b80e3302d917
