### ISSUE TITLE
Make changes to new Gum Forms art 

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#671]
I'll separate these out into sections to explain them as needed

## 1. ListBoxItem selection should be "stronger" than highlight

The following shows the list box with one item highlighted and one item selected. Which is which?

![image](https://user-images.githubusercontent.com/729631/181771887-0101b442-0e70-444b-8dfb-03f1cdfc01f0.png)

I would expect selection to be "stronger" than highlight but actually the dimmer 600x800 is selected above. 

For example, in WPF the "Objects" item is selected, while "DemoScreenGum.gusx" is highlighted:

![image](https://user-images.githubusercontent.com/729631/181772065-35e2bebc-3201-4ea4-b688-de4d259bef61.png)

Another example: Issues is selected, Pull requests is highlighted:

![image](https://user-images.githubusercontent.com/729631/181772164-6eafa6a0-d7ce-4a2a-800f-6de5d4c51fcb.png)

## 2. TextBox placeholder text should be dim compared to entered text

Placeholder text looks the same as text entered manually. Placeholder text should not be as high contrast as entered text.

Currently this is placeholder text:

![image](https://user-images.githubusercontent.com/729631/181772476-414dc612-5a78-42f6-b691-36275ffef9da.png)

This is entered text:

![image](https://user-images.githubusercontent.com/729631/181772519-4d22cc92-621d-4868-846d-f07d2c3415be.png)

For example, here's wells fargo's website placeholder:

![image](https://user-images.githubusercontent.com/729631/181772647-98777a41-afd1-4fc1-b0d8-4975fe06f006.png)

And entered text:

![image](https://user-images.githubusercontent.com/729631/181772731-2b42102e-5403-4c65-b4ec-71a28bfb8d9f.png)

## 3. Consider border on ListBox and ScrollViewer

Currently the ClipContainerInstance for ListBox stretches to the edges of the list box. At 100% scale this looks like selected items bleed over the edge:

![image](https://user-images.githubusercontent.com/729631/181778870-de3e0344-9bd9-4c80-a6ee-db5150dbf79f.png)

They actually don't bleed over the edge, but the list box items do overlap the 1px border which gives that appearance:

![image](https://user-images.githubusercontent.com/729631/181779096-6d7cca02-866c-43bb-a243-7132b61db60c.png)

![image](https://user-images.githubusercontent.com/729631/181779139-8fee5aee-aea5-47c1-aab5-139ec796de02.png)

![image](https://user-images.githubusercontent.com/729631/181797080-4072de9a-0d40-48c4-90cf-ab64b0631381.png)

I believe adding 1 pixel margin on the ClipContainerInstance would work better. This should probably be done for both ListBox and ScrollViewer.

## 4. Add DialogBox control

The DialogBox control is used for games which have dialog between characters, common in RPGs. I realized that there is a behavior for it, but it isn't correctly showing the requirement so I've updated that. The DialogBox has:

* TextInstance (required) of type Text
* ContinueIndicatorInstance (optional) of any type. This is something which appears when the text is fully typed out to tell the user that a button will advance to the next page of text.

Here is the current implementation in the "old" forms project:

![image](https://user-images.githubusercontent.com/729631/181782129-5ad7b452-1a0f-4f54-a2f2-4f014a810654.png)

Example from Final Fantasy 6:

![image](https://user-images.githubusercontent.com/729631/181782252-b20fbbab-8edc-4cdc-8ec3-4a7f7b1a63b0.png)

## 5. Add a Keyboard component

![image](https://user-images.githubusercontent.com/729631/181783083-b9ff213d-329e-42a1-b7d3-4f87e66de806.png)

The behavior for this was missing some things so I added it, but it needs:

* FocusIndicator (required) of any type. This can be moved around by the gamepad to select characters. 
* Keys in any arrangement. I did it in rows, but I don't think it matters. The logic supports any structure. I'll talk about Keys below.

## 6. Add KeyboardKey

This is actually a Button, so technically you don't NEED to have this, but it might be good to have a dedicated key. It should have a TextInstance. This text is used to determine which text to place when the key is pushed.

![image](https://user-images.githubusercontent.com/729631/181784174-06c059f7-a0d3-4618-a49a-374b5b584fa2.png)

## 7. Implement TreeView and TreeViewItem

These are missing and are supported in code in Forms.

## 8. Implement UserControl

UserControl is used in two common scenarios:

1. When a user wants to create a general panel that holds something, like a popup window or a box that holds options, they may inherit from this.
2. When creating a new Forms object in code, the user may inherit from UserControl. This is common in WPF. For example, the Gum Project Properties tab in Glue is a control which inherits from UserControl
![image](https://user-images.githubusercontent.com/729631/181793535-c8a7b818-52d2-498e-bb5a-bd87aa94265b.png)

## 9. Caret should be "crisp" and narrow rather than blurry

The current caret icon is using a sprite which is resized. It does work to communicate the caret, but it is slightly blurry and it can overlap text, especially since the default font size is quite small.

![image](https://user-images.githubusercontent.com/729631/181795308-3800f336-3cb7-4020-bcc4-bd6c5651520c.png)

I've zoomed the image for convenience:

![image](https://user-images.githubusercontent.com/729631/181795360-4b1278b7-dc7a-4bc4-b908-4447c43325df.png)

Typically applications use very small carets. For example, the github window I am typing in has a very narrow caret:

![image](https://user-images.githubusercontent.com/729631/181794658-e2e0ae96-7a33-4ce0-a3b5-fbb5dd9d6c04.png)

I took a stab at this and used the Primary color on a ColoredRectangle:

![image](https://user-images.githubusercontent.com/729631/181797668-3272ee72-d3c6-41ba-8da3-274fccb97778.png)

Feel free to ignore this issue if you approve.

**Comment by profexorgeek** [comment]
Had a bit of time to work on these this afternoon. Items 1-3 are fixed and pushed to the staging (Narfox) repo. It'll be a bit before I can finish the last items.

**Comment by profexorgeek** [comment]
I have now done keyboard and keyboard key. I have NOT done the dialog yet. I did keyboard and key out of order because I already had them close to styled in another project. Updates are in the Narfox staging repo if you'd like to test.

![image](https://user-images.githubusercontent.com/711100/181936467-f6b3c888-146b-4d5c-b317-d9f1658f9b83.png)

**Comment by vchelaru** [comment]
Added test for keyboard, works great:
![31_09 17 37](https://user-images.githubusercontent.com/729631/182033233-acc5bb15-e9c2-433f-a43f-6ad1de3fe5bf.gif)

I've updated it all in the new repo:

https://github.com/flatredball/Examples

**Comment by profexorgeek** [comment]
Okay, I _think_ I'm done with these items pending testing. I have:

- Fixed your caret fix to use Sprite instead of colored rectangle
- Applied your caret changes to the `PasswordBox` too - it was only fixed in the `TextBox`
- A `UserControl` already existed but there's nothing to implement in this component?
- Skinned the `TreeView` item and it's dependencies
- Added/skinned the DialogBox item

**Comment by vchelaru** [comment]
I fixed treeview to have proper stacking. I am implementing Toast now.

**Comment by vchelaru** [comment]
Toast is done!
