### ISSUE TITLE
Gum ColoredRectangle should expose its texture

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#677]
It's a hidden gotcha that the ColoredRectangle in Gum acts exactly like a Sprite. It has a hidden texture that can only be set in code. If users don't know this and mix ColoredRectangle with spritesheet fonts they'll have hundreds or thousands of render breaks.

The ColoredRectangle should expose its source texture property in Gum and be mappable to a spritesheet the same way that Sprite is.

**Comment by vchelaru** [comment]
Done Gum repo: 48ddd8d29ca05f5c969a2d5aa62ffc7d10948a72
