### ISSUE TITLE
TreeView should have the same states as ListBox

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#678]
Some issues I found with TreeView stuff:

- [ ] The behaviors don't actually reflect the required components. I think the TreeViewItemBehavior is missing some instances that are required.
- [ ] The TreeView itself should have the same states that a ListBox has

**Comment by vchelaru** [comment]
## TreeViewItemBehavior

The Behavior is correctly set up to include all required objects (only the InnerPanelInstance). The other items are optional, as outlined in the documentation: https://flatredball.com/documentation/api/flatredball-forms/controls/treeviewitem/

## TreeView States

Added  to both FRB repo and Examples. FRB repo commit: f18f32f29f0cc9672577e0fb268b8fe91837a69a
