### ISSUE TITLE
Creating a Glue project on the BeefBall tutorial should include correct steps and screenshots for latest UI

### ISSUE THREAD

**Issue by devinguthrie** [vchelaru/FlatRedBall#68]
On [https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-creating-a-glue-project/](https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-creating-a-glue-project/)

Under the section Creating a new project, Step 1 is fine but step 2-6 and the screen shot should be replaced to match the [RockBlaster Setup](https://flatredball.com/documentation/tutorials/rock-blaster/tutorials-rock-blaster-setup/) 

2. Enter the name *BeefBall* (no spaces) as your project name
3. Click Create Project!

![image](https://user-images.githubusercontent.com/7505151/111925415-0596d380-8a66-11eb-9851-3fc793cca27a.png)

**Comment by vchelaru** [comment]
Fixed
