### ISSUE TITLE
Gum should have Export As Image functionality

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#688]
Gum is becoming more and more useful as a layout and prototyping tool that makes it easy to take a prototype right into production.

But sometimes you may want to spit out a gum design and experiment with colors, layout, or other design aspects in an image-editing program. Tiled has this functionality and it's often useful to export a tilemap and overlay entities and effects to mock up a screen. While you can use a snipping tool to capture an image, the UI you are trying to capture may have transparency that is "flattened" when snipping, it may be too large to capture at 100% (if designing a menu the size of your screen), or it may be hard to snip to the exact borders of the component you want.

Gum should allow you to export a Screen or Component as an image:

- [x] Gum File menu has "Export As Image" command
- [x] Exporting image works on the currently selected screen or component
- [x] Export does not include any Gum lines or overlays
- [x] Export works with transparency so if you have a partially-transparent background it exports with correct alpha
- [ ] Export ignores current zoom and exports at 100%
- [ ] Export defaults to png, other image modes optional

**Comment by vchelaru** [comment]
Fixed.

Gum commit: 66a50644c71b07cbc8c0de79cf5339968d5d61b4

https://twitter.com/FlatRedBall/status/1558497986702741505
