### ISSUE TITLE
Create new project pop-up should have Glue Icon

### ISSUE THREAD

**Issue by devinguthrie** [vchelaru/FlatRedBall#69]
1. Launch Glue Version 2021.03.21.638
2. Click File > New Project

=> Observe Create new project pop-up does not have Glue icon

Expected results: Create new project pop-up should have Glue Icon

![image](https://user-images.githubusercontent.com/7505151/111925556-9d94bd00-8a66-11eb-9535-cf61e84e3a5d.png)

**Comment by vchelaru** [comment]
![image](https://user-images.githubusercontent.com/729631/113440281-5e8d3280-93a9-11eb-86d4-7db30cd163b0.png)
