### ISSUE TITLE
Glue should offer to create lists in the GameScreen if a new entity has a factory

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#702]
1. Create a game that does not use TMX
2. Right-click to add a new entity
3. Observe that option to add list doesn't exist

Expected behavior: user can choose to have a list of the new type added to the GameScreen.

Additional Info:
This is happening because the option to add a list is part of the Tiled plugin instead of its own plugin.

![image](https://user-images.githubusercontent.com/711100/183260203-79e2c7d2-8c3b-4025-a51f-9fa2f01c474c.png)

**Comment by vchelaru** [comment]
Fixed

![image](https://user-images.githubusercontent.com/729631/183448345-265b4d0b-39e2-4269-9b3d-8e84b74c8916.png)

3e30ae5b5a2a50363fd79388dd0b739fa88806c6
