### ISSUE TITLE
Editor should propagate static variable changes?

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#707]
Here's what this means:

1. I have entities that are `ICollidable`
2. Most of the time, I don't want that collision to show
3. I create an entity called `DebugVariables` and add a `static bool ShowCollision`
4. In my `ICollidable` entities, I add `Collision.Visible = DebugVariables.ShowCollision` in the `CustomInitialize` method
5. Checking/Unchecking the variable box in Glue causes collision to show/not show in the game
6. The _editor_ does not respect the value of this variable. Changing the value of the `static bool ShowCollision` variable does not result in entity collision being visible

I suspect that variable value is being compiled and not updated when a change happens. I _could_ solve this by doing edit mode checks in every entity but that is really inconvenient and the `DebugVariables` entity is a very popular pattern in FRB. This should probably Just Work ™️

**Comment by vchelaru** [comment]
Fixed
