### ISSUE TITLE
Editor window should not be offset when reloading

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#708]
I believe you can repro with these steps:

1. Have editor running, for me it's in full screen
2. Have an entity previewing in the editor, mine has sprites
3. Duplicate an object in the entity, for me that's usually duplicating a sprite that I want to change slightly
4. Observe that the editor disappears for a period of time to recompile
5. When editor reappears, it is offset and misaligned with the parent editor panel. Graphics are cut off with space where nothing renders.

![image](https://user-images.githubusercontent.com/711100/184374846-7da50f61-c71b-48c0-a6eb-e2d2a54825fd.png)

**Comment by vchelaru** [comment]
As a workaround - after the game runs, if the FRB editor is moved or resized then the window should snap into the correct position.

I'll be looking at this soon.

**Comment by vchelaru** [comment]
I believe this is fixed:

63151f0c4953dc4f6c17e84c3b8fb47852b50571
