### ISSUE TITLE
Temporary project upgrade files maintained in repo

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#71]
Nothing blocking, but noticed some of the auto-generated project file upgrade files are being maintained in the repo. I think you can delete those as soon as you think the upgrade went fine.

This was the [first UpgradeLog.XML that I noticed on the NewProjectCreator](https://github.com/vchelaru/FlatRedBall/blob/NetStandard/FRBDK/NewProjectCreator/UpgradeLog.XML), which is from 2016, but if you search for `upgradelog` on the repo file list, you may find a lot of others.

**Comment by vchelaru** [comment]
Removed.
