### ISSUE TITLE
Creating new project results in template ZIP file in project folder

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#710]
Creating a new project in Glue results in a template ZIP file in the resulting project folder.

![Folder file list showing MyProject, .gitignore, FlatRedBallDesktopGlTemplate.zip, and MyProject.sln.](https://user-images.githubusercontent.com/713665/185485353-16eda661-1411-4449-82cc-86d474ebfb11.png)

This was using the FlatRedBall project repo at Git commit `0b32f449`.

The only difference from default I did was unchecking the **Open New Project Wizard** option as instructed in this [Code-Only tutorial](https://flatredball.com/documentation/tutorials/code-only-project-tutorial/01-creating-a-flatredball-project/).

**Comment by vchelaru** [comment]
I also got this to reproduce, but after re-releasing the latest version this went away.
