### ISSUE TITLE
Texture selection region should not resize when clicking inside the region

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#715]
This one may need some conversation because I realize that this may be intentional at times. However, the "bug" is as follows:

1. Set your snapping to the desired size
2. Click somewhere in the grid to select snapping
3. Resize the selected region
4. Click+drag to move the region

Observe: On release, the region resizes back to the snapped size (in my case 16x16)
Expected: If the user simply wants to move the region, it should not also resize

![20_13 21 34](https://user-images.githubusercontent.com/729631/185763058-e81ce3d4-6a39-4e84-85cd-bf571a64b901.gif)

**Comment by dubhlaidh** [comment]
I didn't even realize you could drag that!  Prob easy fix.

In this example though in case you didn't know, you could set snap height to 32 and then not have to resize the box, just select the little guy's 16x32 cell

**Comment by vchelaru** [comment]
Oh yea I'm aware, but there may be situations where some objects are really large and they take up multiple cells. For example, we might want to have larger enemies that are 32 pixels wide. If we want to move things around, that would snap back down to 16 and make it hard to move existing selections.

Also, I should mention - there are situations where you may have a really large selection region but you do want to select just the cell. What do you think about double-click being a "punch through" where it brings the selection to the current snapped cell so that you can still shrink a selection without having to go to the handles?

**Comment by dubhlaidh** [comment]
Can probably do that.  I had planned on allowing click/drag to select larger regions, but was going to do it after I merged that stuff and got feedback.  Going to just get that working now as well.

so click in selection square & mouse move = drag selection around
click outside/drag = rectangular select all between start/end

**Comment by dubhlaidh** [comment]
No double click yet, but rest should be good.

**Comment by dubhlaidh** [comment]
Although the SelectedWidthPixels and SelectedHeightPixels in SelectCellDrag() is kinda ugly.  Probably a cleaner way to find those #'s.

**Comment by vchelaru** [comment]
I'm going to re-open this for the double click unless you think it shouldn't be implemented @dubhlaidh . If not, feel free to close this.

**Comment by dubhlaidh** [comment]
I was going to put it in.  I probably won't use it but it could see it being handy and shouldn't be very hard to implement.

**Comment by dubhlaidh** [comment]
Made a few changes.  Let me know if any of this isn't desirable.

- double click.  Also can double click & drag to immediately start drag selecting.
- Entering the dialog first time it set the selection rect to the entire image.  Changed it to be the top left cell.
- Moved some repeated view.xx() calls in CameraLogic into view.
- Adjusted the zoom & fit
- Some more adjusting on initial window size.
