### ISSUE TITLE
Texture coordinate selection window should default to 16x16 instead of 256x256

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#717]
This could be discussed, but I believe that the most common snapping for FRB games is 16x16 because it is "SNES Style" where resolutions are fairly small. The typical tileset is 16x16.

Currently the size is 256.

**Comment by dubhlaidh** [comment]
It was defaulting to 16 cells - or 256 pixels for a 4096 size image.  But it was just randomness I figured was better than the previous value of 4 which needed to change or the grid was too line-y .  If most are using 16 pixels it should default to that.
