### ISSUE TITLE
Glue toolbar icons cropped

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#73]
After building Glue from source at 27da7c83105b90a26440ce0b433f924576125032 (plus the workaround from #72), Glue has all the toolbar icons cut off by the next section below them.

![Screenshot of Glue with header toolbar icons cut off about halfway by the next lower Quick Actions section.](https://user-images.githubusercontent.com/713665/113079704-ccabdc80-9192-11eb-8f21-ef3aa55e8768.png)

**Comment by vchelaru** [comment]
This has been fixed. This was caused by the toolbar being placed on a winforms window and having a fixed size of 26 pixels. It's been migrated into the main WPF panel and sits on a grid with auto height.

**Comment by patridge** [comment]
Definitely confirmed here...thank you!
![image](https://user-images.githubusercontent.com/713665/113318574-d25a0d00-92cd-11eb-9a34-90542c018ff4.png)
