### ISSUE TITLE
Editor should not allow creating a variable with no type

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#736]
It's possible in Glue to create a variable without selecting a type, such as `float`. When you do this, it causes a cascade of problems and crashes that make the editor unstable.

![glue-no-type-var](https://user-images.githubusercontent.com/711100/187250726-9d3d5f56-87c2-421b-95a5-ba7f4174fe5c.gif)

**Comment by vchelaru** [comment]
Fixed - also, new variables now default to "float" type so it may not even be possible to reproduce, but if it is, an error will display.

faaf3937e9ac675f4471b6ef5de269d14783ba4d
