### ISSUE TITLE
Editor should not allow changing variable type on a derived variable

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#737]
Currently Glue allows you to change the type of a variable in a child class, even if that variable is defined in a parent class. This causes a collection of crashes and problems. Glue should prevent you from changing the variable type on `SetByDerived` variables in a child class.

**Comment by vchelaru** [comment]
Fixed

![image](https://user-images.githubusercontent.com/729631/188242756-58a78e07-b793-478a-93ff-25fdb11c0722.png)

4deedda16a3ef138f3fdf348de9127f3b43955dd
