### ISSUE TITLE
Editor should confirm, then cascade, SetByDerived variable type changes

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#738]
Currently if you change the type of a variable that is marked as `SetByDerived` in a base class, it does not warn you and does not cascade the type change to child classes.

The Editor should ask "Are you sure, this will change Entity1, Entity2, Entity3, etc" and then update all child class variable types when the user has confirmed.

**Comment by vchelaru** [comment]
Fixed:

af29445bef1f177d7c0f19231997daef8ad65d63
