### ISSUE TITLE
NewProjectCreator: unhandled exception after new project created

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#74]
Spun up a new project from latest commit (f3f9ae623c81f47ec68865e9b0e5f0dc94e83bc6). It went through the download appearing to be happy and then jumped back into VS2019 with this exception.

![image](https://user-images.githubusercontent.com/713665/113318874-21a03d80-92ce-11eb-9722-3a0c5e6aa6d1.png)

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=DialogResult can be set only after Window is created and shown as dialog.
>   Source=PresentationFramework
>   StackTrace:
>    at System.Windows.Window.set_DialogResult(Nullable`1 value)
>    at Npc.MainWindow.<BeginMakingProject>d__8.MoveNext() in C:\dev\FlatRedBall\FRBDK\NewProjectCreator\NpcWpf\MainWindow.xaml.cs:line 110
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Npc.MainWindow.<HandleMakeMyProjectClicked>d__7.MoveNext() in C:\dev\FlatRedBall\FRBDK\NewProjectCreator\NpcWpf\MainWindow.xaml.cs:line 85
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
>     Npc.MainWindow.BeginMakingProject() in MainWindow.xaml.cs
>     [External Code]
>     Npc.MainWindow.HandleMakeMyProjectClicked(object, System.Windows.RoutedEventArgs) in MainWindow.xaml.cs

**Comment by vchelaru** [comment]
Fixed by removing steps from the run-from-source page.

**Comment by patridge** [comment]
I was still using NPC from a separate solution. THis appears to be removed from download instructions now.
