### ISSUE TITLE
User should not see pure white spritesheet

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#742]
In order to turn snapping off when mapping a sprite, you can set the snapping to 1x1. This works fine but when zoomed out the spritesheet looks entirely white because of the grid lines. Each time I have encountered this, I thought it was a bug where the mapping window crashed before realizing it was just the grid. You must zoom in before you can see that you are looking at a spritesheet with a grid and not a solid white texture.

In general the workflow is typically going to be _either_ have snapping on w/ a consistent increment such as 8, _or_ turn snapping off entirely so you can map a specific sized sprite. So, creating a checkbox that toggles snapping and the grid on/off will be better for workflow while also eliminating this perceived bug.

![image](https://user-images.githubusercontent.com/711100/187939434-93b93f8b-e417-43c6-b548-53d0f93b8112.png)

**Comment by vchelaru** [comment]
I believe this should just have a checkbox for snapping above the width/height.

**Comment by dubhlaidh** [comment]
I think it looks great like that....

I should also make it so by default Height is linked to Width, but allow disabling that for odd sized cells.  This makes the standard case of square cells 1 less # to type in.

**Comment by dubhlaidh** [comment]
check box to turn off.  Also turns off if width==1

check box to unlink height/width.  defaults off.

Let me know if you want any UI rearranging there...  I tried a couple different things and it's ok, but didn't find what felt like the perfect layout.
