### ISSUE TITLE
Texture Coordinate Selection should not get into a bad offset state

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#743]
When using the texture selector you can get into a state where the snapping is offset by an incorrect amount:

![image](https://user-images.githubusercontent.com/711100/187940104-93247a58-4c6e-4b83-b765-e461fb73203c.png)

Repro:

- Get to a point where you can map a texture on a sprite
- Set the snap increment to 1x1 and draw an odd (non-binary) sized shape
- Change snapping increment to 8x8
- The whole object snaps to 8x8 from where the selection currently is, but it does not snap it to a global 8x8 grid
- It also does not snap the size to an even increment of 8

Expected behavior: both the dimensions and origin of the texture coordinates rectangle snap to a global NxN grid where N is your configured snapping size.

Actual behavior: the coords rectangle maintains it's size and snaps to an arbitrary offset from the NxN grid.

**Comment by dubhlaidh** [comment]
HA!!!!!  This was the preexisting bug that got me started adjusting this dialog!  And I didn't even fix it doing all these other changes!! *sigh*
