### ISSUE TITLE
TileShapeCollection defaults to square grid based on width of the tiles.

### ISSUE THREAD

**Issue by sabsmall** [vchelaru/FlatRedBall#765]
Adding a TileShapeCollection based on a non-square TileSet, the bounding box defaults to a square with side length equal to the width of the tiles.

I wouldn't put a high priority on it.

Two workarounds came to mind, until the issue is resolved.
-Compositing square tiles in case of integer side ratio.
-Stretching a window of square tiles.

If i am correct, the GridSize property in TileShapeCollection is the cause, as it assumes only one data dimension.
Turning it into a float pair would help hunt down all the not compiling references. (Not sure about the generated ones.)
Which there are plenty. Even my meager project had 119 reference to it, many highly repetitious.

Generated   #	File
Read	 47	[project dir]\GlueControl\Editing\Markers\TileShapeCollectionMarker.Generated.cs
Write	   2	[project dir]\GlueControl\Editing\VariableAssignmentLogic.Generated.cs
Total	 49
Non-Gen
Read	 61	[project dir]\TileCollisions\TileShapeCollection.cs
Write	   8	[project dir]\TileCollisions\TileShapeCollection.cs
Write	   1	[project dir]\TileGraphics\LayeredTileMap.cs
Total	 70

**Comment by vchelaru** [comment]
I spent a little bit of time researching this. GridSize is primarily used for partitioning and picking a rectangle based on an arbitrary position.

The TileShapeCollection wraps the more general ShapeCollection class which has the properties `MaxAxisAlignedRectanglesScale` and `MaxPolygonRadius`. This means that changing the TileShapeCollection to support different GridSizes on X and Y would result in changes to `ShapeCollection` too. It seems like a trivial change but it would actually require a bit of work, and it may have slight performance impact on partitioning too.

I realize that this is a feature supported by Tiled, and all else equal we should support any feature that Tiled supports. However, there are lots of features that Tiled supports which FlatRedBall doesn't, so if we are going to expand the set of supported features we should do so in order of what is high priority and low impact.

My main concern (as far as impact goes) with this change is that I'm not sure how to perform this without breaking existing projects. 

Actually, perhaps I could have MaxAxisAlignedRectangleScale simply return the X version and have it set both X And Y. But internally it could use X and Y... I'm going to investigate this.

**Comment by sabsmall** [comment]
Hi,

Just got home from work. On the weekend I will look into what limited
contribution can i make on the matter, besides confirming the issue indeed
has zero priority. It's quite an edge case if a rectangle is needed.
:winkwink:
(Should i copy my answer to github, or is that better used only for
briefings)

Victor Chelaru ***@***.***> ezt írta (időpont: 2022. okt.
20., Cs, 15:08):

**Comment by vchelaru** [comment]
Your answer is on Github :)

I'm working on a fix for this now.

**Comment by vchelaru** [comment]
Fixed

de9d9b423fc1be86a959d9d54b1706d692ca713b
