### ISSUE TITLE
Selecting item in treeview should select it in the editor

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#767]
Repro steps:

1. Have a screen running in the editor
2. Drag some entities into the screen
3. Select an entity in the editor
4. Observe it has a rectangle showing what is selected
5. Select a different entity in the treeview
6. The selection rectangle in the editor doesn't change

Use cases:

- When duplicating an entity, you can't tell which entity is selected or where the duplicated entity is
- Sometimes Glue freaks out and an object moves way out of position (probably due to some weird command latency?), it's very hard to find the new object
- When the Editor rectangle and the treeview selection don't match, you can spend a lot of time updating the properties of the wrong entity

This is a major workflow problem that can totally break the editing experience so I'm marking this as a blocking issue

**Comment by vchelaru** [comment]
The selection bug has been fixed. I believe I have improved the bug with objects moving off-screen (far away) but I'm not 100% certain. I'm going to close out this issue since the main issue is fixed, and we'll see if the other issue still occurs.

d3c4d0225ca555b09e71235993e7783ad81b52c2
