### ISSUE TITLE
Editor should use the whole editor window to render

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#770]
![image](https://user-images.githubusercontent.com/711100/193701457-0d741eba-92a2-4ee4-a553-9557129bd2a9.png)

**Comment by vchelaru** [comment]
Fixed!

![11_07 57 19](https://user-images.githubusercontent.com/729631/195113455-3336c2f6-7a75-44e5-8f14-e6e20d6f7ef4.gif)


205f01267bb6145db1e6e41f08f967c4ea68c51c
