### ISSUE TITLE
Renaming an uncategorized state in Gum causes an exception

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#804]
![imaxe](https://user-images.githubusercontent.com/24922404/203947907-497e454d-709b-4458-9e41-e4e86c8088a2.png)

I'm moving to categorized states as recommended but I came across this exception while renaming the uncategorized states. I can provide the Gum project if needed.

**Comment by vchelaru** [comment]
Fixed. This is a Gum repo fix so be sure to update that repository. Commit d5911b3a214d55bc0fa1a191afe573a514d60d4e
