### ISSUE TITLE
Gum animations preview time is stretched

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#806]
![GumTimeStretching](https://user-images.githubusercontent.com/24922404/204015103-afd3673f-29b8-4c7e-800e-3e2d0c73272e.gif)

While previewing an animation in Gum the time it takes to complete is much longer than the time it should take. For example, as shown in the gif above, an animation of 1 second takes almost 3 seconds to finish. The animations play at their correct speed while running the game.

**Comment by vchelaru** [comment]
I believe this is a MVVM bug in the binding. Changing the playback speed from 100% to a different value, then back to 100% makes the animation play correctly. Need to investigate the initial binding code to see why it might be binding to the wrong value...

**Comment by vchelaru** [comment]
Fixed on Gum commit 8563d3e6836f23c9846e27d55fb80e03782b61e2
