### ISSUE TITLE
Bad performance while playing Gum animations

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#807]
While Gum animations are running the game seems to have a severe hit in performance.

Performance while showing inventory UI without animation -observe the FPS remain at a steady 60-:
![NoAnimPerformance](https://user-images.githubusercontent.com/24922404/204024369-e8dd5918-fad7-4eb3-8fac-a41289dd052e.gif)

Performance while showing inventory UI with a Gum animation -the FPS take a hit-:
![AnimPerformance](https://user-images.githubusercontent.com/24922404/204024399-3a1617df-ebfb-42a0-91b3-59daf8fd6fc8.gif)

Inspecting the game's CPU performance I found this, which looks like an abnormal CPU use for a simple event handler. Maybe there's heavy memory allocation?
![imaxe](https://user-images.githubusercontent.com/24922404/204024890-2a7b7180-3913-4381-84fc-50dbb5054c82.png)

**Comment by mfigueirido** [comment]
Spent a little more time with this. PositionChanged is wired in generated code to InterpolateBetween which in turn makes lots of calls to ResumeLayout:
![imaxe](https://user-images.githubusercontent.com/24922404/204267910-7aaa0261-a4b0-4343-9192-07f3d1d44924.png)

The animations are just moving a top component from a position to another. To my understanding -which could be flawed- a deep layout update would be redundant in this case -and probably others too- so maybe a solution would be to check the kind of properties being changed, whether children components are affected, and skip these deep layout updates in those cases?

**Comment by vchelaru** [comment]
There is now an update which improves performance on some animations, but the real problem now is that when we suppress/resume updates, the resume is recursive. If there are tons of children, then this recursive resume can be slow.

To fix this, we need a SuspendLayout which can be shallow or deep, and a resume that is also shallow/deep.

**Comment by vchelaru** [comment]
Update - SuspendLayout and ResumeLayout can take `true` or `false`. By changing it to `false` in @mfigueirido 's case, the fps improved a lot. Therefore, we can probably check which variables are changing, and see if we need deep or shallow. For example, for X and Y, we don't need deep updates even if we're using right or left alignment.

**Comment by vchelaru** [comment]
I've updated it to only do shallow updates if certain variables are changing.

Commit 67571c0f304e0bfa1456cd07973398a6408ae8c7
