### ISSUE TITLE
Another case of suboptimal Gum performance

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#808]
![ItemEquip](https://user-images.githubusercontent.com/24922404/204529145-dd1db59a-01ba-4a26-9128-813144922cc3.gif)

In this case the bad performance comes when equipping items. The code being executed related to UI on this action is as follows.

This toggles visibility of the "E" letter in the selected item slot on the grid:
![imaxe](https://user-images.githubusercontent.com/24922404/204529884-86b12c7e-1b8c-471f-b218-604ffabda0c9.png)

This sets up the "equipped item" area below the grid. It changes the current texture and the text showing the ammo it holds (or hids those controls if appropriate):
![imaxe](https://user-images.githubusercontent.com/24922404/204533540-7ae690d0-f1ee-4558-819d-0e513edac734.png)

Taking a look at method cost we get this:
![imaxe](https://user-images.githubusercontent.com/24922404/204532581-2c65aede-a84f-4cad-a28f-f7df53dfba30.png)

The way I look at it I think Texture properties shouldn't spam layout updates when the size of the texture is equal to the last texture set. Visible and text I understand they could trigger layout updates but maybe there's a way to make this more efficient.

**Comment by mfigueirido** [comment]
Update - Called SuspendLayout() on the controls before changing the properties and ResumeLayout() after but the performance didn't improve.

**Comment by vchelaru** [comment]
This one may require a number of fixes, so I'm going to do this one-at-a-time.

The first is texture, which is currently implemented as shown in the following snippet:

```
public Microsoft.Xna.Framework.Graphics.Texture2D Texture
{
    get...
    set
    {
        ContainedSprite.Texture = value;
        UpdateLayout();
    }
}
```
The setter does an update no matter what. In this case, the game is using a PercentageOfFileWidth and Height.

![image](https://user-images.githubusercontent.com/729631/204543237-54a4d4ec-d6f7-4e28-abbd-a45282489d55.png)

Changing the texture can change the width, but we could have a before and after check to decide if the sizes really did change. If not, no need to do an update layout. I'm going to work on this first.

**Comment by vchelaru** [comment]
The texture fix has improved performance slightly, but there are still framerate pops.

I believe the reason the framerate pops are happening is because a menu popup is being moved around. This menu popup is a child of the main inventory backpack. The backpack resizes itself based on its children. Therefore, if a child moves, the parent must do a layout. Doing this layout cascades to all children which is somewhat expensive.

In this case, we don't want the parent to resize itself based on the movement of the popup. The popup should be a child of the parent so that it can be positioned correctly, but it should not update the width or height of the parent.

To solve this, Gum needs a property to tell the child to not be considered in the parent's calculated width (which is what we really want conceptually in this case). This would improve performance.

**Comment by mfigueirido** [comment]
Ok. Got all the latest fixes, checked the new option "ignored by parent size" on the problematic actions menu popup and begun testing layout calls. These are the circumstances inside the game that appear to do a little too many layouts:

1) Text with selectable options dissapearing after selecting an option - 13.782 calls
2) Combining two items inside the backpack - 13.504 calls
3) Assign a shortcut inside the backpack - 12.059 calls
4) Switch to the documents tab inside the backpack - 2.890 calls
5) Showing text with selectable options - 802 calls
6) Showing regular text - 428 calls

To assist you to perform those actions I think it would be helpful if you changed the game's language to english because I think you have it in galician or spanish. To do this while running the game press the "P" key and the pause menu will show:
![imaxe](https://user-images.githubusercontent.com/24922404/205111539-576620df-88b7-41bd-94f7-91739c81e18b.png)
Press "S" to highlight "Opcións" and press "B" to accept. The options screen will show and you can press "A" to set the language to english. Select "Done" and accept, and back in the pause menu select "Continue" and accept.

1) Happens after picking up an item like the ones inside the barn:
![imaxe](https://user-images.githubusercontent.com/24922404/205112972-43ffd97a-bd2e-4890-b305-f69fab331737.png)
Select "yes" or "no" and the layouts happen after the text dissapears.

2) For this you can equip the handgun (I believe you know how). After that exit the backpack, hold "M" to aim and press "B" to shoot. This will change the amount of ammo inside the weapon. Go back to the backpack, select the handgun and bring up the menu.
![imaxe](https://user-images.githubusercontent.com/24922404/205114435-bc0e6635-7149-42a0-98aa-af2e32fa5c4a.png)
Select "Combine" and after that select the handgun bullets. Accept. The cuantities should have moved and the layouts should have happen.

3) Inside the backpack select the metal pipe or the handgun. Press any of the arrow keys and the item will show in this section:
![imaxe](https://user-images.githubusercontent.com/24922404/205114871-61c77cc4-5968-429d-b124-de9b582e5ba2.png)

4) While in the backpack press "2" to switch to the documents tab.
![imaxe](https://user-images.githubusercontent.com/24922404/205115301-e2f528cc-daa2-4c0a-9e40-5108b8232eea.png)

5) Happens while showing the text related to picking up an item which contains selectable options "yes" and "no":
![imaxe](https://user-images.githubusercontent.com/24922404/205116478-3955ab02-c485-4869-981e-08ec1db1122f.png)

6) Happens while inspecting the environment like, for example, pressing "B" while next to this dump:
![imaxe](https://user-images.githubusercontent.com/24922404/205117079-3d98e509-1bac-4716-8f91-e24a1da1a91e.png)

I hope the explanations are clear enough. Thanks!

**Comment by vchelaru** [comment]
We talked about the fixes and so far they seem to have improved fps . It's not perfect, but maybe good enough for now.

If you would like additional fixes, please open another issue and let me know what areas to improve.
