### ISSUE TITLE
[Wildcard files] Added WAV files don't generate XNB until restarting the editor

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#822]
Steps to reproduce:
- With the editor open add a new WAV file in a widcard synced folder.
- The editor adds it but if you enter Visual Studio the XNB file isn't added to the content references. The game will crash because it can't find it.

Current workaround:
- Reopen the editor and it will generate the XNB and add it as a reference.

**Comment by vchelaru** [comment]
Fixed

b007df9fabd126b606a7e65c56dd68e6039ee239
