### ISSUE TITLE
Cancelling new project creation download throws numerous errors

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#83]
When on slow internet and creating a new project and decided to close the download progress dialog to cancel it. Not sure if it was intended, but it ended up presenting 5 error dialogs and a Notepad file with one of the errors, which seemed a bit excessive.

1. "Download for the following file has failed..."
2. "Clean and unzip failed"
3. Notepad with FRBDKUpdaterImmediateLog.txt and contents from step 1
4. "Error downloading the file"
5. "The local .zip file could not be unzipped.  Deleting this file.  Attempt to create the project again to re-download it."

**Comment by vchelaru** [comment]
Fixed!

![Uploading 2021_April_23_121108.gif…]()
