### ISSUE TITLE
Make the exceptions the game throws clearer to see

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#833]
Sometimes an exception is shown while starting the game but I don't notice it until I see that the game's window doesn't show up thinking the build just takes time or the loading is just being slow. In reality an exception stopped the game's execution.

FRB shows something like this on those scenarios:
![imaxe](https://user-images.githubusercontent.com/24922404/208107264-067a408b-955e-4352-9890-3203e02a7d5d.png)

It would be good if the exception was painted in red or something that makes them really stand out in the editor.

**Comment by vchelaru** [comment]
Fixed

fcc3726d0d0063d1001b03c954faadd1ff7aa757
