### ISSUE TITLE
Preview sfx and songs from inside FRB

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#845]
Just like the texture preview window it would be really nice to be able to reproduce sound efffects (.wav) and songs (.ogg, .mp3) from inside FRB.

It could be a window with simple player controls like play and stop and it could play right away when double clicking the tree node element. It could show the duration of the effect or song as well.

This would remove the necessity to have other apps open to reproduce the audio files while doing audio work. It's not something critical but I think it could make the experience more streamlined while working on audio.

**Comment by vchelaru** [comment]
Fixed

bb0464dd2628c87f6cd486e24c0cd8c43c21c25c
