### ISSUE TITLE
Add ability to search for folders in the tree view search box

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#854]
My game has a lot of global content organized in folders. It would be helpful to be able to search in the tree view search box for example "outskirts" and be able to double click on the result and it would take me to the actual "outskirts" folder. 

![imaxe](https://user-images.githubusercontent.com/24922404/209568074-595bb83d-4843-486e-8aa5-29e442520c70.png)

**Comment by vchelaru** [comment]
Fixed

87a866866f15c7b02e7223e4ca365a4d65b4165a
