### ISSUE TITLE
Creating a file from another app and saving it inside a wildcard synced folder causes duplicated references

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#861]
Steps to reproduce:

1- Open Glue.

2- Create a new folder inside a wildcard synced folder:
![imaxe](https://user-images.githubusercontent.com/24922404/209953087-cee40250-6918-42f9-bf0f-439cd3f206a5.png)

3- Save a new file from another app into that folder, for example a PNG file with MS Paint:
![imaxe](https://user-images.githubusercontent.com/24922404/209953242-087aebea-fc45-4859-bc82-8c102289e1c0.png)
![imaxe](https://user-images.githubusercontent.com/24922404/209953303-c43e6273-8bd3-4152-8dcc-cb613305daf0.png)

This is the result:
![imaxe](https://user-images.githubusercontent.com/24922404/209953352-d33eed8d-81a7-4fb1-a424-295014d29b2e.png)

If you try to run the game:
![imaxe](https://user-images.githubusercontent.com/24922404/209953563-8d4fb71c-82fc-4f23-bba3-bdc3b5ec88da.png)

Additional information: If instead of creating a file with an app you copy-paste another file only one reference is added (it works fine).

**Comment by vchelaru** [comment]
Note - this does not reproduce when saving from Paint.NET but it does reproduce when saving from the native Paint app. Good thing that was mentioned otherwise I wouldn't have been able to reproduce.

**Comment by mfigueirido** [comment]
Just mentioning it happened with Graphics Gale and Photoshop too but native Paint was certainly something you had in your computer. Tested and working perfectly. Thanks!
