### ISSUE TITLE
Add ability to rename a tree view element just pressing a key like "F2" in Visual Studio

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#863]
![imaxe](https://user-images.githubusercontent.com/24922404/209996334-19b5e70a-63b7-4fb7-83a5-ea4db4228f9d.png)

After pressing the key the field becomes editable and the name can be changed. Additionaly the user must be able to copy the string to paste it anywhere.

This would enable faster renaming of entities, screens, content files or folders. It would also be handy to be able to copy the name of an element to paste into Tiled's entities properties (I do this a lot).

**Comment by vchelaru** [comment]
I have added support for renaming:

* Screens
* Entities
* Files
* Entity folders
* Folders in Global Content
* Objects in Screens/Entities

I have to add each type explicitly, so let me know if this covers the cases you want or if you want additional types.  If you do, you can either reopen this issue, or create a new one with the types you'd like to be able to rename with F2.

8188097420abea527e5fb86dd23720a94d774d46

![31_11 49 45](https://user-images.githubusercontent.com/729631/210153196-81c15519-d91b-42fc-acb4-178796f1ff8d.gif)
