### ISSUE TITLE
Texture preview panel default zoom level is too far away

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#865]
The current behavior seems to be to have a very distant starting zoom level -so I think textures like big tilesets fit in the screen by default- and then the user changes the zoom level and it stays that way for the next texture that is previewed.

In my game I have very small textures, like 6x6, 4x6 and sizes like that so at the start the texture looks like a fly on the window:
![imaxe](https://user-images.githubusercontent.com/24922404/210059800-ce8d56c4-c05d-4f90-a956-8de064a77907.png)

Then I zoom in to see it better but the texture gets out of the visible area and panning is a little sluggish to work with. Then I see a bigger texture and I have to zoom out a lot.

I can think of some things that could be done as an improvement -they are options, I don't mean to do all three-:
a) Create a "fit to window" button inside the panel. In addition there could also be a zoom level dropdown like in Photoshop.
b) Make the starting zoom level change depending on the size of the texture.
c) Set an initial zoom level not so far away and/or improve zoom/pan controls.

**Comment by vchelaru** [comment]
While I like all of the options above, I am going to go for the quick-and-easy solution. I've now made it so when you select a texture, it fits the window. Is this okay? I'm going to close it, but please reopen if not with feedback.

![30_16 20 38](https://user-images.githubusercontent.com/729631/210117580-e6734fb0-a4a1-4f9e-99f5-a84cdafd0d51.gif)

**Comment by vchelaru** [comment]
Oops forgot to put the commit:

293e96bf187f88b3079b35e98cbd9f5ae97a1d42
