### ISSUE TITLE
Derived Objects Don't Respect Base Type Changes

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#870]
1. Create base entity
2. Create derived entity from base
3. Create object (was tested with circle) on base type
4. Set SetByDerived to true on base object
5. Change SourceClassType of the base object (was tested by changing to rectangle), the derived object's type is not changed and compilation errors spawn as a result

**Comment by vchelaru** [comment]
Fixed

0b1bbb38a2ed27f0a3e83eabcb6c1c892067144d
