### ISSUE TITLE
Animation condition "Movement Name" does not list movement values from base members

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#872]
1. Create base platformer entity
2. Create derived entity from base
3. Add X platformer movement type
4. navigate to derived entity's Entity Input Movement -> Animation -> Movement Name, dropdown contains <NULL> and X, but not "Ground" and "Air" from base entity

**Comment by vchelaru** [comment]
Fixed

![image](https://user-images.githubusercontent.com/729631/210174333-49b1dd54-16db-40c7-894c-fc36467a87fd.png)

5d91c76cadc124696a8e2d36803e3e09ab14cd07
