### ISSUE TITLE
Animation condition "Movement Name" selecting <NULL> breaks animations

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#873]
Select <NULL> in Entity Input Movement -> Animation -> Movement Name. Default value should be blank, blank value works as expected. Selecting <NULL> causes that animation layer to set the current animation chain index to -1

### in PlatformerAnimationController.Generated:
![image](https://user-images.githubusercontent.com/6179393/210162329-fda336f6-a776-49b3-8eb3-a57a0eabf6fd.png)
`configuration.MovementName` is the string `"<NULL>"`

**Comment by vchelaru** [comment]
Fixed

057010ec9d27f3f55de90c50849817cd3ad6019c
