### ISSUE TITLE
F2 rename doesn't work on content folders

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#878]
Renaming content folders doesn't seem to work:
![imaxe](https://user-images.githubusercontent.com/24922404/210231427-73489379-fa48-4985-8f33-bf7456db2634.png)

After the operation:
![imaxe](https://user-images.githubusercontent.com/24922404/210231440-49ec0255-6757-454f-b968-0fe12275ef84.png)

The folder loses track of the files it contains and it isn't renamed after all. Restarting Glue brings back the files.
Also noticed that the whole project gets refreshed after the operation, not a problem because it's fast but I mention it just in case it's of interest.

**Comment by vchelaru** [comment]
Fixed

0c78694862980982b561f5e36c0977c1695c2527

![02_07 16 18](https://user-images.githubusercontent.com/729631/210243239-a015a1bf-1bce-42fe-a1a9-6c67635c2921.gif)
