### ISSUE TITLE
F2 renamed content folder which uses wildcards still losing contained files until restarting the Editor

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#881]
![imaxe](https://user-images.githubusercontent.com/24922404/210268432-98cc12ce-ebd9-4d9e-a9d6-406f98495b8f.png)

After the rename:

![imaxe](https://user-images.githubusercontent.com/24922404/210268443-205eb01c-0754-4893-92fe-4d2a47d45e9a.png)

The files are dissapearing from the UI but the renames are properly done on the Visual Studio references and the game runs.

**Comment by vchelaru** [comment]
I believe this has been fixed with await calls.

64096249ce9fc7de01aaa6c09601e1aae69e1054

Waiting for @mfigueirido to test it to make sure it solves it for him before closing the issue.
