### ISSUE TITLE
new top down wizard project creating 2x PlayerList in GameScreen

### ISSUE THREAD

**Issue by dubhlaidh** [vchelaru/FlatRedBall#893]
New Project -> Standard Top Down.  Note: the second time I did it the project initially opened w/o the error dialog but reloading the project showed the dialog.

![image](https://user-images.githubusercontent.com/10093926/211218784-978e6ecc-dd1b-4405-ac75-67fd8a0ce532.png)

![image](https://user-images.githubusercontent.com/10093926/211218655-7654fac0-a017-472d-a946-635f950e5ca6.png)

**Comment by vchelaru** [comment]
Fixed

03d949e1d06a7329bdf6027bc772a30e62423808
