### ISSUE TITLE
Documentation Damage Dealing 01

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#897]
https://flatredball.com/documentation/tutorials/damage-dealing/01-setup/
### Typo
![image](https://user-images.githubusercontent.com/6179393/211896904-9c1e5ec3-9534-4418-a5be-c207bb7647b8.png)
### Typo
![image](https://user-images.githubusercontent.com/6179393/211896911-3866d883-4739-47de-aac1-14993f662f66.png)
### I would just say "Shoot 'em up". I was able to guess what it meant, but I had to look it up.
![image](https://user-images.githubusercontent.com/6179393/211896912-45dc64fc-301d-4d1d-acd0-32de91c2fdbf.png)
### No link to next tutorial step at the bottom like in https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-creating-a-glue-project/ for example

**Comment by vchelaru** [comment]
Fixed.
