### ISSUE TITLE
Entity delete dialog buttons very hard to read

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#90]
On a 200% DPI screen, the button text is chopped to be almost unreadable.

[Edit: uploaded proper screenshot to replace camera picture.]
![Screenshot of Glue delete dialog showing three buttons where the text is chopped off halfway down the letters.](https://user-images.githubusercontent.com/713665/118137388-64236280-b3c2-11eb-8d46-9984b95efd0b.png)

**Comment by vchelaru** [comment]
Fixed.

76f8e1466db1b3f6ffbba6cf6dd3ad02cd6fbf51
