### ISSUE TITLE
Ability to open content files with external editor from within FRB

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#914]
Right now PNG, WAV, OGG and MP3 files are previewed inside FRB which is great because it's fast and avoids opening new windows on your desktop but sometimes you need to edit those files. I think another improvement in this area would be to be able to open the files with and external app. It could be done via the right-click menu. The file could be open with Windows assigned app for that extension but I think in my case I would prefer to leave Windows associations to their defaults and configure -in some kind of settings dialog- the app I want like Aseprite or GraphicsGale for PNG and Audacity for audio files.

Edit: Just realized there is already a file association UI:
![imaxe](https://user-images.githubusercontent.com/24922404/213170739-102e2cff-b213-4176-bbc4-d280280e7d9f.png)

**Comment by vchelaru** [comment]
Fixed

![18_07 26 28](https://user-images.githubusercontent.com/729631/213196921-4d008f7e-ee42-4dcb-855d-e5e2d4b65f37.gif)

7e351e560986e2aa2f0add6781d1c48fc47de7a8
