### ISSUE TITLE
Previewed files should have their preview updated automatically

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#917]
For PNG files I have to preview a different PNG and come back in order to get the view updated after the texture changed on disk.
For audio files I suspect it's the same behavior because I found this other issue: https://github.com/vchelaru/FlatRedBall/issues/916.

**Comment by vchelaru** [comment]
Fixed

![18_06 47 44](https://user-images.githubusercontent.com/729631/213188009-a2c5da06-11e4-42d9-af2b-7dd15a49e215.gif)

d03524157476eea6ad1e94e63c5898b0532d5eb5
