### ISSUE TITLE
Add WAV, OGG and MP3 extensions to file association window

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#919]
![imaxe](https://user-images.githubusercontent.com/24922404/213267740-8d004bdb-eed3-4d93-bb66-a1d81c6d40d1.png)
Those extensions are absent from the UI. Also note that the window is cut at the bottom.

**Comment by vchelaru** [comment]
Fixed
2f917aa16af4efdd154176931a1c4601a384cc72
