### ISSUE TITLE
Ability to copy and paste a content file anywhere

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#930]
There seems to be a sort of copy/paste functionality already but it only pastes the new file onto the folder you copied it.

The file should be able to be pasted on the current selected folder with "control+C", "control+V" keyboard shortcuts and/or copy/paste right-click menus. If a file is selected the selected folder is understood to be the one that file sits on.

**Comment by mfigueirido** [comment]
I forgot about this but it would be even better if there was the ability to copy and paste full folders with their contents if it isn't too complicated.

**Comment by vchelaru** [comment]
![image](https://user-images.githubusercontent.com/729631/216985760-2ee44695-4bff-49d3-9b26-19a410491df5.png)

Miguel says:

That's deep into the Global Content tree
I expect a new folder called "Desk1" with its contents identical to "Desk" to appear after pasting it into "HouseStudy" 
For files similar behaviour like Windows explorer

**Comment by vchelaru** [comment]
Copy/paste of files works currently. Folders do not.

**Comment by vchelaru** [comment]
8c785ab660c890628f764b2a80c893930f1479b1

![07_06 09 29](https://user-images.githubusercontent.com/729631/217254071-e2f51b54-ed5d-4f6e-9a3d-54e6d314f4fc.gif)
