### ISSUE TITLE
Move object to list dialog buttons impossible to read

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#94]
On a 200% DPI screen, the buttons are cropped so far that no text is visible.

![Screenshot of Glue object moving dialog where action buttons are only visible a tiny amount on the left side and no text is visible.](https://user-images.githubusercontent.com/713665/118137621-a3ea4a00-b3c2-11eb-91ed-1448e704eaaa.png)

**Comment by patridge** [comment]
Possibly related to #90.

**Comment by vchelaru** [comment]
Fixed b2a10fc09bb593ab15e68675b49f4ad2e6b26fef
