### ISSUE TITLE
Content in Game window does not use full window area when switching to edit mode while running the game in Glue

### ISSUE THREAD

**Issue by dantogno** [vchelaru/FlatRedBall#950]
# Environment info
I'm on a 4K monitor with 100% scaling in Windows 11. Game is set to 16x9.

![image](https://user-images.githubusercontent.com/3150710/216786988-6b1b2d29-60d9-4de0-9e49-98cb6868e983.png)

# Steps to reproduce
1.  Load the project and click play in Glue.
2. Hit the edit button.

## Results
Usable space is limited to 16x9 even though the Game window has much more space to take advantage of:
![image](https://user-images.githubusercontent.com/3150710/216786887-d406c0ec-58c2-49c8-bd71-e5499d618102.png)

## Notes / expected results
If you resize the Glue window, this issue corrects itself, but it will come back any time you stop the running game, hit play and then hit edit.

![image](https://user-images.githubusercontent.com/3150710/216786949-690415b9-8fdf-4814-bb9e-76506051b95c.png)

**Comment by vchelaru** [comment]
This may be a problem with .NET 4.7.X projects. I'm going to upgrade this project to .NET 6 to see if that's the problem. If moving to .NET 6 fixes it, I think we close this issue out, as no one is making 4.7 projects anymore.

**Comment by vchelaru** [comment]
I haven't heard that this is still a problem, so closing it out.
