### ISSUE TITLE
Gum should not stop functioning properly when a file in use is deleted

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#953]
Repro:

1. Have a Component A that includes an instance of Component B as well as some other instances
2. Delete Component B
3. Select any instance that's _not_ Component B in Componant A
4. Now select Component B
5. Observe that variables window continues to show previously-selected component
6. Variables window will not update now, regardless of what component you select

Expected behavior: Gum uses some generic standard type to display missing components (container with a red-dotted line?) and a warning icon and does not crash.

Actual behavior: Gum stops working properly

Gif:
![gum-deleted-file](https://user-images.githubusercontent.com/711100/217311070-9a83a867-53d0-4354-8fa6-64463a1b48e6.gif)

**Comment by vchelaru** [comment]
Now Gum will display the component using default values. A red exclamation appears, and it no longer crashes.

Fixed on Gum commit 3d7df2d2e2846f6f74e8db843cfb64479e72ab7d
