### ISSUE TITLE
MonoGame content project error message seems truncated

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#983]
![Glue error screenshot saying the error message below.](https://user-images.githubusercontent.com/713665/224177583-b42eb4a8-d149-4c6e-af7e-b748d19f21d9.png)

When I loaded an [old monthly game](https://github.com/profexorgeek/Shiprekt) (after a lot of solution reference tweaking), I got the above error.

While I don't really understand what it's saying, it also seems to have some issues.

* It says to search for the "following text", but there is no text following that message.
* No space between "building." and "To" of the next sentence.

For reference, here's the full text of the error message.

> Could not load the project C:/dev/_frb/FlatRedBall-Games/Shiprekt/Shiprekt\Shiprekt.csproj
> because MonoGame 3.7.1 files are missing. click OK to open your browser to the MonoGame 3.7.1 install location:
> 
> https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGameSetup.exe
> 
> Alternatively you can remove the MonoGame content project from your .csproj. You probably don't need it if FlatRedBall is handling your content building.To do this, search your .csproj file for the following text and delete it

And if it is related, the following error was logged in the Glue Output tab after all the other build output.

> The imported project "C:\Program Files\dotnet\sdk\7.0.201\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\7.0.201\MonoGame\v3.0\MonoGame.Content.Builder.targets" is correct, and that the file exists on disk.  C:\dev\_frb\FlatRedBall-Games\Shiprekt\Shiprekt\Shiprekt.csproj

**Comment by vchelaru** [comment]
This has been fixed, and Glue now gives a way more informative error when trying to load .NET 4.7.1 projects.
