### ISSUE TITLE
Add search to list that appears when choosing a sidebar preview image from entity list

### ISSUE THREAD

**Issue by dantogno** [vchelaru/FlatRedBall#987]
The list can be long, so searching would be helpful.

![image](https://user-images.githubusercontent.com/3150710/224504737-505f82d4-686c-4854-9478-8596345b905d.png)

![image](https://user-images.githubusercontent.com/3150710/224504750-9acdc29a-62a1-4b50-9781-1672d22a7324.png)

**Comment by vchelaru** [comment]
![29_06 39 07](https://user-images.githubusercontent.com/729631/228537851-77eda16b-7f61-465c-be96-71d53b026cf6.gif)

5c232e7b4daaee5f063ab07a2773a8db87d95c4d
