### ISSUE TITLE
Cursor movement when gamepad-controlled should be tracked as a double

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#993]
I had an issue where the cursor wasn't moving [consistently] in my game when controlled by a gamepad. I investigated and it ended up that my game was running at an uncapped framerate. The per-frame movement of the cursor is calculated as a `float` but cast to an `int` each frame. At high framerates, this means cursor movement is often clamped to zero.

You should track cursor movement as a `float` or even a `double` and cast/round to an `int` just before it has to be converted to whole numbers in screenspace. This will ensure that very small movement amounts properly accumulate.

The specific method is `Cursor.UpdateValuesFromJoystick` which is here:
https://github.com/vchelaru/FlatRedBall/blob/NetStandard/Engines/FlatRedBallXNA/FlatRedBall/Gui/Cursor.cs#L2469

And looks like this at the time of this posting:

```csharp
private void UpdateValuesFromJoystick(Xbox360GamePad gamepad)
{
  if (gamepad != null)
  {
      // ... method truncated for clarity
      
      // mScreenX and mScreenY are clamped to int - If thisFrameMultiplier is really small they will always be zero!
      var thisFrameMultiplier = GamepadPixelsPerSecondMovementSpeed * TimeManager.SecondDifference;
      mScreenX += (int)(xPosition * thisFrameMultiplier);
      mScreenY -= (int)(yPosition * thisFrameMultiplier);
      
      //... method truncated for clarity
   }
}
```

**Comment by vchelaru** [comment]
FPS is shown in that text:

![22_08 58 29](https://user-images.githubusercontent.com/729631/226947216-a529e6f8-d193-4968-b094-2dcb7056b340.gif)


d39841756a56ee2cd4be0d1672481861613f1662
